### ISSUE TITLE
Webview as overlay

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/RootEncoder#1004]
Just like to know whether it is possible to use WebView as one of the overlay in the application.

**Comment by MTayyabSarfraz** [comment]
yes .. you can by rendering your webview using AndroidViewFilterRenderer.
example in **OpenGlRtmpActivity** class under filter name AndroidView!

**Comment by pedroSG94** [comment]
As indicated by @MTayyabSarfraz this is the line example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L164

**Comment by mylaimani** [comment]
Thanks @MTayyabSarfraz @pedroSG94 it is working fine

**Comment by mylaimani** [comment]
I tried to implement the code, in mobile camera view, the WebView is showing but in live stream it is not displaying. I am trying to display it in full screen. Am I doing anything wrong

           rtmpCamera1 = new RtmpCamera1(openGlView, this);
            ProgressDialog progDailog;
            progDailog = ProgressDialog.show(MCStreamingActivity.this, "Loading", "Please wait...", true);
            progDailog.setCancelable(false);
            openGlView.getHolder().addCallback(this);
            openGlView.setOnTouchListener(this);
            animationWebView.setBackgroundColor(Color.TRANSPARENT);
            animationWebView.getSettings().setJavaScriptEnabled(true);
            animationWebView.getSettings().setLoadWithOverviewMode(true);
            animationWebView.getSettings().setUseWideViewPort(true);
            animationWebView.setWebViewClient(new WebViewClient() {
                @Override
                public boolean shouldOverrideUrlLoading(WebView view, String url) {
                    progDailog.show();
                    view.loadUrl(url);

                    return true;
                }
                @Override
                public void onPageFinished(WebView view, final String url) {
                    progDailog.dismiss();
                }
            });

            animationWebView.loadUrl("https://msn.com");

            AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
            androidViewFilterRender.setView(animationWebView);
            rtmpCamera1.getGlInterface().setFilter(androidViewFilterRender);

**Comment by mylaimani** [comment]
This is camera view
![device-2021-12-09-181721](https://user-images.githubusercontent.com/4998347/145399477-ce92969a-c57c-451c-8bdc-d2b13b67ae92.png)

This is live view
![Uploading Screenshot 2021-12-09 at 6.17.55 PM.png…]()

The WebView is in the top

**Comment by pedroSG94** [comment]
Hello,

try to add filter after startStream is called

**Comment by mylaimani** [comment]
I tried that also

     rtmpCamera1.startStream(value); //Start Live Streaming
     androidViewFilterRender = new AndroidViewFilterRender();
     androidViewFilterRender.setView(animationWebView);
     rtmpCamera1.getGlInterface().setFilter(androidViewFilterRender); //add render to filter

Then also web view is not showing, I feel web view is not added to filter, so only its position in the camera screen is wrong. If it added means it would have been inside the camera view.

**Comment by pedroSG94** [comment]
Are you using more than a filter?
Did you try using  rtmpCamera1.getGlInterface().addFilter(androidViewFilterRender); instead of setfilter?
It is isn't working share me activity code to reproduce the problem.
Also rememeber that the view must be inflated before add it to filter.

**Comment by mylaimani** [comment]
<img width="1074" alt="Screenshot 2021-12-21 at 2 32 42 PM" src="https://user-images.githubusercontent.com/4998347/146903011-d01062ae-c55a-4239-82dc-24306dd5973f.png">

In our application I am trying to bring exactly same kind of view, but it is not coming correctly.

It comes like this

![device-2021-12-21-144515](https://user-images.githubusercontent.com/4998347/146904387-13044189-a446-4297-b496-a527c030e0e0.png)

My stream preview size is 1920 x 1080, I am trying to bring the same size for the WebView also

    private void setBrowser() {
        try {
            AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
            androidViewFilterRender.setView(animationWebView);
            rtmpCamera1.getGlInterface().addFilter(androidViewFilterRender);
            androidViewFilterRender.setPosition(0,0);
            androidViewFilterRender.setPreviewSize(1920, 1080);
            spriteGestureController.setBaseObjectFilterRender(androidViewFilterRender); //Optional
            spriteGestureController.setPreventMoveOutside(true);
            animationWebView.setVisibility(View.INVISIBLE);
        } catch (Exception e){
            Toast.makeText(MainActivity.this,"Include WebView " + e.toString(),Toast.LENGTH_LONG).show();
        }
    }

**Comment by mylaimani** [comment]
I resolved the problem using this method
**androidViewFilterRender.setScale(37, 37);**
Giving the result needed. 

Need to add one more filter


private void setBrowser() {
        try {
            AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
            androidViewFilterRender.setView(animationWebView);
            androidViewFilterRender.setPosition(0,0);
            androidViewFilterRender.setScale(37, 37);
            rtmpCamera1.getGlInterface().addFilter(androidViewFilterRender);
            spriteGestureController.setBaseObjectFilterRender(androidViewFilterRender); //Optional
            spriteGestureController.setPreventMoveOutside(true);
            animationWebView.setVisibility(View.INVISIBLE);
        } catch (Exception e){
            Toast.makeText(MainActivity.this,"Include WebView " + e.toString(),Toast.LENGTH_LONG).show();
        }
    }
