### ISSUE TITLE
VideoEncoder: Encoding error java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ramapitecusment** [pedroSG94/RootEncoder#1008]
Good day. You created an excellent RTSP stream library for Android. However, I am experiencing some issues with it. Could you, please, help me with solution? I use you library for display streaming. Resolution 1920*544. 
This problem occurs only on Android 5.0 and Android 5.1 devices. The same code on Android 6+ works perfect.

Possible problem with h264 encoder. https://stackoverflow.com/a/30506941. Everything works with 352*288 resolution. I understand that it could be an OS Android issue, but I need support for higher resolutions. Probably there is a way to change encoder/decoder or different solution. Probably, this artcle could help: https://medium.com/bumble-tech/webrtc-on-android-how-to-enable-hardware-encoding-on-multiple-devices-5bd819c0ce5

Error log: [Error log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7682170/Error.log.txt)

Result for CodecUtil.showAllCodecsInfo(): [Codecs.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7682169/Codecs.txt)

Code:
```
    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
    private fun initRTSPServer() {
        rtspServer?.stopStream()
        if (rtspServer == null) {
            rtspServer = RtspServerDisplay(getApplication(), USE_OPENGL, connectionCheckerRtsp, RTSP_PORT)
            rtspServer?.setForce(CodecUtil.Force.FIRST_COMPATIBLE_FOUND, CodecUtil.Force.FIRST_COMPATIBLE_FOUND)
        }
        if (resultCode == null || resultIntent == null) {
            rtspServer?.sendIntent()?.let { /* call permission  */ }
        } else {
            startStream()
        }
    }

    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
    fun onScreenStreamResultOK(resultCode: Int, data: Intent) {
        this.resultCode = resultCode
        resultIntent = data
        rtspServer?.setIntentResult(resultCode, data)
        startStream()
    }

    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
    private fun startStream() {
        rtspServer?.let {
            if (it.prepareVideo(1920, 544, 1920*544) ) {
                if (!it.isStreaming) it.startStream()
            } else {
                Timber.e("Unable to start RTSP server")
                it.stopStream()
            }
        }
    }
```

    implementation 'com.github.pedroSG94:RTSP-Server:1.1.6'
    implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.4'

I also tried older library versions

In addition, i tried:
```
prepareVideo(1920, 544, 30, 1920*544, 0, 320, MediaCodecInfo.CodecProfileLevel./*AVCProfileExtended and other AVC profiles*/, -1, 2)
```

```
rtspServer?.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND)
```
Changing bitrate also does not help. Only changing the resolution helps.

**Comment by pedroSG94** [comment]
Hello,

As you can see in your Codec.txt you can't use a resolution higher of 896 in that device. This is your only video encoder for h264:
```
    ----------------
    Name: OMX.google.h264.encoder
    Type: video/avc
    ----- Encoder info -----
    Complexity range: 0 - 0
    CBR supported: false
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    21
    2130708361
    Profile: 1, level: 1
    Profile: 1, level: 2
    Profile: 1, level: 4
    Profile: 1, level: 8
    Profile: 1, level: 16
    Profile: 1, level: 32
    Bitrate range: 1 - 2000000
    Frame rate range: 0 - 960
    Width range: 16 - 896
    Height range: 16 - 896
    ----- -----
```

I can't do anything about it. This look like you are using an emulator that sometimes have this problem with encoder that only support low resolutions. In a physical device, normally, you have a hardware encoder with higher resolutions.

**Comment by ramapitecusment** [comment]
But with 896x896 also does not work too. Only something lower thab 352*288. If i set 353*288 or higher, it fails. Additionally, unfortunately physical device does not have hardware encoder for h264 encoder, as well as software encoder =( . Could you, please, give me an advice how I can change the codec from h264 to vp8?

**Comment by ramapitecusment** [comment]
This is a custom board with processor that does not have h264 or h265 encoder/decoder

**Comment by pedroSG94** [comment]
VP8 is not supported in this library. Only h264 and h265 are supported.

About the error:
I found a similar problem in API 16 emulator that only work with 352x288 using that codec. I can't do anything about it because I can't modify the encoder in the room (This require access to root and it isn't a general solution so it is totally discarded) and I'm using MediaCodec that is a low level wrapper to that codec.
OMX.google.h264.encoder is a software encoder that is implemented in all Android devices. If you have root access to the room you can add other encoder to Android or update that encoder version:
https://stackoverflow.com/questions/17217845/writing-custom-codecs-for-android-using-ffmpeg
https://source.android.com/devices/media

Also, you can replace VideoEncoder class with other external software encoder.

As you can see all this solutions could be hard to implement and has no sense to add only for a special case so I think that your only solution is update that device to Android 6+ or cap resolution to 352x288 in that Android version.
