### ISSUE TITLE
OpenGlView losing content loaded upon resuming back to activity

### ISSUE THREAD

**Issue by MTayyabSarfraz** [pedroSG94/RootEncoder#1014]
I'm using `OpenGlActivity` and adding an `AndroidViewFilter` to it.

I have to pick an image from the gallery and present it back on the` OpenGlView`(using addFilter() method).

Now here is the issue I'm facing.
if go to another Activity(Like of GalleryChooser using startActivityForResult) and comes back to my OpenGLActivity...
previously added layouts are removed. I believe SurfaceView instance gets destroyed while I move to another activity or might be I'm wrong (I don't know the exact reason). Worth mentioning I'm using addFilter() method not setFilter() so there is no chance that previously added filters are cleared and a new one is set over it.
Is there a way to retain all the filters while moving to and forth the activities or when the app gets passed (in background)!!

**Comment by pedroSG94** [comment]
Hello,

Each time you replace glInterface you lose all filters attached to it. It is because each filter have a reference to ManagerRender and this class is different in each glInterface.
I only can recommend you save filters configuration and add it again each time you change glInterface. For example:
Create a Hashmap of filters setted to stream and add it again. Where key is filter type and value is a object with filter configuration that contain position, scale, any custom value, etc.

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 i've done some thing like this ,it is working fine for me.... wonder if it is the right approach or not..plz. ignore the filterConfigurations(I'll take care of it later ):

```
`@Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int width, int height) {
//        Size optimalSize = getOptimalPreviewSize(rtmpCamera1.getResolutionsBack(), getResources().getDisplayMetrics().widthPixels, getResources().getDisplayMetrics().heightPixels);
//        SizeCalculator.getViewport(false,0,width,height,1920, 1080);
//        rtmpCamera1.startPreview(optimalSize.getHeight(), optimalSize.getWidth());
//        Log.e("snajdbds", "surfaceChanged: y:"+points.second.y+ "  x"+ points.first.x );
        rtmpCamera1.startPreview(width, height);
        if (isSurfaceViewDestroyed) {
            restoreViews();
        }
        isSurfaceViewDestroyed = false;
    }

```
    /**
     * upon moving to other activity or app gets in background ... surfaceView is destroyed and all applied views are to be restored using this method
     */
    private void restoreViews() {
        rtmpCamera1.replaceView(openGlView);

        glInterFace.addFilter(webViewRenderer);
        webViewRenderer.setView(webView);
        glInterFace.addFilter(imageRenderer);
        imageRenderer.setView(imageView);
    }`

**Comment by MTayyabSarfraz** [comment]
well, it is crashing sometimes... when intensively tested :(

**Comment by pedroSG94** [comment]
Yes, that should be fine.
I'm not sure if I will do it automatically in the future because I can do it automatically in few cases but using, for example, ImageObjectFilterRender I'm creating a texture asociated to an eglContext and it is destroyed so I can't re use it and this make really difficult to duplicate the filter.

Can you share me crash logs?

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 [here is the gist of crashLogs](https://gist.github.com/MTayyabSarfraz/9f2ff5463b5e7caf5bb7dcc772ae9b44)

I was trying to find the concrete crash cause but am unable to find it, I think the crash is being handled by ExceptionHandler.

Also please note that I'm using my activity in LandScape Mode and the gallery is opening in portrait mode 
so upon Changing orientation, the instance isn't saved, which might be causing the state loss of everything on the activity.

I'm working in this direction, let me know if these logs are of any help.

one  more thing worth mentioning is I have also tried the build with portrait mode, but Is still crashing.

there are two scenarios to watch,

1. Moving to another activity, and coming back without setting result i.e back button is Pressed.
2. Moving to another activity, and coming back with setting some  result i.e selecting some image.

for 1st scenario, it crashes sometimes, but for the second scenario it is always Crashing.

> ImageObjectFilterRender I'm creating a texture asociated to an eglContext and it is destroyed so I can't re use it and this make really difficult to duplicate the filter.
 
 for this case... I'm not using ImageObjectFilterRender I'm using AndroidViewFilterRenderer ...so it won't effect any thing.

**Comment by MTayyabSarfraz** [comment]
here it is .. 

`
    @Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        if (rtmpCamera1.isRecording()) {
            rtmpCamera1.stopRecord();
            bRecord.setText(R.string.start_record);
            Toast.makeText(this,
                    "file " + currentDateAndTime + ".mp4 saved in " + folder.getAbsolutePath(),
                    Toast.LENGTH_SHORT).show();
            currentDateAndTime = "";
        }
        if (rtmpCamera1.isStreaming()) {
            rtmpCamera1.stopStream();
            button.setText(getResources().getString(R.string.start_button));
        }
        rtmpCamera1.stopPreview();
        isSurfaceViewDestroyed = true;
    }`

**Comment by pedroSG94** [comment]
Try remove filters using clearFilters on surfaceDestroyed because your crash seem an error rendering canvas maybe because your view is not renderable in that moment

**Comment by MTayyabSarfraz** [comment]
no luck.. crashing again.. also ...the camera preview is rotated ClockWise upon Resuming if I  learFilter in `surfaceDestroyed` `
        if (glInterFace != null)
             {glInterFace.clearFilters();}`
for most tests, it crashed..

**Comment by pedroSG94** [comment]
Can you share me full example code to reproduce your case?

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 [i've created a gist for you , includes main activity + layout ](https://gist.github.com/MTayyabSarfraz/06404dd770ccd41240826dfcef0595c9)

**Comment by MTayyabSarfraz** [comment]
@pedroSG94  finally i've got the exact crashing statment 

````
D/Surface: lockCanvas
I/BufferQueueConsumer: [SurfaceTexture-1-2896-0](id:b5000000000,api:4,p:15622,c:2896) disconnect()
I/BufferQueueConsumer: [SurfaceTexture-3-2896-1](id:b5000000001,api:1,p:2896,c:2896) disconnect()
I/BufferQueueConsumer: [SurfaceTexture-4-2896-2](id:b5000000002,api:1,p:2896,c:2896) disconnect()
E/SurfaceManager: GL already released
I/chatty: uid=10731(com.antiquelogic.crickslab) glThread identical 1 line
E/SurfaceManager: GL already released
E/AndroidRuntime: FATAL EXCEPTION: glThread
    Process: com.antiquelogic.crickslab, PID: 2896
    java.lang.RuntimeException: drawScreen end. GL error: 1285
        at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:142)
        at com.pedro.encoder.input.gl.render.ScreenRender.draw(ScreenRender.java:131)
        at com.pedro.encoder.input.gl.render.ManagerRender.drawScreen(ManagerRender.java:76)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:184)
        at java.lang.Thread.run(Thread.java:923)
I/BufferQueueProducer: [SurfaceTexture-1-2896-0](id:b5000000000,api:4,p:15622,c:2896) disconnect(): api=4
E/CameraManagerGlobal: Camera 3 is not available. Ignore physical camera status change
E/Parcel: Reading a NULL string not supported here.
I/Process: Sending signal. PID: 2896 SIG: 9
````

**Comment by pedroSG94** [comment]
I'm not able to compile your gist so I did a branch to emulate your case but I can't reproduce your crash:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/i1014

This basically add a ImageView and WebView to stream using AndroidViewFilters when you click on the button menu to add it. After that, if you press switchCamera this open file explorer to find an image and if you go back and you already added AndroidViewFilter this is automatically added after startPreview.
This is working fine for me without any crash. Let me know where is my mistake to reproduce your case (I'm not doing anything with image from file explorer because I don't know what is doing your ImageFromGalleryPickup)

About your error reported. This is an out of memorry error:
https://developer.android.com/reference/android/opengl/GLES20
Maybe you are using an image so big. Try to resize it to 720p for example.

Since this seems an error of this type I will need your help to create an enviroment to reproduce the case so maybe image used is necessary.

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 i've switched to i1014.
i've tested on two devices And it is crashing for me  on both.

I am unable to understand  `GL_OUT_OF_MEMORY` exception thing.

` (I'm not doing anything with image from file explorer because I don't know what is doing your ImageFromGalleryPickup)`

Actually for now this has nothing to do with imageselection.it just opens the default Android gallery for picking images. no handling/processing be done after choosing ... 

You can maybe reproduce the issue by loading webView content then moving to and forth from OpenGlActivity to image chooser and select some image... come back... wait for webview to load and then again selecting image and coming back..

repeat this process few time and hope y'll be able to reproduce the crash..
For now, just test with only one filter (with webView) ...and try reloading the previously-stored instance of webView .. as applying only one filter(webView also generates the crash)

In my opinion, this crash has nothing to do with the image size as I'm not processing/rendering that selected image at any stage for now... to keep things simple... 

Also can you specify the model/make , specs of your device on which you are testing


@pedroSG94 bro I didn't have write access to this branch so I'm attaching a gist of my updated code to simulate error on your side .
[here is the gist link,simply copy this code and pase in yours **OpenGlRtmpActivity** class](https://gist.github.com/MTayyabSarfraz/212646bfb9c2d77d9686e70442699709)
Thanks

**Comment by pedroSG94** [comment]
Your code is working fine for me. The only problem is that I'm not able to load your Webview url but I can't get any crash after add android view filter and select an image. I tried it about 20 times without a crash.
I'm using 2 devices:
Oneplus 7T (Android 11) and Samsung Galaxy S7 (Android 8) specifications links:
https://www.gsmarena.com/oneplus_7t-9816.php
https://www.gsmarena.com/samsung_galaxy_s7-7821.php
