### ISSUE TITLE
Add SEI NALU

### ISSUE THREAD

**Issue by jacklai24** [pedroSG94/RootEncoder#1016]
Hi Pedro,

I looked at the source code and it seems that there is no way to add SEI. Could I just ask you a question? Do you consider adding this feature?

**Comment by pedroSG94** [comment]
Hello,

This could be added in the future but for now I'm not really interesed on it because this extra data normally is send using other socket instead of in the h264 data.
Also, in most of cases the player side (that is normally the principal reason to add it) doesn't support it.

**Comment by jacklai24** [comment]
Thanks for your reply. I'll try to implement this feature and feedback to you.
