### ISSUE TITLE
rtsp模块是否可以支持组播

### ISSUE THREAD

**Issue by HelloTodayWolrd** [pedroSG94/RootEncoder#1019]

**Comment by pedroSG94** [comment]
If you means stream to 2 or more endpoint at same time you can do it using MultiRtp:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/rtplibrary/src/main/java/com/pedro/rtplibrary/multiple
In the header class you have a description of how to adapt a normal RtmpCamera1 to MultiRtpCamera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/multiple/MultiRtpCamera1.java#L44
