### ISSUE TITLE
RuntimeException: Error during updateTexImage

### ISSUE THREAD

**Issue by svprdga** [pedroSG94/RootEncoder#1022]
In my app I use this library to stream the screen of the user.

I am receiving a lot of crashes from my users in my error tracker tool, the log that I have is:

> Fatal Exception: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
>        at android.graphics.SurfaceTexture.nativeUpdateTexImage(SurfaceTexture.java)
>        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
>        at com.pedro.encoder.input.gl.render.CameraRender.updateTexImage(CameraRender.java:2)
>        at com.pedro.encoder.input.gl.render.ManagerRender.updateFrame(ManagerRender.java:2)
>        at com.pedro.rtplibrary.view.OffScreenGlThread.run(OffScreenGlThread.java:80)
>        at java.lang.Thread.run(Thread.java:923)

It happens in many brands and many versions of Android, so it doesn't seem to be related to any specific device model or type.

I couldn't personally reproduce it, I only know that it happens at some point of the screen broadcast.

Version: `2.1.4`

**Comment by pedroSG94** [comment]
Hello,

I will need more info about it.

Do you have any way to get a full logcat?

Can you specidfy a bit the enviroment crash (device model, Android API, time streaming to know if crash on start, while streaming or stopping)?

Do you have any way to get logs from this class? This could give me info to know where is the fail.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/SurfaceManager.java

**Comment by pedroSG94** [comment]
Closing as inactive.
