### ISSUE TITLE
push texture from diff source

### ISSUE THREAD

**Issue by soham24** [pedroSG94/RootEncoder#1024]
I am using https://github.com/CainKernel/CainCamera to render filters, I need to push this stream using your library.

I am using CameraTextureView specifically, which extends textureview. https://github.com/CainKernel/CainCamera/blob/master/cameralibrary/src/main/java/com/cgfay/camera/widget/CameraTextureView.java 

@pedroSG94 @cainkernel

**Comment by pedroSG94** [comment]
Sorry but implement that library with my library is not worth due to the time to study and develop it.

If you can get a way to extract raw h264 and AAC buffers from that library you can use RtmpClient or RtspClient class directly to stream.

**Comment by soham24** [comment]
thats fair. @pedroSG94 
this given library gives method to record video via ffmpeg . I think 
I need to explore more in this direction to get h264 data .

**Comment by pedroSG94** [comment]
Closing as inactive
