### ISSUE TITLE
Unresolved reference: code

### ISSUE THREAD

**Issue by publioelon** [pedroSG94/RootEncoder#1025]
When trying to run the gradle build the following error is output: 

`Unresolved reference: code`

at path:` \rtsp\src\main\java\com\pedro\rtsp\rtp\sockets\RtpSocketTcp.kt`

Line:  `private val tcpHeader: ByteArray = byteArrayOf('$'.code.toByte(), 0, 0, 0)`

Currently using kotlin version: 1.6.10.

I tried restarting and clearing the cache but the error persists

**Comment by pedroSG94** [comment]
Hello,

It is working for me.
I'm not sure why you are using RtpSocketTcp class but make sure that you added dependencies correctly.
Keep in mind that recently Android Studio set maven repository dependencies in settings.gradle file when you create a new project.
About your kotlin version it is not important you can use this library without add kotlin in your project.
