### ISSUE TITLE
SrsFlvMuxer class missing

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/RootEncoder#1026]
In old version we had this library, net.ossrs.rtmp.SrsFlvMuxer, I am using old version for USB live streaming. Now in the new version we are missing this class **SrsFlvMuxer**

Is there any alternate for the **public class RtmpUSB extends USBBase** that uses SrsFlvMuxer

**Comment by pedroSG94** [comment]
Hello,

You have 2 options:
- Compile library with version 2.0.2 or older (last version with SrsFlvMuxer)
- Compile last library version and replace SrsFlvMuxer with RtmpClient that have a really similar usage
