### ISSUE TITLE
Picture in Picture Mode

### ISSUE THREAD

**Issue by mneckoee** [pedroSG94/RootEncoder#1029]
Hi, I want to implement PIP mode for live Streamer. How can I change the texture view while streaming?

**Comment by pedroSG94** [comment]
In this case you can use [background example](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample) to know how to replace actual view using replaceView method (You will need use a service to avoid remove stream instance).

The idea is use replaceView with context on surfaceDestroyed callback and wait until your new openglview is recreated and use replaceView on surfaceChanged to reload your preview and if you want go back to activity exactly the same.

**Comment by mneckoee** [comment]
What is a "replaceView" ? Do you mean the new openGLView?

**Comment by pedroSG94** [comment]
This is the method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L452
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L457

This method allow you change preview on fly. Context if you want go to background and OpenGlView if you want change OpenGlView (maybe because you last OpenGlView was destroyed and it is not usable anymore).

with new OpenGlView I mean that for Picture in Picture maybe you need to use a widget or other different view that make your Activity die so you can use replaceView for this case.

**Comment by mneckoee** [comment]
![image](https://user-images.githubusercontent.com/16606340/148208974-94ef2a7d-0a39-4642-b7e9-cec452ec0e4d.png)

**Comment by mneckoee** [comment]
> This is the method: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L452 https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L457
> 
> This method allow you change preview on fly. Context if you want go to background and OpenGlView if you want change OpenGlView (maybe because you last OpenGlView was destroyed and it is not usable anymore).
> 
> with new OpenGlView I mean that for Picture in Picture maybe you need to use a widget or other different view that make your Activity die so you can use replaceView for this case.

you are awesome, I inspect your suggested method and inform you about the result

**Comment by DenisStadnichenko** [comment]
@mneckoee Hi, did you manage to implement pip mode?
@pedroSG94 These url's don't work, can you give working links?

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L452 https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L457

**Comment by pedroSG94** [comment]
Updated links:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/Camera2Base.java#L465
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/Camera2Base.java#L470

About your case. You can test rotation example in the app module:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/rotation

Try to compile the project and test rotation example.

**Comment by DenisStadnichenko** [comment]
thanks for the quick reply
