### ISSUE TITLE
How to Creating a Virtual Background in RTMP 

### ISSUE THREAD

**Issue by PongPloy2016** [pedroSG94/RootEncoder#1035]
Hi bro i want Background Removal and Segmentation or Virtual Background Integrate in  live streaming    for exmaple Image 

![1_jKS3pc30553sJe0SZIrUbg](https://user-images.githubusercontent.com/8625469/149558936-e446ab85-82e4-4105-835d-eec7b6787aef.gif)

link : https://towardsdatascience.com/custom-calculators-in-mediapipe-5a245901d595 

in Background Removal and Segmentation

MediaPipe Selfie Segmentation

video : [https://google.github.io/mediapipe/images/selfie_segmentation_web.mp4](url)

https://uploads-ssl.webflow.com/6139ee313144e527fc2c2fdb/614493f96be9f97bef916efd_BG_seg1_optimised-transcode.mp4

I trying like this before question me in link [https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1001](url)
I have studied every category. But it doesn't make any Virtual Background   images coming from outside. 

![image](https://user-images.githubusercontent.com/8625469/149560119-dd93e87b-4081-4a05-be67-1314bf42e4e7.png)

Please I don't know if it supports this or not. please suggest

**Comment by pedroSG94** [comment]
You can try with Chroma filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/ChromaFilterRender.java
It is developed to work with a chroma so you need a green background and taht green color will be replaced to your image

**Comment by PongPloy2016** [comment]
hey bro i not show !  please help not show  Virtual Background  from image please see file is show background color light pink  

please help 

![271489730_968954080379167_7998149970187547267_n](https://user-images.githubusercontent.com/8625469/149763696-03a9f9da-b28e-41f3-bdf0-4f0beedafb47.jpeg)

**Comment by pedroSG94** [comment]
I don't understand.
As I told you it is a chroma filter. Where do you have green color to test?

**Comment by PongPloy2016** [comment]
Thank you for your suggestion and I have some questions about chroma color 
, Is it possible if I would like add more colors for chroma filter and I need add blue color or white color

Thank you for your support

![1570](https://user-images.githubusercontent.com/8625469/149813631-24520a2d-2df1-4753-8d31-bf976422511d.jpg)

**Comment by pedroSG94** [comment]
You need change this glsl file to support it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/chroma_fragment.glsl
