### ISSUE TITLE
How can i use SensorRotationManager​ in openGl activity please?

### ISSUE THREAD

**Issue by medali88** [pedroSG94/RootEncoder#1037]
Hello i want to rotate camera during streaming , i find a   ​class​ ​SensorRotationManager​  but i dont know how to use it .
Can you help me please ? Thanks

**Comment by medali88** [comment]
I sucess to implement SensorRotationManager in OpenGlRtmpActivity but I have this result when I turn the phone in landscape (streamPreview very small)
![IMG20220117105411](https://user-images.githubusercontent.com/26676174/149748277-bda06c57-8594-4c08-8485-5cfad1a97a64.jpg)

**Comment by pedroSG94** [comment]
It is because you started stream in portrait. You should start stream in landscape to get horizontal resolution (full screen) and then when you rotate to protrait it will be adapted correctly.

**Comment by medali88** [comment]
can i adapt horizontal resolution (full screen) when activity fixed to portrait , i want to fixed my app in portrait

**Comment by pedroSG94** [comment]
Actually this feature is limited for landscape activity locked. I will create a feature to allow stream without lock activity in portrait or landscape as you said but it is not developed yet

**Comment by medali88** [comment]
I have another question, is there a method to unlock 60FPS on phones (with the native camera, I can film with 60fps but with your app or other apps I only have 30fps maximum even if with this line for test:
         mPreviewRequestBuilder.set(CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE, new Range<>(60, 60));

)

**Comment by pedroSG94** [comment]
Hello,

It is not possible it is locked by device's manufacturer.
In few models (like Google pixel) you can do it without modify a line of code. You only need specify it on prepareVideo method.
This is totally on manufacturer side.

**Comment by medali88** [comment]
I tested as you told me (I changed 30 to 60 framerate of the onPrepareVideo function) under Xiaomi redmi 8 pro where 60 and 50 fps are unlocked but it doesn't work, I have a black screen when I start the stream

**Comment by pedroSG94** [comment]
Hello,

To know if you have 60 fps allowed in that resolution. Use camera2 with this code:
```java
//get all fps range supported by your device. Print the returned ranges to show it.
rtmpCamera2.getSupportedFps();
//if you can find 60 fps in the above method. Use this method to know if your resolution support 60 fps (replace resolution and facing to the desired in your case).
rtmpCamera2.getSupportedFps(new Size(640, 480), CameraHelper.Facing.BACK);
```

**Comment by Y2Kot** [comment]
Hello, I have the similar problem - when I starting preview in portrait it's became 90 degree rotated in horizontal ( video sample https://disk.yandex.ru/i/UWuMd-Hxuw1gzw). How can I fix this?
