### ISSUE TITLE
Non-increasing DTS with akamaiTs enabled

### ISSUE THREAD

**Issue by 111913** [pedroSG94/RootEncoder#1039]
Hi @pedroSG94 !

When streaming, the following DTS errors occur on our server:
> [flv @ 0000015c24192680] Non-increasing DTS in stream 1: packet 21 with DTS 568, packet 22 with DTS 568
[flv @ 0000015c24192680] Non-increasing DTS in stream 1: packet 22 with DTS 568, packet 23 with DTS 568

> [null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 142240 >= 142240
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 53 >= 53
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 147392 >= 147392
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 149920 >= 149920
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 60 >= 60
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 63 >= 63
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 157696 >= 157696
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 65 >= 65
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 69 >= 69
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 167936 >= 167936
[null @ 0x55943627e8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 170432 >= 170432

Although after reading your comment about Akamai, I called the rtmpCamera2.forceAkamaiTs(true) method. Can you give me any advice, maybe I'm doing something wrong?
Thanks in advance!

**Comment by pedroSG94** [comment]
Hello,

Which server are you using?
Can you write a log here with flvPacket.timeStamp to know ts produced in your device? (show me the logcat)
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L250
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L262

**Comment by BakhromMuydinov** [comment]
Srs server used
I have attached the logs.

[rtmpAudioTsLogs.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7934918/rtmpAudioTsLogs.txt)
[rtmpVideoTsLogs.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7934919/rtmpVideoTsLogs.txt)

Also, when I increased the accuracy of the timeStamp calculation, the DTS errors disappeared. But most likely this is not a rational move at all. I think the application will crash when the values reach the limit of the Long type. 
I did the following:
`commandsManager.startTs = System.nanoTime()`
`flvPacket.timeStamp = System.nanoTime()  - startTs`

I think you can find a much better solution. Thanks for the quick response!

**Comment by pedroSG94** [comment]
Srs server is working for me with or without forceAkamaiTs(true).
Could be that it is wokring but you receive that logs checking a file? Can you tell me how to get that logs?
version: XCORE-SRS/4.0.156(Leo) using docker

Your solution use timestamp as nanoseconds but the correct way is use timestamp as milliseconds (I'm doing it).

The problem using forceAkamaiTs(true) is that both frames are send in the same millisecond so using akamaiTs you send it with the same value.

For now, I will add a way to calculate audio timestamp based on the audio packet size and report you back to test it but I need the way to get that dts logs in srs server.

**Comment by BakhromMuydinov** [comment]
The errors I indicated are observed in the ffmpeg logs.
You can view them like this:

> for Linux: ffmpeg -loglevel debug -i rtmp://x.x.x.x:1935/xxx -c copy -f null /dev/null
for Windows: ffmpeg -loglevel debug -i rtmp://x.x.x.x:1935/xxx -c copy -f mp4 NUL

**Comment by pedroSG94** [comment]
Using App example (OpenGl example) without modify a line I haven't that problem (without forceAkamaiTs(true)):
```
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
    Last message repeated 1 times
[rtmp @ 0x55ccf34d61c0] Sending bytes read report.40 bitrate=N/A speed=1.28x    
[rtmp @ 0x55ccf34d61c0] Sending bytes read report.09 bitrate=N/A speed=1.12x    
[rtmp @ 0x55ccf34d61c0] Sending bytes read report.83 bitrate=N/A speed=1.08x    
[rtmp @ 0x55ccf34d61c0] Sending bytes read report.69 bitrate=N/A speed=1.06x
```
I only have this problem using forceAkamaiTs(true).
```
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
cur_dts is invalid st:1 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
    Last message repeated 2 times
[null @ 0x560e57abe600] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 186 >= 186
[null @ 0x560e57abe600] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1152 >= 1152
[null @ 0x560e57abe600] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1153 >= 1153
[null @ 0x560e57abe600] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1473 >= 1473
[null @ 0x560e57abe600] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1783 >= 1783
    Last message repeated 1 times
[null @ 0x560e57abe600] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1938 >= 1938
```
Both cases using Srs server
I recommend you don't use it because it is not necessary in Srs server. Anyway, I will find a way to avoid this problem using akamaiTs.

**Comment by BakhromMuydinov** [comment]
Okay Pedro,
Thanks for the advice!
