### ISSUE TITLE
Need to rotate stream without rotating preview.

### ISSUE THREAD

**Issue by fakeivchenko** [pedroSG94/RootEncoder#1045]
I need to rotate the stream without preview rotation in order to support both portrait and landscape modes. It looks like it can't be implemented right now. I'm using OpenGLView.

**Comment by pedroSG94** [comment]
Hello,

It is not implemented. I have little time this weeks but I will developed it the next feature, but for now, I'm trying to fix other problems.

**Comment by pedroSG94** [comment]
Use rotation example
Closing as inactive.
