### ISSUE TITLE
How to support Android 5.1.1?

### ISSUE THREAD

**Issue by roybill** [pedroSG94/RootEncoder#1056]

**Comment by pedroSG94** [comment]
This library support API 16+ (Android 4.1). I don't understand your question

**Comment by roybill** [comment]
> This library support API 16+ (Android 4.1). I don't understand your question

I ran it on x86 5.1.1, but it didn't work.

**Comment by pedroSG94** [comment]
You need to specify more.

- Can you tell me device model used? If you are using emulator, which image and configuration is used exactly?
- Which example did you test using my app example? 
- Can you tell me the fail produced and how to reproduce it?

**Comment by roybill** [comment]
1.I'm running on an emulator for Pixel 2,x86;
2.I use it like this:  
   <SurfaceView
        android:id="@+id/surfaceView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

 SurfaceView surfaceView = findViewById(R.id.surfaceView);
        RtmpCamera1 rtmpCamera1 = new RtmpCamera1(surfaceView, new MyConnectCheckerRtmp());

        Button buttonStart = findViewById(R.id.b_start);
        buttonStart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                    Toast.makeText(AcivityA.this, "开始推流", Toast.LENGTH_SHORT).show();
                    rtmpCamera1.startStream(url);
                    LogUtils.d("1527   11111111111");
                } else {
                    /**This device cant init encoders, this could be for 2 reasons: The encoder selected doesnt support any configuration setted or your device hasnt a H264 or AAC encoder (in this case you can see log error valid encoder not found)*/
                    LogUtils.d("1527   222222222222");
                }
            }
        });

3.When I execute the code:                rtmpCamera1.startStream(url);
  The simulator is stuck,There were no errors.

**Comment by pedroSG94** [comment]
Hello,

I tested using Pixel2 API 22 x86(goople api) emulator from Android studio and it is working so this seems a code error in your side. 
Can you test using Default RTMP example? If you have any problem share me a logcat.

**Comment by roybill** [comment]
@pedroSG94   ok, thank you!
