### ISSUE TITLE
When I set the orientation, the interface will stretch and the pull flow will appear blurred. How to solve this problem?

### ISSUE THREAD

**Issue by roybill** [pedroSG94/RootEncoder#1060]
I use the computer version of VLC playback also blurry.

1. push:
buttonStart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                    Toast.makeText(AcivityA.this, "开始推流", Toast.LENGTH_SHORT).show();
                    rtmpCamera1.startStream(rtmpUrl);
                    rtmpCamera1.setPreviewOrientation(0);     //摄像头左转
                } else {
                    /**This device cant init encoders, this could be for 2 reasons: The encoder selected doesnt support any configuration setted or your device hasnt a H264 or AAC encoder (in this case you can see log error valid encoder not found)*/
                }
            }
        });
2.pull:         https://github.com/Jzvd/JZVideo
    @Override
    protected void onCreate(@Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_yierlinger);
        mJzVideo = findViewById(R.id.jz_video);
        mJzVideo.setUp(rtmpUrl, "title",JzvdStd.SCREEN_NORMAL,JZMediaIjk.class);
        mJzVideo.backButton.setImageResource(R.mipmap.back_white);
        mJzVideo.posterImageView.setImageResource(R.mipmap.temp_banner);//封面图
        mJzVideo.startVideo();
    }

**Comment by pedroSG94** [comment]
Closing as inactive.
