### ISSUE TITLE
Capture only microphone audio.

### ISSUE THREAD

**Issue by GauravSTripathi** [pedroSG94/RootEncoder#1061]
Hello Pedro.
We need to capture only microphone data In Display Stream.
For that we have changed the audio source from DEFAULT to MIC.
But Still we are getting the Device internal audio.

**Comment by pedroSG94** [comment]
Hello,

You are not getting internal audio, you are getting audio from speakers. Try to test it using low audio and you will check that it is the case.
You can try use echoCanceller enabled of prepareAudio method but if it isn't working for you. I haven't other way to do it. This is the recommend way in few posts but it doesn't work in all cases:
https://stackoverflow.com/questions/53025219/audiorecord-while-also-playing-audio-accessing-output-playback-data
