### ISSUE TITLE
 Rendering filter view file  gif is  Invalid item show multiple  (Background "chromaFilterRender " , Beauty)  incomplete

### ISSUE THREAD

**Issue by PongPloy2016** [pedroSG94/RootEncoder#1066]
Why  Rendering filter view gif is  not show multiple  incomplete 

Case 1 
If 1 Filter gif is displayed, the screen can be used normally, but if use more than 1 Filter gif, there will be a problem of overlaying duplicate images using the command.

rtmpCamera1!!.glInterface.addFilter(gifObjectFilterRender)

by example 

picutre
![Screenshot_20220302-011905_ar_live_ais](https://user-images.githubusercontent.com/8625469/156228981-72e13ae1-66d3-4b08-809e-791fd72c55ec.jpg)

video link :  https://drive.google.com/file/d/1COc7O_vs5Tt2skJHY2a9PT6GnUr2L9_O/view?usp=sharing
code

`   charItem.urlImage?.let {
               // val gifURL = URL("https://admin-stg.authority.wittytech.live/live_asset_imgs/file_gif_8AC41ZAPY91ZWAHRYMNU_1646016031.gif")
                val gifURL = URL(it)
                val connection: HttpURLConnection = gifURL.openConnection() as HttpURLConnection
              //  var mInputStream = connection.inputStream
                val result: Deferred<InputStream?> = GlobalScope.async {
                    connection.inputStream
                }
                GlobalScope.launch(Dispatchers.Main) {
                    val gifObjectFilterRender = GifObjectFilterRender()
                    gifObjectFilterRender.setGif(  result.await())
                  //  gifObjectFilterRender.setGif(resources.openRawResource(R.raw.fig_demo))
                    rtmpCamera1!!.glInterface.setFilter(gifObjectFilterRender)
                    gifObjectFilterRender.setDefaultScale(
                        rtmpCamera1!!.streamWidth,
                        rtmpCamera1!!.streamHeight
                    )
                    gifObjectFilterRender.setPosition(TranslateTo.BOTTOM)
                   spriteGestureController.setBaseObjectFilterRender(gifObjectFilterRender) //Optiona
                    rtmpCamera1!!.glInterface.addFilter(gifObjectFilterRender) //---> i am it multiple gif 
             
                
                }

            }`

********************************

Case 2.  Gif. -> Background. : gif is not up but Background. is up 

WhenFilterRender #gif singer one and using filter #chromaFilterRender the result shows that the gif is not showing but chromaFilter does, as an example.  

video : https://drive.google.com/file/d/1CgjMaKbzMOWALNSv29v8WPn3wWaiU1_6/view?usp=sharing

example 

code 👍 

`   GlobalScope.launch(Dispatchers.Main) {
                    chromaFilterRender.setImage( result.await() )
                    rtmpCamera1!!.glInterface.setFilter(chromaFilterRender)
                  
                }`

**************************

Case 3  Gif. -> beauty. : Gif can't go up. But beauty can go up. 

When FilterRender #gif singer one and using filter #BeautyFilterRender the result shows that the gif is not showing but chromaFilter does, as an example.  

src 👍 

video :  https://drive.google.com/file/d/1CmBelO9k1Sh67NmRE9fRe__Z1xelLwFb/view?usp=sharing

example 

code 👍 

`   GlobalScope.launch(Dispatchers.Main) {
                    rtmpCamera1!!.glInterface.setFilter(BeautyFilterRender())
                    liveFilterRenderList.add(BeautyFilterRender())
                  
                }`

thank you. please help !!!!

**Comment by pedroSG94** [comment]
I will investigate case 1 but case 2 and 3 is related with your code.
You are doing a replace instead of add a filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/GlInterface.java#L120

You should use addFilter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/GlInterface.java#L80

The usage is similar to an ArrayList

**Comment by pedroSG94** [comment]
I'm testing using my gif:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/raw/banana.gif
But I can't reproduce your case. I need the gif to reproduce your case. Also, if you can write me the way you download the gif to implement it in my app example and test it.

**Comment by PongPloy2016** [comment]
> I'm testing using my gif: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/raw/banana.gif But I can't reproduce your case. I need the gif to reproduce your case. Also, if you can write me the way you download the gif to implement it in my app example and test it (I haven't the url).
> 
> Also, to discard device or gif problems you can compile my app example and using OpenGl RTMP/RTSP add test using gif filter from menu.


Sorry, I may not be explaining the problem clearly enough.
i would like add more gifs over 1 gif on screen but when call second gif filter on screen or more then so i will encounter gif display bug like this picture. Could you please recommend me? What can I do if I want to add more than one gif filter to display on screen? 
I used call function  “rtmpCamera1!!.glInterface.addFilter(gifObjectFilterRender)” to call multiple gifs on srceen

Could you please recommend me? What can I do if I want to add more than one gif filter to display on screen?

<img width="833" alt="Screen Shot 2565-03-04 at 00 59 56" src="https://user-images.githubusercontent.com/8625469/156624148-7339b17a-895b-460f-8697-5c4860c2c420.png">

**Comment by pedroSG94** [comment]
Ok I could reproduce your case but it is not an error in the library.
You are adding 2 times the same filter but you can't do it because each filter must be added only 1 time to the stream (it use texture references to work so you can't do it).
The correct way to use it is create a new GifObjectFilterRender for each gif added to stream. Also, rememeber that, after add a gif you need get InputStream again to create the new one. It is the same for Image filter.
