### ISSUE TITLE
can we play music along with rtmp streaming?

### ISSUE THREAD

**Issue by hemant-novotrax** [pedroSG94/RootEncoder#1071]

**Comment by pedroSG94** [comment]
I'm not sure what do you means but if you use the microphone. Microphone can take skeapers sound.
Other way you can take internal audio that will get all audio produced by your device.

**Comment by hemant-novotrax** [comment]
Hello

Thank you for reply .
I mean can we play raw file from assets folder along with rtmp streaming?

**Comment by pedroSG94** [comment]
Hello,

You can stream a file using fromfilebase. You have the example here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/filestreamexample

You can try get you assest file path using this method:
https://stackoverflow.com/a/56455963
If it isn't working you can copy file to a folder and use it.
