### ISSUE TITLE
Gradle enterprise problems

### ISSUE THREAD

**Issue by thhart** [pedroSG94/RootEncoder#1072]
Only a short hint, I checked the library for some tests in Intellij Idea and got some problems while Gradle enterprise was used for some kind of signing, I am not into it, but I resolved the problems by this:

**I had to modify build.gradle files:**

<pre>
android {
  compileSdkVersion 32

  defaultConfig {
    minSdkVersion 16
    targetSdkVersion 31
  }
  buildTypes {
    release {
      minifyEnabled false
    }
  }

  publishing {
    singleVariant("release")
  }
}
</pre>

**to this:**

<pre>
android {
  compileSdkVersion 32

//  defaultConfig {
//    minSdkVersion 16
//    targetSdkVersion 31
//  }
//  buildTypes {
//    release {
//      minifyEnabled false
//    }
//  }
//
//  publishing {
//    singleVariant("release")
//  }
}
</pre>

**Comment by pedroSG94** [comment]
Hello,

I'm not sure about your problem without a trace error but normally you don't need comment defaultConfig and buildTypes. Remove publishing should be fine to compile it normally.

Anyway if you compile it using gradle line on README instead of import it manually you don't need do it.
