### ISSUE TITLE
Using older Gradle Version

### ISSUE THREAD

**Issue by ggpaeg** [pedroSG94/RootEncoder#1076]
Hi, @pedroSG94!

I'm using your library on a project that needs older Gradle configuration.
I need to use these parameters in order to keep compatibility.

ext.kotlin_version = '1.4.10'
classpath 'com.android.tools.build:gradle:3.3.0'

distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-bin.zip

When I tried to import this library in my project, I got the following error. 

Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

I need to use older library version?

**Comment by pedroSG94** [comment]
Hello,

You have 2 options:
- Update kotlin version
- Compile library manually with kotlin version 1.4.0 (you can create a fork and upload the project to jitpack if you want)

**Comment by AlexUrrutia** [comment]
Pedro, I'm getting this error:

`jetified-rtplibrary-2.2.4/jars/classes.jar!/META-INF/rtplibrary_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

What can I do?

**Comment by pedroSG94** [comment]
Closing as inactive.
