### ISSUE TITLE
Screen black issue

### ISSUE THREAD

**Issue by Malikfarooq** [pedroSG94/RootEncoder#1079]
I am working in RTMP streaming and facing issue while app goes in background. OpenGlView surface holder is showing black  screen on 
 app resuming .

**Comment by pedroSG94** [comment]
Hello,

If you are doing streaming while app is in background you should check background example.
If you go to background your OpenGlView is destroyed and you need to change it in surfaceHolder callback like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt#L54
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt#L59
