### ISSUE TITLE
Camera2 Resolutions

### ISSUE THREAD

**Issue by ali-safdarii** [pedroSG94/RootEncoder#1082]
Hello pedro
how can i get only supported devices Resolutions with camera2 api?  with **rtmpCamera1**.resolutionsBack i get only supported devices Resolutions , but with **rtmpCamera2**.resolutionsBack i get all screen size Resolutions , how can i get same result with camera 2? sorry for bad english :)

**Comment by pedroSG94** [comment]
Hello,

rtmpCamera2.resolutionsBack provide supported device resolutions. The difference is that camera2 can accept any resolution between the smaller and the higher resolution in that list if you have a proper implementation of camera2 in the device (it is cropping using the closest resolution).
To know if you have a proper implementation of camera2 in your device you have this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L273
Documentation:
https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics#INFO_SUPPORTED_HARDWARE_LEVEL
This isn't exposed in Camera2Base, but you can add it if you want. Anyway, my recommendation is use always a resolution provided by that list to avoid problems.

**Comment by ali-safdarii** [comment]
thank you so much
