### ISSUE TITLE
RTMPT and pass through constrained networks

### ISSUE THREAD

**Issue by benjaminVadon** [pedroSG94/RootEncoder#1083]
Hello,
I'm facing problems using your great library behind on a not fully open network to internet (such as a hotel or a company network) on which I can't manage opening ports nor letting rtmp protocol be used. Had you ever been faced to this kind of usage from your users ?

To solve this issue, one way is using rtmpt, an encapsulation of rtmp through http, which as drawback on latency but having advantage of not being blocked. Did you ever test for this protocol or any advice if I want to implement such a layer in your library ?

PS: using only port 80 is not an option for all cases because some firewall blocks rtmp protocol

**Comment by pedroSG94** [comment]
This is a good feature but I haven't a server to test it.
Do you know any free server that support rtmpt?

**Comment by benjaminVadon** [comment]
My backend co-worker is working in building such a server in order to test it on iOS part.
He agrees to open it to you when it's done fully functional, so you'll be able to do your test when you want. I'll ping you here when it's done and we can explain you how to use it in direct message (not so complicated but need a special version of our product)

**Comment by benjaminVadon** [comment]
Hello @pedroSG94  ,
my coworker has finished his rtmpts service (rtmpts stands for rtmp tunnel through https, instead of http) and I've modified our android app so you can generate your own rtmpts server on demand.
I will share it to you by firebase app distribution. Can I use your gmail adress of your github account ? 
Once installed, I think it's better if I give you a vocal onboarding (on discord or meet maybe) so you can easily create your test server and see your content.

**Comment by pedroSG94** [comment]
Hello,

You can use my gmail address to share it.
For now, share me a documentation to install server and a ffmpeg command to test it. I will tell you if I have any question.
Also, if you can, provide me a way to use with http to develop rtmpt at the same time
ffmpeg is totally required. I need a valid way to know that it is working before start develop

This change look a big change so don't expect it in 1 or 2 weeks. I'm developing this project in my free time so it depend of it.

**Comment by benjaminVadon** [comment]
Ok, my coworker will add rtmpt server soon and I'll send you a mail when it's ready to use, and with a ffmpeg to command to connect to it. You still need the android app to generate an on demand server. In the mail, I will explain as simple as possible how to do it.
I understand it could take time to do it, and I'm pushing in my company to sponsor you for your work, and they are open for it. 
PS: you should have received an firebase invitation to download the app.

**Comment by pedroSG94** [comment]
Hello,

I received both emails. I will start it as soon as I can.
I will notify you by email any doubts.
