### ISSUE TITLE
Autofocus Issue

### ISSUE THREAD

**Issue by nirmala-ncompass** [pedroSG94/RootEncoder#1094]
Step 1: We disabled the autofocus.
Step 2: We enabled it again. But the auto focus is not working. 
Also,
    Tap to focus is not consistent.

**Comment by pedroSG94** [comment]
Camera1, Camera2?
Are you calling it with preview/stream/record started? If not, it is ignored.

What do you mean with consistent? not working sometimes times?

**Comment by nirmala-ncompass** [comment]
1. We are using camera2.
2. We are using button for toggling the autofocus(enable/disable). preview state and run time streaming state.
3. Sometimes it's not working. This will happen when the auto focus is disabled but the user taps to focus.

**Comment by nirmala-ncompass** [comment]
Hi @pedroSG94, Any update on this? Could you able to recreate this?

**Comment by pedroSG94** [comment]
Hello,

I was doing tests but I'm not able to reproduce your case as you described.
I found a bug that if you are using tap to focus, enableAutoFocus stop to work in camera2, and I fixed it. Call enable and disable autofocus multiple times without use tap to focus was working fine. 
Commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/432d69c5f613ddb2754d82919292a8aec8c468b1

I tested in 2 devices with the same result.
To know if enable/disable autofocus was success you can call:
```java
rtmpCameraw.isAutoFocusEnabled();
```
If not success this means that something happens and normally it is that you called it without camera started

**Comment by nirmala-ncompass** [comment]
Thanks @pedroSG94 This fix is working. But when we disable the auto focus, screen gets blurred. Is there any possibilities to fix this issue?

**Comment by pedroSG94** [comment]
It isn't an issie. Disable autofocus is set focus to infinity, so it is working as expected.
