### ISSUE TITLE
RTMP Cumulative delay

### ISSUE THREAD

**Issue by lijiaqq** [pedroSG94/RootEncoder#1096]
RTMP Push flow has Cumulative delay。How to optimization it?

**Comment by pedroSG94** [comment]
Hello,

I haven't acumulative delay. Delay is normally in server or player side.
You have tests here to check it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1064
This test use RTSP but to test RTMP is exactly the same
