### ISSUE TITLE
OpenGL rotation to Portrait stretches and scales stream

### ISSUE THREAD

**Issue by isouriadakis** [pedroSG94/RootEncoder#1098]
I am using the repo as a library for a flutter project. If I rotate with OpenGL to stream as Portrait instead of landscape, the streamed image doesn’t match the preview. The received video is cropped and streched. I have ensure that the resolution of the preview and stream is the same as the native resolution. I am using a Galaxy tab A8.

Does anyone knows how to fix this issue?

**Comment by pedroSG94** [comment]
Hello,

I'm not sure what do you mean but using keepAspectRatio in xml like here should fit screen without deform image using black borders or cropping depend if you use adjust or fill aspectRatioMode. You have examples in the demo app:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12

If you only have problems using flutter. I never tested using flutter so I'm not sure about it.
