### ISSUE TITLE
How to support android lifecycle when streaming?

### ISSUE THREAD

**Issue by haiyiya** [pedroSG94/RootEncoder#1103]
Thanks for your great library!!! I have some difficulties. When I am streaming, I switch to another app and then switch back, and the streaming is stopped. I want to continue streaming when app resumed, Could I do something in onPause and onResume? sorry for my poor english.

**Comment by uditshoprtv** [comment]
Hey,

I have tried BackgroundActivity and it's working fine for me.

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample
