### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by lijiaqq** [pedroSG94/RootEncoder#1105]
when I pushing ，I just want send video‘s  voice   prohibit Microphone。just like appAudio and MicAudio     I don't know. Do you understand what I mean

**Comment by pedroSG94** [comment]
I'm not sure what you means but:
- If you want stream a video (Audio and Video) you can use RtmpFromFile or RtspFromFile.
- If you want stream internal Audio (audio produced by speakers) you can do it using DisplayBase and prepareInternalAudio method.
- If you want stream Microphone audio without audio reproduced by speakers. It is not possible but, maybe you can reduce a bit the sound get from speakers using echo and noise features from prepareAudio method.
