### ISSUE TITLE
close fail

### ISSUE THREAD

**Issue by lijiaqq** [pedroSG94/RootEncoder#1112]
when i called displayBase.stopStream(),I have received calback onDisconnectRtp. But theserver display is still connected。

 Is there a return value from server when i called stopStream

**Comment by pedroSG94** [comment]
What do you means qith server display?
- You are still sending packet?
Are you sure that you are already sending video packet? you can check it in logcat

**Comment by lijiaqq** [comment]
I  am sorry my English is not good. I means when i stopStream the connection can still be find in server but client shows disconnect success.

**Comment by pedroSG94** [comment]
Check in logcat:
- Rtmp: send close command
- Rtsp: send teardown command

If you can find it. It is correctly disconnected and you should check the reason in server side. Maybe server need few seconds to update ui
