### ISSUE TITLE
 Stream from microphone(Rtsp) is available but no any audio when play it?

### ISSUE THREAD

**Issue by tienthanhdo98** [pedroSG94/RootEncoder#1117]
Hi.
I used RtspOnlyAudio in my project and i have problem. Some time, stream is available  no any audio. 
How do I fix that error? Or you can tell me reason this bug is occur?
please suggess me
Thank you

**Comment by pedroSG94** [comment]
I don't undertand the question. Can you see audio packets in logcat?
If you can see that. The library send correctly packets to server and you should check the problem in server side.
