### ISSUE TITLE
I have got one issue while live streaming in portrait camera orientation

### ISSUE THREAD

**Issue by vcsvetronind** [pedroSG94/RootEncoder#1118]
Hi pedroSG94,
I am using your library for live streaming. I am testing on the 4G HD Law enforcement recorder for which I have uploaded a screenshot. I am trying to stream in portrait resolution which is 352 x 288. But the issue I am facing is that when I am streaming in portrait but it changes to the landscape. Could you help me with this issue ? 

![1653297334147](https://user-images.githubusercontent.com/91876003/169786682-5bd052fa-4d1c-4999-b9dc-f016421b2a6a.JPEG)
![1653297319695](https://user-images.githubusercontent.com/91876003/169786701-86f9747c-65ee-45d6-a942-998fe373cbcb.JPEG)
![1653297330077](https://user-images.githubusercontent.com/91876003/169786723-84da01b2-9bc1-40c8-8ec6-c9a57ed8ccc2.JPEG)

**Comment by pedroSG94** [comment]
I don't understand the problem. Can you explain it better?
Where is the problem exactly when you change to landscape? Can you explain desired behavior?

**Comment by vcsvetronind** [comment]
Can you please see below attachment link show (Preview video)

https://www.youtube.com/shorts/OU1cufH664o
*Thanks and regard *
*Nitul Patel*

**Comment by BlueBazze** [comment]
Actually. How the f did you manage to get the video to rotate when you rotated the device like that?

**Comment by vcsvetronind** [comment]
> Actually. How the f did you manage to get the video to rotate when you rotated the device like that?

That is the issue which I am facing!

**Comment by pedroSG94** [comment]
Ok, I understand now.

Do you have prepareVideo method with rotation value setted correctly? The correct value should be like this:

```java
prepareVideo(width, height, fps, bitrate, CameraHelper.getCameraOrientation(context);
```

If you have this method corerctly configured lest try other ways:
- Use OpenGView as preview and set RotationFilter:
```java
        RotationFilterRender rotationFilterRender = new RotationFilterRender();
        rtmpCamera1.getGlInterface().setFilter(rotationFilterRender);
        rotationFilterRender.setRotation(90);
```
- If you are using Camera1 you can try with this method:
```java
rtmpCamera1.setPreviewOrientation(90);
``` 
- Use OpenGView as preview and set rotation to OpenGlView:
```java
//rotate preview and stream/record
rtmpCamera1.getGlInterface().setRotation(90);
//rotate only stream/record result
rtmpCamera1.getGlInterface().setStreamRotation(90);
```
