### ISSUE TITLE
Text or layout is not show properly with Rtmp streaming

### ISSUE THREAD

**Issue by HemantBhartiGoswami** [pedroSG94/RootEncoder#1123]
Hello 
When I used Custom Text or layout ,it text stretch and color does not show proferly .
![InkedScreenshot_2022-05-25-17-15-09-13_37e661718c7513d7915c2f345cc7025d_LI](https://user-images.githubusercontent.com/17778282/170254775-a7e1ee5d-ffe4-496f-a57b-3f64258f4b16.jpg)

**Comment by pedroSG94** [comment]
If you means for resolution. You have setSize method to fix it
If you means for quality. It is related with stream/preview resolution, try to increase resolution and you will get a better quality.
