### ISSUE TITLE
Will there be plans to support WebRTC live streaming in the future?

### ISSUE THREAD

**Issue by sheng930920** [pedroSG94/RootEncoder#1131]
Will there be plans to support WebRTC live streaming in the future?

**Comment by pedroSG94** [comment]
Hello,

I haven't plan to do it because WebRTC is not used for the same cases that RTMP or RTSP.
WebRTC is used for communication in both directions instead of this project that use protocols to stream in only one direction.

Other possible compatible protocols could be SRT or HLS
