### ISSUE TITLE
why the “presentTimeUs” in BaseEncoder is static?

### ISSUE THREAD

**Issue by xumingxin7398** [pedroSG94/RootEncoder#1138]
I have 3-5 encoders implements the baseEncoder , for streaming and recording in different size. But I found the “presentTimeUs” is static so they will use the same value to calculate their times. In some case when the device was performance slowly, may cause timestamp problem(I think). Can I remove the static, can I get your advice?

**Comment by pedroSG94** [comment]
You can remove it. The idea about that static is use the same presentTimeUs for both encoders (audio and video) to avoid sync issues if you have a device that take time to start both encoders.
In most of devices it isn't a problem.
