### ISSUE TITLE
Select mic using prepareAudio

### ISSUE THREAD

**Issue by invalidtask** [pedroSG94/RootEncoder#1139]
I'm trying to select mic using prepareAudio but the only result that happens is a sped up sounding voice on playback. I'm using AudioDeviceInfo to get the device id of the microphone and passing that value to the prepareAudio method. Is this not the correct usage? If not, how do I select a different microphone?

**Comment by pedroSG94** [comment]
Hello,

If you means parameter "int audioSource".
This parameter support this values: 
https://developer.android.com/reference/android/media/MediaRecorder.AudioSource

In most of cases using MediaRecorder.AudioSource.MIC or MediaRecorder.AudioSource.VOICE_COMMUNICATION is enough but if you are using bluetooth microphone enable it using SCO could be necessary:
https://developer.android.com/reference/android/media/AudioManager
