### ISSUE TITLE
Question about MediaExtractor seekto.

### ISSUE THREAD

**Issue by stormxz** [pedroSG94/RootEncoder#1142]
Hi Pedro,
First, thank you for your project.
But，i have a issue when use RtspFromFile.

  public void onStopTrackingTouch(SeekBar seekBar) {
    if (rtspFromFile.isStreaming()) rtspFromFile.moveTo(seekBar.getProgress());
    touching = false;
  }
  
When I slide the progress bar backwards（seek bar to left）, the video will stoped，but audio is ok.
And i see this log：
 W GraphicBufferSource: Dropping frame that's going backward in time
 
 Does encoder code which in your project not support video going backward function? 
 
 ps: When I fast forward this video( seek bar to right ), video and audio are ok.

**Comment by pedroSG94** [comment]
Hello,

I'm already working on it. 
I will check moveTo method but seekTo method of MediaExtractor is not working really good so I'm not sure if I can fix it totally.
Do you have problems only if you go back?
I will try report you in the next days. For now, check this:
- When video is stopped check if you still have video packets in the logcat to discard that Decoder or Encoder stopped.
- Try to use moveTo method manually instead of use seekbar and wait few second in each call to avoid multiple calls.

**Comment by stormxz** [comment]
Thanks for your reply.
Do you have problems only if you go back? 
- Yes.

When video is stopped check if you still have video packets in the logcat to discard that Decoder or Encoder stopped.
- I use this method on Qualcomm and MTK platforms，I saw the platform actively discard the go backward video frames.

13:57:48.298   782  7390 W GraphicBufferSource: Dropping frame that's going backward in time
13:57:48.301   782 12590 E MtkOmxVdecExV4L2: [0xee43ed40] PrepareAvaliableColorConvertBuffer, no free buffer can't queue to CCDst
13:57:48.310   782 12590 E MtkOmxVdecExV4L2: [0xee43ed40] ConvertFrame create job: 68150, fence: 378, LINE: 9556
13:57:48.311   782 12590 D MDP     : [PQ][PQDREAdaptor(0)] getDefaultDREVPOutput, use the previous output curve stored in Ashmem
13:57:48.312   782 12590 E MtkOmxVdecExV4L2: [0xee43ed40] PrepareAvaliableColorConvertBuffer, no free buffer can't queue to CCDst
13:57:48.319   529   529 I hwcomposer: [HWC] (0) displaySetActiveConfig config:0 
13:57:48.332   782  7390 W GraphicBufferSource: Dropping frame that's going backward in time

Try to use moveTo method manually instead of use seekbar and wait few second in each call to avoid multiple calls.
- ok，I will try this.

**Comment by pedroSG94** [comment]
Hello,

I did a commit to fix this problem: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c9290c668aae690ac2f5c13d87ec574e721fab2d
Test it and let me know if it is working for you.

**Comment by stormxz** [comment]
08-11 02:44:11.443 28898 28978 E AndroidRuntime: FATAL EXCEPTION: VideoDecoder
08-11 02:44:11.443 28898 28978 E AndroidRuntime: Process: com.pedro.sample, PID: 28898
08-11 02:44:11.443 28898 28978 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=8; index=19
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at com.pedro.encoder.input.decoder.BaseDecoder.decode(BaseDecoder.java:249)
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at com.pedro.encoder.input.decoder.BaseDecoder.lambda$start$0$BaseDecoder(BaseDecoder.java:111)
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at com.pedro.encoder.input.decoder.-$$Lambda$BaseDecoder$txnbwu7_ugba9BVkhA3zIrIUd0E.run(Unknown Source:2)
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:229)
08-11 02:44:11.443 28898 28978 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by stormxz** [comment]
when i use new code, application is crash.
ps: i use OpenGlView

**Comment by pedroSG94** [comment]
Hello,
Can you share me file used to reproduce the problem?
