### ISSUE TITLE
'com.pedro.rtpstreamer' has stopped error

### ISSUE THREAD

**Issue by karthikstar** [pedroSG94/RootEncoder#1147]
Hi there, currently I am working on using your code to create a rtsp stream client to be run in a robot with camera equipped. However, while I am able to open the app in the robot, whenever i press Custom RTSP button to do the streaming of camera feed to rtsp URL, the app crashes, with a error message saying that com.pedro.rtpstreamer has stopped. What can i do in this case? Would like your input on that issue, thank you!

**Comment by pedroSG94** [comment]
I can't help you like this. I need:
- logcat error
- If you modified the code I will need code related to the crash
