### ISSUE TITLE
replaceView function issue

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/RootEncoder#1151]
When I call replaceView function from RtmpFromFile with OpenGL or Context as the parameter, I got illegalStateException. I downgrade the version to 2.0.0 and the problem has been solved. But The versions after 2.0.0 faced this issue.

**Comment by pedroSG94** [comment]
So, version 2.0.1 and above produce this problem, right?

**Comment by MohammadRezaei92** [comment]
> So, version 2.0.1 and above produce this problem, right?

Yes

**Comment by pedroSG94** [comment]
I did changes to that method in a recent commit above 2.1.9 that should solve this problem. Try to compile last commit using this gradle:
```gradle
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:54790ce5f8'
```
Let me know if the problem persist. This also should fix loop mode and moveTo method

**Comment by MohammadRezaei92** [comment]
> I did changes to that method in a recent commit above 2.1.9 that should solve this problem. Try to compile last commit using this gradle:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:54790ce5f8'
> ```
> 
> Let me know if the problem persist. This also should fix loop mode and moveTo method

The issue has not fixed yet.
`java.lang.IllegalStateException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2042)
        at com.pedro.encoder.input.decoder.VideoDecoder.changeOutputSurface(VideoDecoder.java:80)
        at com.pedro.rtplibrary.base.FromFileBase.prepareGlView(FromFileBase.java:348)
        at com.pedro.rtplibrary.base.FromFileBase.replaceGlInterface(FromFileBase.java:328)
        at com.pedro.rtplibrary.base.FromFileBase.replaceView(FromFileBase.java:306)`

**Comment by pedroSG94** [comment]
Hello,

I did a commit for it: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/1e9f0636fde4444522dfc2e37a513bc45d2e97ae
```gradle
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1e9f0636fd'
```
Let me know if it is working for you

**Comment by MohammadRezaei92** [comment]
> Hello,
> 
> I did a commit for it: [1e9f063](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/1e9f0636fde4444522dfc2e37a513bc45d2e97ae)
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1e9f0636fd'
> ```
> 
> Let me know if it is working for you

Still have the problem. Besides that, my video has no voice when it played.

**Comment by pedroSG94** [comment]
Are you sure? 
I can't reproduce the error after that commit using 3 different devices.
Can you test using default app? I did this changes to test:
- Go to RtmpFromFileActivity:
    - add context to RtmpFromFile
    - replace case R.id.b_re_sync code to:
    ```java
            if (rtmpFromFile.getGlInterface() instanceof OffScreenGlThread) {
          OpenGlView openGlView = findViewById(R.id.surfaceView);
          rtmpFromFile.replaceView(openGlView);
        } else {
          rtmpFromFile.replaceView(this);
        }
    ```
- Go to activity_from_file layout:
    - In line 8 add:
    ```xml
      <com.pedro.rtplibrary.view.OpenGlView
      android:id="@+id/surfaceView"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>
    ```
Now, compile app and using From file RTMP use resync file button to change from context to openglview on fly.
If possible use more than one device to discard device specific issue.

**Comment by pedroSG94** [comment]
Closing as inactive.
