### ISSUE TITLE
Switch between streams with different SPS, PPS.

### ISSUE THREAD

**Issue by anilmaddala** [pedroSG94/RootEncoder#1162]
I am trying to switch between streams which have differnet SPS, PPS.

I am seeing Grey Video feed on the receiving viewer client. The newer stream works as expected if I teardown and restart the RTSP connection.

Is there a way to switch between streams (with different SPS,PPS) without resetting the connection?

**Comment by pedroSG94** [comment]
Hello,

No,
RTSP and RTMP need specify SPS and PPS in connection so it is inmutable because player need to know how to decode it.
Normally you should do it in server side and connect player to desired endpoint. This is possible in few servers like wowza or srs server
