### ISSUE TITLE
Adaptive bitrate reduced when streaming Image Object Filter

### ISSUE THREAD

**Issue by nirmala-ncompass** [pedroSG94/RootEncoder#1164]
When Image Object filter is rendered,adaptive bitrate is reduced from higher bitrate (1080) to lower bitrate (360). It is not restoring to higher bitrate even when I get sufficient bandwidth. But when Image Object filter is removed, it is getting restored. 
1. Do you have any reason for this? 
2. How can we resolve this?

**Comment by pedroSG94** [comment]
What do you mean with 1080 bitrate and 360 bitrate?
Did you test with multiple devices to discard device problem?
If you don't use bitrate adapter. All is working fine?

**Comment by nirmala-ncompass** [comment]
Before Image Object render, we are getting 4.5 * 1000000 bitrate (4.5MB) from bitrate adapter. When I started streaming image object, bitrate is reduced  to 1 * 1000000 (1MB) from adapter.

**Comment by pedroSG94** [comment]
Ok,
Did you tried this?:


> Did you test with multiple devices to discard device problem?
> If you don't use bitrate adapter. Is all working fine?

Did you created a new bitrate adapter class to test and get more info about the case?

**Comment by nirmala-ncompass** [comment]
It is behaving the same when we didn't use bitrate adapter and also in multiple devices.

**Comment by pedroSG94** [comment]
Hello, Sorry for late response.

This is really weird. Can you share me your stream configuration (video and audio parameters) and image filter configuration (image, size, etc) to reproduce the problem?

**Comment by nirmala-ncompass** [comment]
**Video & Audio Configuration:**
 rtmpCamera2.prepareVideo(1920, 1080, 4608000);
rtmpCamera2.prepareAudio();
**Image Configuration:**
 ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
 rtmpCamera2.getGlInterface().setFilter(imageObjectFilterRender);
 Bitmap image = BitmapFactory.decodeStream(url.openConnection().getInputStream());
  imageObjectFilterRender.setImage(image);
  **Reference image url:**
![sport-congresse](https://user-images.githubusercontent.com/78897848/184824301-1a954c82-4920-40f8-bec1-888fd8f2f44f.jpg)

**Comment by pedroSG94** [comment]
Hello,

I was testing your case. 

The bitrate using default app with your image filter is working as expected. The only way to reduce bitrate is using image full screen, but it is expected.
Are you using image filter full screen?
Keep in mind that if you use full screen filter or a high part of screen, the bitrate could go down because you are streaming a static image, so h264 algorithm reduce the bitrate because pixels never change.
It is not a bug. You can try setScale to 20, 20 percent of screen to check it.

**Comment by nirmala-ncompass** [comment]
Hi @pedroSG94
I tried to set scale of screen, bitrate is not reduced as you mentioned above.
We are using image filter in full screen. Is there any solution to stream image in full screen without bitrate reduce?
