### ISSUE TITLE
add SRT

### ISSUE THREAD

**Issue by lql7993259lql** [pedroSG94/RootEncoder#1172]
add SRT

**Comment by minhchuduc** [comment]
One more vote for supporting SRT (y) @pedroSG94

**Comment by pedroSG94** [comment]
Hello,

I have the first version usable for SRT protocol in this branch:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/srt

You can compile the project and test the example. It is a first version and crash/fails are normal (it is not stable).
You can use this PR for more info about the state:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/pull/1268

Any feedback are welcome
