### ISSUE TITLE
I can't contact the RTSP address. 

### ISSUE THREAD

**Issue by Dragon-xiang-fang** [pedroSG94/RootEncoder#1175]
I use vlc media player, but I can't contact the RTSP address.
I used the format as "rtsp://192.168.1.1:1935/live/pedroSG94 RTSPS", but it constantly keep showing "Retry".
![picture (2)](https://user-images.githubusercontent.com/98225456/191894334-4ff8f276-fad6-43c4-9e17-bf3ddb230eeb.jpg)

Is there any thing wrong?
What‘s more, I tried to find the problem, but I didn't succeed.
![pic](https://user-images.githubusercontent.com/98225456/191895249-4debdd2c-5012-4542-80a1-7a5221bb7e7a.jpg)

What should I do？Hope to get a reply！Thanks！

**Comment by Dragon-xiang-fang** [comment]
@pedroSG94

**Comment by pedroSG94** [comment]
Hello,
According with the log you can't connect to your rtsp server.
Are you sure that you have an rtsp server configured in that direction and listening in that port?
To discard problems with your server you can test with any server of this list:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested#rtsp

**Comment by Dragon-xiang-fang** [comment]
![image](https://user-images.githubusercontent.com/98225456/192124861-620a1480-7fdb-41ae-a561-c708d1a814c1.png)
**I think this should be right**
**I don't know much about RSTP connection. I just want to broadcast on the LAN.**

**Comment by Dragon-xiang-fang** [comment]
@pedroSG94 
**_Thank you for taking the time to reply to me. Sorry to bother you, but I hope you can reply again. Thanks!_**

**Comment by pedroSG94** [comment]
Hello,
Are you sure that you have a server?
This library send video/audio to a server and then you can receive that video using a player.
If you want stream directly to a player you can use this:
https://github.com/pedroSG94/RTSP-Server

**Comment by Dragon-xiang-fang** [comment]
**Thank you very much. The problem is solved.**
