### ISSUE TITLE
How to set CBR?

### ISSUE THREAD

**Issue by ggpaeg** [pedroSG94/RootEncoder#1176]
Hi @pedroSG94!

How could I proceed in order to use CBR and turn off the adaptative bit rate?

**Comment by pedroSG94** [comment]
CBR is configured if your video encoder support it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L134
