### ISSUE TITLE
RtmpDisplay  stream screen only has 3 fps

### ISSUE THREAD

**Issue by supr3me** [pedroSG94/RootEncoder#1188]
Hi @pedroSG94 
I use RtmpDisplay and videoDecoder set fps 30 , but  result is only 3 or 4 fps ,when I do not move my screen.
And when I move my screen , it may have 30-40 fps
How can I set fps at least 30?
Thank you very much!

**Comment by pedroSG94** [comment]
Hello,

This is the way that MediaProjection API works. I can't do anything about it.
I have a method to force glthread to render (basically repeat frame) but sometimes it is not working in all devices:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/displayexample/DisplayService.kt#L71
If it is not working. One solution could be create a way to render the screen continually like an animated notification
