### ISSUE TITLE
How can reconnect if read time out

### ISSUE THREAD

**Issue by littlemary1379** [pedroSG94/RootEncoder#1197]
Hello, pedro!
I am currently developing rtmp transfers in a below average internet environment.
I have downloaded and used your example app. After outputting for 2 to 5 minutes, null is generated in the message part of the handleMessages part, and the broadcasting is cut off. 
At this point, I want to reset the socket and reconnect. What should I do?
Here's how I've tried it:
`  @Throws(IOException::class)
  private fun handleMessages() {
    var socket = this.socket ?: throw IOException("Invalid socket, Connection failed")
    Log.i(TAG, "socket ?  ${socket.isConnected()}")

    var message : RtmpMessage? = null

    try {
      message = commandsManager.readMessageResponse(socket)
    } catch (E : Exception) {
      Log.i(TAG, E.message.toString())
      closeConnection()
      establishConnection()
      return
    }
    if(message.toString() == "") {
      Log.i(TAG, "handleMessages empty")

    } else {
      Log.i(TAG, "handleMessages $message")
      if(message == null) {
        if(running) {
          Log.i(TAG, "message null !!")
          closeConnection()
          establishConnection()
          return
        }
      }
    }`

**Comment by pedroSG94** [comment]
Hello,

You don't need modify the library. You can use reconnection feature like in the default example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L96
Remember configure the number of retries:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L73
