### ISSUE TITLE
Different rotations for preview and recording/streaming

### ISSUE THREAD

**Issue by pluesenpai** [pedroSG94/RootEncoder#1198]
Hey there,
I have the same problems mentioned in issue #730. I need the activity orientation to be fixed in portrait (`android:screenOrientation="sensorPortrait"`) and record and stream either in portrait or landscape depending on a user preference, set on activity start.
I cannot find `lockCurrentUIState()` or `unlockUIState()` anywhere, both here and in Android documentation.
Any suggestions?

Thanks.

**Comment by pedroSG94** [comment]
Use rotation example.
Closing as inactive.
