### ISSUE TITLE
Question | Infinite focus

### ISSUE THREAD

**Issue by rashid56156** [pedroSG94/RootEncoder#1199]
Hello Pedro, i am using Camera1 with openGl rtmp, i am trying to set infinite focus. I believe if if i disable auto focus, it will be equivalent to infinite focus which i have done but some how it is not working for me. Is there any other way to achieve the infinite focus?

**Comment by pedroSG94** [comment]
Hello,
Sorry for late response I was on holydays.
Actually the only way to do it is using: rtmpCamera1.disableAutoFocus();
Make sure you call it after startPreview
