### ISSUE TITLE
Failed to resolve v2.2.1 from Jitpack.io

### ISSUE THREAD

**Issue by hantrungkien** [pedroSG94/RootEncoder#1201]
Hi bro, after delete the ./gradle/caches folder then I can not fetch this library from jitpack.io. I have seen a error:

![Screenshot from 2022-12-08 10-35-19](https://user-images.githubusercontent.com/20286370/206350482-5594db5b-15d4-477e-892c-2334d28c76db.png)

https://jitpack.io/com/github/pedroSG94/rtmp-rtsp-stream-client-java/2.2.1/build.log

Could you please fix it help me? Thanks!

**Comment by pedroSG94** [comment]
Fixed, Try using version 2.2.2
