### ISSUE TITLE
FPS is not consistent while streaming in tablets

### ISSUE THREAD

**Issue by sowmiya-ncompass** [pedroSG94/RootEncoder#1202]
Hi @pedroSG94 . FPS is not consistent while streaming in tablets. App is struggling to stream when streamed for more than 2 hours

Tablet mmodel : Samsung - SM-A525F
Started the stream with 80% charge and streaming 3hrs stream
--
Initially the FPS was below 28-29
After one hr - Network IN is below 1mbps.
Battery percentage - 50
After one & half hr -  Mobile struggled to stream
Started again, Network IN is not increasing. Failed to stream
Click back from streaming page
Phone got stuck.
After sometime started it again
Network IN was high and FPS was 28 to 30.
Stopped the stream and battery percentage - 30

**Comment by pedroSG94** [comment]
Closing as inactive.
