### ISSUE TITLE
disable video while streaming

### ISSUE THREAD

**Issue by ramanareddy463** [pedroSG94/RootEncoder#1204]
Hi @pedroSG94,
How to disable video while streaming (version 2.2.2)

**Comment by pedroSG94** [comment]
Hello,
You can use 2 ways:
- Use black filter and remove it after: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L175
- Use muteVideo/unmeteVideo methods:
```java
rtmpCamera1.getGlInterface().muteVideo();
```
