### ISSUE TITLE
SocketException crash when called stopStream during connecting

### ISSUE THREAD

**Issue by socialError** [pedroSG94/RootEncoder#1205]
When stop stream is called durring connecting app sometimes crashes. 

Crash log:
<img width="1141" alt="Screenshot 2022-12-20 at 16 29 17" src="https://user-images.githubusercontent.com/32396097/208703961-49a9a91d-f7df-4f38-aa37-ac753a48ae95.png">

**How to easilly reproduce this issue:**
at the end of valid streaming url add "xyz" and set some retry count (for instance 10). Durring connecting phase call stopStream and app crashes a lot in this case.

Could you please take a loot at it? 

Also big thanks for the library it's great :)

**Comment by pedroSG94** [comment]
Hello,
Sorry for late response. I was on holydays.
I will handle with this as soon as I can. Thank you for report

**Comment by pedroSG94** [comment]
This should be fixed now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b4ca9bd7569855dd0e9c261fc83c41fb7a10a951
