### ISSUE TITLE
How can we maintain FPS 30 in the restricted bandwidth using adaptive bitrate logic?

### ISSUE THREAD

**Issue by nirmala-ncompass** [pedroSG94/RootEncoder#1206]
If we restrict the bandwidth (ex. 3MB,2MB,1MB), within 1 minute lot of fluctuations happening in the bitrate when we use Adaptive bitrate logic.
Because of this bitrate fluctuations FPS is not maintaining at 29 or 30.  How can we maintain FPS around 30 even we restrict the bandwidth?? How can we reduce the fluctuations??

**Comment by pedroSG94** [comment]
Closing as inactive.
