### ISSUE TITLE
Take a frame in realtime, process, shift the outgoing frame by XY.

### ISSUE THREAD

**Issue by envery** [pedroSG94/RootEncoder#1207]
Greetings. 
You have a very good project.
Please tell me what needs to be done in order to take a frame in realtime, process it with opencv, and shift the outgoing frame by XY coordinates to stabilize the camera shake.
I think it 's better to do the shift in your own way using the opengl realtime filter ? Is it possible to give an example of how to create a frame processing function and cause a frame shift from it?
Best Regards pedroSG94 and all github team !!!

**Comment by pedroSG94** [comment]
Hello,
OpenCV is not supported in this library. The only way to modify the output frames is using openGL with a filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters

You can use getGlInterface().takePhoto method to get frames as bitmap, convert it to argb byte array and proccess it with openCV. With the data you can use the filter to modify the image but I think that the first step will be really slow so I'm not sure it is a good idea.

Few devices support camera stabilization using camera2 api that maybe is the best way to handle with this problem. It is already implemented in the library using this methods:
```java
rtmpCamera2.enableVideoStabilization()
rtmpCamera2.enableOpticalVideoStabilization()
```
