### ISSUE TITLE
HUWEI Hongmeng system 3.0 Flashback

### ISSUE THREAD

**Issue by tianguo1314** [pedroSG94/RootEncoder#1211]
Error Log：
-------------------------------------------------------------------------------------------------------------------------
#00 pc 0000000000042e84 /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) [arm64-v8a::e18cca17d252ede5b01226139ce195f2]
#01 pc 000000000044d57c /apex/com.android.art/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+1708) [arm64-v8a::ab71c02d26b3c6ac213f327a7e32f089]
#02 pc 00000000000049e0 /apex/com.android.art/lib64/libbase.so [arm64-v8a::c2223684f28269a88f71e985c49cbb2f]
#03 pc 0000000000001e34 /system/lib64/liblog.so (__android_log_assert+308) [arm64-v8a::04e83ac83390c69d3032b22ed1771931]
#04 pc 0000000000060d30 /system/lib64/libaudioclient.so (_ZN7android11ClientProxy13releaseBufferEPNS_5Proxy6BufferE+420) [arm64-v8a::140f518470ad82c5cc70c579e1b36d21]
#05 pc 000000000001b6ac /system/lib64/libaudioclient.so (_ZN7android11AudioRecord13releaseBufferEPKNS0_6BufferE+176) [arm64-v8a::140f518470ad82c5cc70c579e1b36d21]
#06 pc 000000000001de18 /system/lib64/libaudioclient.so (_ZN7android11AudioRecord4readEPvmb+308) [arm64-v8a::140f518470ad82c5cc70c579e1b36d21]
#07 pc 00000000000cac40 /system/lib64/libandroid_runtime.so [arm64-v8a::dc5a43829f01fee12b737082d6afd759]
#08 pc 0000000000025588 /system/framework/arm64/boot-framework.oat (oatdata+148872) [arm64-v8a::f8c4169a0ff2cd059c41bcdf17d4c75f]
java:
android.media.AudioRecord.read(AudioRecord.java:1500)
android.media.AudioRecord.read(AudioRecord.java:1452)
com.pedro.encoder.input.audio.MicrophoneManager.read(MicrophoneManager.java:207)
com.pedro.encoder.input.audio.MicrophoneManager$1.run(MicrophoneManager.java:171)
android.os.Handler.handleCallback(Handler.java:966)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loopOnce(Looper.java:205)
android.os.Looper.loop(Looper.java:293)
android.os.HandlerThread.run(HandlerThread.java:67)
-------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------

0poll0+136)
--
101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.nio.ch.PollArrayWrapper.poll0(Native method)
201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.nio.ch.PollArrayWrapper.poll(PollArrayWrapper.java:115)
301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.nio.ch.PollSelectorImpl.doSelect(PollSelectorImpl.java:87)
401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] - locked <0x00d727d5> (a sun.nio.ch.PollSelectorImpl)
601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] - locked <0x0d7d0bea> (a java.util.Collections$UnmodifiableSet)
701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] - locked <0x08db8edb> (a io.netty.channel.nio.SelectedSelectionKeySet)
801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
1001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
1101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
1201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
1301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.lang.Thread.run(Thread.java:930)
1401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
1501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "arch_disk_io_0" prio=5 tid=82 Waiting
1601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x16683928 self=0x7347c10400
1701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12559 nice=0 cgrp=foreground sched=0/0 handle=0x72ea79fcb0
1801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 4451823 44758492 22 ) utm=0 stm=0 core=5 HZ=100
1901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72ea69c000-0x72ea69e000 stackSize=1039KB
2001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
2101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 0000000000085d5c /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
2201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 000000000069a420 /apex/com.android.art/lib64/libart.so (art::Thread::Park(bool, long)+472)
2301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 00000000005b2bb8 /apex/com.android.art/lib64/libart.so (art::Unsafe_park(_JNIEnv*, _jobject*, unsigned char, long)+648)
2401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.misc.Unsafe.park(Native method)
2501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] - waiting on an unknown object
2601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
2701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
2801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
2901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
3001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
3101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
3201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.lang.Thread.run(Thread.java:930)
3301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
3401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "TP-CPUBound-2" prio=4 tid=84 Waiting
3501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x16683b58 self=0x73461fc000
3601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12561 nice=11 cgrp=foreground sched=0/0 handle=0x72e958bcb0
3701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 55196410 464599475 208 ) utm=4 stm=0 core=5 HZ=100
3801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72e9488000-0x72e948a000 stackSize=1039KB
3901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
4001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 0000000000085d5c /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
4101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 000000000069a420 /apex/com.android.art/lib64/libart.so (art::Thread::Park(bool, long)+472)
4201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 00000000005b2bb8 /apex/com.android.art/lib64/libart.so (art::Unsafe_park(_JNIEnv*, _jobject*, unsigned char, long)+648)
4301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.misc.Unsafe.park(Native method)
4401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] - waiting on an unknown object
4501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
4701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
4801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at com.tencent.tbscommon.threadpool.MyThreadPoolExecutor.g(TbsJavaCore:11)
4901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at com.tencent.tbscommon.threadpool.MyThreadPoolExecutor.a(TbsJavaCore:47)
5001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at com.tencent.tbscommon.threadpool.MyThreadPoolExecutor$a.run(TbsJavaCore:1)
5101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.lang.Thread.run(Thread.java:930)
5201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at com.tencent.tbscommon.threadpool.QBThreadFactory$a.run(TbsJavaCore:2)
5301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
5401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "TBSBeaconUploader" prio=5 tid=85 Native
5501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x16683c48 self=0x73461fdc00
5601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12563 nice=0 cgrp=foreground sched=0/0 handle=0x72e7481cb0
5701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 22897293 26583645 56 ) utm=1 stm=0 core=4 HZ=100
5801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72e737e000-0x72e7380000 stackSize=1039KB
5901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
6001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 00000000000d8838 /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
6101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 00000000000166a8 /system/lib64/libutils.so (android::Looper::pollInner(int)+180)
6201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 000000000001658c /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
6301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #03 pc 0000000000191118 /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
6401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.nativePollOnce(Native method)
6501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.next(MessageQueue.java:374)
6601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loopOnce(Looper.java:163)
6701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loop(Looper.java:293)
6801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.HandlerThread.run(HandlerThread.java:67)
6901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
7001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "Rendering thread" prio=5 tid=86 Native
7101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x16683d30 self=0x7336585c00
7201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12564 nice=0 cgrp=foreground sched=0/0 handle=0x72e6377cb0
7301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 14878113362 10778108352 46695 ) utm=1038 stm=449 core=5 HZ=100
7401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72e6274000-0x72e6276000 stackSize=1039KB
7501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
7601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 0000000000085d5c /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
7701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 000000000028c274 /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+156)
7801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 000000000046c274 /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+528)
7901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #03 pc 0000000000150058 /system/lib64/libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long, android::PhysicalDisplayId, unsigned int, android::VsyncEventData)+92)
8001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #04 pc 00000000000b52e4 /system/lib64/libgui.so (android::DisplayEventDispatcher::handleEvent(int, int, void*)+208)
8101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #05 pc 0000000000016984 /system/lib64/libutils.so (android::Looper::pollInner(int)+912)
8201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #06 pc 000000000001658c /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
8301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #07 pc 0000000000191118 /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
8401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.nativePollOnce(Native method)
8501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.next(MessageQueue.java:374)
8601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loopOnce(Looper.java:163)
8701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loop(Looper.java:293)
8801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at com.esri.arcgisruntime.mapping.view.GeoView$RenderingThread.run(SourceFile:5)
8901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
9001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "Rendering thread" prio=5 tid=36 Native
9101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x16683e50 self=0x7336587800
9201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12572 nice=0 cgrp=foreground sched=0/0 handle=0x72db744cb0
9301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 12623087436 8692807095 31496 ) utm=958 stm=304 core=0 HZ=100
9401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72db641000-0x72db643000 stackSize=1039KB
9501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
9601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 0000000000085d5c /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
9701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 000000000028c274 /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+156)
9801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 000000000046c274 /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+528)
9901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #03 pc 0000000000150058 /system/lib64/libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long, android::PhysicalDisplayId, unsigned int, android::VsyncEventData)+92)
10001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #04 pc 00000000000b52e4 /system/lib64/libgui.so (android::DisplayEventDispatcher::handleEvent(int, int, void*)+208)
10101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #05 pc 0000000000016984 /system/lib64/libutils.so (android::Looper::pollInner(int)+912)
10201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #06 pc 000000000001658c /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
10301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #07 pc 0000000000191118 /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
10401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.nativePollOnce(Native method)
10501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.next(MessageQueue.java:374)
10601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loopOnce(Looper.java:163)
10701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loop(Looper.java:293)
10801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at com.esri.arcgisruntime.mapping.view.GeoView$RenderingThread.run(SourceFile:5)
10901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
11001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "arch_disk_io_1" prio=5 tid=87 Waiting
11101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x16684920 self=0x7346029c00
11201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12570 nice=0 cgrp=foreground sched=0/0 handle=0x72db958cb0
11301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 1715675 23225055 64 ) utm=0 stm=0 core=5 HZ=100
11401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72db855000-0x72db857000 stackSize=1039KB
11501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
11601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 0000000000085d5c /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
11701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 000000000069a420 /apex/com.android.art/lib64/libart.so (art::Thread::Park(bool, long)+472)
11801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 00000000005b2bb8 /apex/com.android.art/lib64/libart.so (art::Unsafe_park(_JNIEnv*, _jobject*, unsigned char, long)+648)
11901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at sun.misc.Unsafe.park(Native method)
12001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] - waiting on an unknown object
12101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
12201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
12301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
12401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
12501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
12601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at java.lang.Thread.run(Thread.java:930)
12801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697]
12901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] "X5MemoryMonitor" prio=5 tid=88 Native
13001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| group="" sCount=1 ucsCount=0 flags=1 obj=0x166849e8 self=0x7347ce3c00
13101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| sysTid=12571 nice=0 cgrp=foreground sched=0/0 handle=0x72db84ecb0
13201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| state=S schedstat=( 89400063 328688383 381 ) utm=4 stm=3 core=5 HZ=100
13301-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| stack=0x72db74b000-0x72db74d000 stackSize=1039KB
13401-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] \| held mutexes=
13501-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #00 pc 00000000000d8838 /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
13601-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #01 pc 00000000000166a8 /system/lib64/libutils.so (android::Looper::pollInner(int)+180)
13701-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #02 pc 000000000001658c /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
13801-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] native: #03 pc 0000000000191118 /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
13901-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.nativePollOnce(Native method)
14001-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.MessageQueue.next(MessageQueue.java:374)
14101-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loopOnce(Looper.java:163)
14201-06 14:53:36.140 12325 18853 F rrow.technolog: runtime.cc:697] at android.os.Looper.loop(Looper.java:293)
14301-06 14:53:36.141 12325 18876 I RtmpSender: wrote Video packet, size 929
14401-06 14:53:36.172 12325 18876 I RtmpSender: wrote Video packet, size 1041
14501-06 14:53:36.204 12325 18060 D PipelineWatcher: DEBUG: elapsed 0 / 0
14601-06 14:53:36.204 12325 18060 D PipelineWatcher: DEBUG: elapsed 0 / 0
14701-06 14:53:36.204 12325 18060 D PipelineWatcher: DEBUG: elapsed 0 / 0
14801-06 14:53:36.206 12325 18876 I RtmpSender: wrote Video packet, size 1073
14901-06 14:53:36.239 12325 18876 I RtmpSender: wrote Video packet, size 1089
15001-06 14:53:36.272 12325 18876 I RtmpSender: wrote Video packet, size 1121
15101-06 14:53:36.312 12325 18876 I RtmpSender: wrote Video packet, size 1297
15201-06 14:53:36.345 12325 18876 I RtmpSender: wrote Video packet, size 1313
15301-06 14:53:36.388 12325 18876 I RtmpSender: wrote Video packet, size 1233
15401-06 14:53:36.407 12325 18876 I RtmpSender: wrote Video packet, size 1233

**Comment by pedroSG94** [comment]
Do you have this problem always?
Can you tell me device model and android version?

**Comment by pedroSG94** [comment]
Closing as inactive.
