### ISSUE TITLE
Example Project Background service example is not running properly

### ISSUE THREAD

**Issue by ranshao0121** [pedroSG94/RootEncoder#1212]
Hello, first of all thank you very much for providing this project, I use background service example, prompt RTP service destroy.  The log content is as follows 

I/VideoEncoder: 1 encoders found
I/VideoEncoder: Encoder OMX.amlogic.video.encoder.avc
I/VideoEncoder: Color supported: 2135033992
I/VideoEncoder: Color supported: 19
I/VideoEncoder: Color supported: 21
I/VideoEncoder: Color supported: 2141391872
I/VideoEncoder: Color supported: 2130708361
I/VideoEncoder: Encoder selected OMX.amlogic.video.encoder.avc
I/OMXClient: IOmx service obtained
I/VideoEncoder: Prepare video info: SURFACE, 480x640
I/VideoEncoder: bitrate mode CBR not supported using default mode
I/MediaCodec: MediaCodec will operate in async mode
I/AmAVUtils: AmAVUtils::getComponentRole isEncoder :1 mime:video/avc 
V/AVUtils: AVUtils::getComponentRole
W/OMXUtils: do not know color format 0x7f000789 = 2130708361
I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level4]
W/ACodec: [OMX.amlogic.video.encoder.avc] setting color aspects failed even though codec advertises support
I/ACodec: [OMX.amlogic.video.encoder.avc] cannot encode color aspects. Ignoring.
W/ACodec: [OMX.amlogic.video.encoder.avc] setting HDRStaticInfo failed even though codec advertises support
I/ACodec: [OMX.amlogic.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
I/ACodec: setupVideoEncoder succeeded
I/AmAVUtils: AmAVUtils::isAudioExtendFormat input = video/avc
I/AmAVUtils: AmAVUtils::isExtendFormat input = video/avc
W/OMXUtils: do not know color format 0x7f000789 = 2130708361
W/ACodec: [OMX.amlogic.video.encoder.avc] getting color aspects failed even though codec advertises support
W/ACodec: [OMX.amlogic.video.encoder.avc] setting color aspects failed even though codec advertises support
W/ACodec: [OMX.amlogic.video.encoder.avc] getting color aspects failed even though codec advertises support
I/VideoEncoder: prepared
I/MicrophoneManager: Microphone created, 32000hz, Stereo
I/AudioEncoder: 1 encoders found
I/AudioEncoder: Encoder selected OMX.google.aac.encoder
I/OMXClient: IOmx service obtained
I/MediaCodec: MediaCodec will operate in async mode
I/AmAVUtils: AmAVUtils::getComponentRole isEncoder :1 mime:audio/mp4a-latm 
V/AVUtils: AVUtils::getComponentRole
I/AmAVUtils: AmAVUtils::isAudioExtendFormat input = audio/mp4a-latm
I/AmAVUtils: AmAVUtils::isExtendFormat input = audio/mp4a-latm
I/AudioEncoder: prepared
I/VideoEncoder: started
I/AudioEncoder: started
I/SurfaceManager: GL released
E/SurfaceManager: GL already released
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/SurfaceManager: GL initialized
I/SurfaceManager: GL initialized
I/MicrophoneManager: Microphone started
E/RtpService: RTP service destroy

![image](https://user-images.githubusercontent.com/15192283/212219326-ed8bd815-92b5-419a-aa69-057c593b1b29.png)

If you have time, could you help me confirm this problem?  The other examples in the sample project work, only this background service example does not work.  Thank you very much

**Comment by pedroSG94** [comment]
The problem was related with a bug in the code example already fixed
Closing as inactive.
