### ISSUE TITLE
Is this library support both landscape and portrait modes simultaneously?

### ISSUE THREAD

**Issue by kkvarma9387** [pedroSG94/RootEncoder#1216]
Hi Team,

Thanks for the great library which you provided.

We need help regarding the streaming modes issue.
Can this possible to make a whole video stream in both landscape and portrait mode?
Example: Initially we started streaming in portrait mode and then after some time I switched to landscape mode and the streaming is not working for now when we move from portrait to landscape mode. again If I switch to portrait mode it's working.  

"The video streaming should work both in portrait and landscape mode depending on a user's preference while they are in streaming they can able to change the device orientation and continue the streaming without any issues.r"

Please help us to fix this issue. Thanks in advance.

Thanks, 
Kumar

**Comment by pedroSG94** [comment]
Hello,
You have an example related with your case:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/rotation

Did you test it? 
If you have problems with the example. Can you explain exactly how to reproduce your case?
