### ISSUE TITLE
Android 12 box recording screen streaming, playing streaming picture garbled

### ISSUE THREAD

**Issue by iqiluwxy** [pedroSG94/RootEncoder#1219]
Hello, I used DisplayService on the Android 12 box to record the screen and push the stream, and then used the vlc player to pull the stream, but the picture was garbled, but after I used the Android 9 box to record the screen and push the stream and played the pull address, there was no such phenomenon, may I ask if you have any idea about it?
<img width="960" alt="835a787e40e3cae7b2209e41b1978bc" src="https://user-images.githubusercontent.com/31097667/215725567-d3c2d322-a52d-46a6-a60c-cd955709c87c.png">

**Comment by pedroSG94** [comment]
Maybe it is related with a video encoder bug in you Android 12. 
Can you check in logcat if you are using the same video encoder in both cases? The idea is exclude you encoder here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java#L418

**Comment by pedroSG94** [comment]
Closing as inactive.
