### ISSUE TITLE
dropping old packet received too late

### ISSUE THREAD

**Issue by zhubinsheng** [pedroSG94/RootEncoder#1222]
https://github.com/zhubinsheng/FFmpeg/blob/master/libavformat/rtpdec.c#:~:text=%22RTP%3A%20dropping%20old%20packet%20received%20too%20late%5Cn%22)%3B

**Comment by zhubinsheng** [comment]
use ijkplayer play rtsp, if seek will logcat  "RTP: dropping old packet received too late\n"

**Comment by pedroSG94** [comment]
Closing as inactive.
