### ISSUE TITLE
Is it possible to capture the specific area of screen?

### ISSUE THREAD

**Issue by SanKoKo** [pedroSG94/RootEncoder#1224]
Hello PedroSG94;
First of all, thank you so much for your library. I would like to know is it possible to capture the specific area of screen? If it is, how? I cannot figure it out. Thank you.

**Comment by pedroSG94** [comment]
Solved in the last commit using CropFilterRender:
https://github.com/pedroSG94/RootEncoder/commit/73dc88c6fffd37c03d0a518080022a9701e46e5a
Closing issue
