### ISSUE TITLE
bitmap is recycled at android.opengl.GLUtils.texImage2D

### ISSUE THREAD

**Issue by hemant-novotrax** [pedroSG94/RootEncoder#1226]
Hello Pedro,
In many devices app crashes bellow line. 

```
public int[] load(Bitmap[] bitmaps) {
    int[] textureId = new int[bitmaps.length];
    GlUtil.createTextures(bitmaps.length, textureId, 0);
    for (int i = 0; i < bitmaps.length; i++) {
      if (bitmaps[i] != null) {
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, textureId[i]);
        GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, bitmaps[i], 0);
        bitmaps[i].recycle();
        bitmaps[i] = null;
      }
    }
    return textureId;
  }
```
  
  
<img width="800" alt="Screenshot 2023-03-03 184019" src="https://user-images.githubusercontent.com/90753441/222729851-7e29d239-ee89-44c3-8946-bc5a8937ccf7.png">

**Comment by pedroSG94** [comment]
fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/97fa5ffb2b311ddcf674be47f1468c1b6c0e38ed#diff-9080294adb04c773eead376b12617643d1c5d16ca24039d43d20e1d7720f997dR40
Compile library version 2.2.4 and the error should be solved
