### ISSUE TITLE
Question: Highest resolution

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RootEncoder#1227]
What is the highest resolution can we stream with this library?
or is it bound to?

rtmpCamera.getResolutionsFront();

**Comment by pedroSG94** [comment]
The highest resolution depend of your device. Normally is the higher obtained by rtmpCamera.getResolutionsBack using camera2. 
Remember that if your front camera doesnt support that resolution you can't switch camera (you will get an error if you do it)

**Comment by pedroSG94** [comment]
Closing as inactive.
