### ISSUE TITLE
Unable to stream from RtmpFromFile.

### ISSUE THREAD

**Issue by zari786** [pedroSG94/RootEncoder#1233]
Hi @pedroSG94  first of all thankyou for great library, 
I'm not able to stream prerecorded video on facebook rtmp url, its woking fine on different devices I've tested but the issue occur on Samsung SM-G970F Android 10 onVideoDecoderFinished() this method is called when I start the stream. Here is the details of video

![Screenshot_20230403-120222_MX Player](https://user-images.githubusercontent.com/34839678/229437090-ad9d1db2-7704-4870-a40c-2c812ccb91b1.jpg)

Any help will be appreciated.

**Comment by pedroSG94** [comment]
Unable to reproduce. If you can provide more info or share the video to test you can reopen it
Closing as inactive.
