### ISSUE TITLE
Error Sps or pps null when calling preparevideo in foreground service in another thread

### ISSUE THREAD

**Issue by Kutensa** [pedroSG94/RootEncoder#1234]
basically i am unable to start server in foreground service unless i do it in onstartcommand().
The reason i want to start server outside of  onstartcommand(). is i want to tell the server to change video quality on demand in the background.
so i was planning to stop and start the server each time i want to change the quality with different parameters for preparevideo() .
it would be helpfull if there is any other to achieve the same in a foreground service if anyone can suggest.
otherwise i dont know why am unable to succefull call preparevideo() and prepareaudio in threads  in the service apart from startcommand.

am using constractor RtspServerCamera2(context,useopengl, ConnectCheckerRtsp).

**Comment by Kutensa** [comment]
server.setVideoBitrateOnFly() accomplices my problem.
nonetheless would still want to know why am unable to successfully call preparevideo() and prepareaudio in threads outside startcommand.

**Comment by pedroSG94** [comment]
Closing as inactive. Reopen issue if needed
