### ISSUE TITLE
Use this library to stream on Facebook using Genymotion

### ISSUE THREAD

**Issue by dev-android1** [pedroSG94/RootEncoder#1236]
This is working fine on Real device but when i use this on Genymotion to publish on Facebook Live app hangs.
I tried few combination but every time app hangs and Facebook gives error low key frame rate.
I tried to change Frame rate to 30,40 but did not work.

displayBase?.prepareVideo(360, 640, 30, 2 * 1000 * 1024, 0,densityDpi,-1,-1,30)

**Comment by pedroSG94** [comment]
Error related with software encoder in Genymotion emulator. I can't fix it
Closing as inactive.
