### ISSUE TITLE
Error in decoding video: non-existing PPS 0 referenced

### ISSUE THREAD

**Issue by hamza-naeem** [pedroSG94/RootEncoder#1238]
Hello,

I am encountering an issue where the saved rtmp stream cannot be played by ffplay, resulting in the following error message:

```
[h264 @ 0x7f4c4e5cd780] decode_slice_header error
[h264 @ 0x7f4c4e5cd780] no frame!
[h264 @ 0x7f4c4e5cd780] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0x7f4c4e5cd780] decode_slice_header error
[h264 @ 0x7f4c4e5cd780] no frame!
[mpegts @ 0x7f4c50cfa800] decoding for stream 0 failed
```

My device is a Radxa Rock 5B, and I am using the "c2.rk.avc.encoder" hardware encoder. I have attempted to resolve the issue by changing the iFrameinterval to 0, but the problem persists. However, when I use a software decoder, the issue is resolved. Unfortunately, my requirements necessitate the use of the hardware encoder. Can you provide assistance with this matter?

@pedroSG94

**Comment by pedroSG94** [comment]
I can't reproduce the issue. You can try using software encoder. Reopen issue if needed
Closing as inactive.
