### ISSUE TITLE
Stream Animated text

### ISSUE THREAD

**Issue by RedwanSharafatKabir** [pedroSG94/RootEncoder#1240]
I am trying to use Animated text as filter. But app is crashing.
Text animation code:
textView.ellipsize = TextUtils.TruncateAt.MARQUEE
textView.isSelected = true
textView.isSingleLine = true

I am using this textview as filter into AndroidViewFilterRender().

But always app is crashing and giving this error - "java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?"

**Comment by pedroSG94** [comment]
Closing as inactive.
