### ISSUE TITLE
The log message "RtmpSender: Skipping iteration, frame null" appears when I start the push. What's Skipping Iteration, Frame Null

### ISSUE THREAD

**Issue by Ckarelie** [pedroSG94/RootEncoder#1242]
RtmpCamera2(AutoFitTextureView,...).setForce(SOFTWARE,FIRST_COMPATIBLE_FOUND);
and cameraRtmp.startStream();

**Comment by pedroSG94** [comment]
Normally related with bad connection issues. You can reopen issue if needed
Closing as inactive.
