### ISSUE TITLE
ScreenShare

### ISSUE THREAD

**Issue by Sodiqjon-111** [pedroSG94/RootEncoder#1245]
@Hello i just use RtmpDisplay or RtspDisplay depend of stream protocol and I create app that is about screen share.
All my code is works fin but when i input my IP and Port connection failed
i should write like that: Params:
url – of the stream like: protocol://ip:port/application/streamName RTSP: rtsp://192.168.1.1:1935/live/pedroSG94 RTSPS: rtsps://192.168.1.1:1935/live/pedroSG94 RTMP: rtmp://192.168.1.1:1935/live/pedroSG94 RTMPS: rtmps://192.168.1.1:1935/live/pedroSG94
/

but still I couldnt resolve it.
If someone is create that type of app please let me know

**Comment by pedroSG94** [comment]
Closing as inactive.
