### ISSUE TITLE
ScreenShare example

### ISSUE THREAD

**Issue by RebornQ** [pedroSG94/RootEncoder#1246]
Hello PedroSG94, thank you so much for your library at first!

I would like to know how to push screen data with rtmp? Do you have an example of screen sharing with your library?

I can not figure it out. Thank you.

**Comment by FrankLove** [comment]
It's not too difficult to do that,you can use mediaprojection get the data screen and mediacodec to encode this data to h264 ,then use the rtmpclient of this liabray to send the data.

**Comment by pedroSG94** [comment]
Hello, You can use this example that already implement all code commented by @FrankLove
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/displayexample

**Comment by RebornQ** [comment]
Thanks you very much! @FrankLove @pedroSG94
