### ISSUE TITLE
It is recommended to add a callback in the specified method to deal with frame loss caused by very occasional or unknown reasons

### ISSUE THREAD

**Issue by Rethen** [pedroSG94/RootEncoder#1248]
It is recommended to add a callback in the specified method to deal with frame loss caused by very occasional or unknown reasons，

![image](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/7802673/ebe976d9-cbd2-4e7d-afd2-f5c604812929)

When the long-term frame is lost, the caller should know, and the caller can choose to disconnect and reconnect

**Comment by pedroSG94** [comment]
You can check dropped frame variable using onBitrate callback (called each second)
Closing as inactive.
