### ISSUE TITLE
When my mobile phone uses RtmpOnlyAudio to push the audio stream to the computer nginx server to realize the function of voice call, but the quality of the voice played on the computer is very poor

### ISSUE THREAD

**Issue by ILoveLin** [pedroSG94/RootEncoder#1255]
When my mobile phone uses RtmpOnlyAudio to push the audio stream to the computer nginx server to realize the function of voice call, but the voice quality played on the computer is very poor, how can I improve the audio quality of the push? Make sure the sound quality is perfect?
This is my code
`           /**
                 * 音频配置： 码率：256*1024
                 * 采样率：44100
                 */
                //尝试启用噪声抑制器和/或回声消除器：
                mRtmpOnlyAudio.prepareAudio(256 * 1024, 44100, true,
                        true/*echo canceler*/, true/*noise suppressor*/);
                mRtmpOnlyAudio.startStream(mCurrentMicUrl);
            }`

Now I use the downloaded code, and the quality of the voice call is also a meeting card.

`           /**
                 * 音频配置： 码率：256*1024
                 * 采样率：44100
                 */
                //尝试启用噪声抑制器和/或回声消除器：
              mRtmpOnlyAudio.prepareAudio(256 * 1024, 44100, true, false, false)
                mRtmpOnlyAudio.startStream(mCurrentMicUrl);
            }`

Hello blogger, the following is the rar file of my recording, you can listen to the existence card phenomenon

[profile_icon_audioname.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/11935159/profile_icon_audioname.zip)

How can I solve the problem of voice calling card? And the problem of poor quality of voice calls, I hope you can help me, thank you.

I found a solution, compared to the previous calling card, the quality of voice calls has improved a lot
     `//音频推流
        mRtmpOnlyAudio= new RtmpOnlyAudio(this);
        //解决语音卡顿问题
        mRtmpOnlyAudio.setMicrophoneMode(MicrophoneMode.SYNC);`

Now the effect of packet loss on my voice card is much better than before.
However, there is still a sudden or sizzling sound within ten seconds, how can I solve it now?
This problem has troubled me for a long time. I hope the blogger can reply to me and help me when he sees it. Thank you.
It's my code
`
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.0.2'
//音频推流
        mRtmpOnlyAudio= new RtmpOnlyAudio(this);
        //解决语音卡顿问题
        mRtmpOnlyAudio.setMicrophoneMode(MicrophoneMode.SYNC);
        mRtmpOnlyAudio.prepareAudio(256 * 1024, 44100, true, false, false);

`
Now I have upgraded the version number
`
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.9'
//I can't use the downloaded code in the activity interface, because there is no callback function for voice calls, how can I write //my code?
mRtmpOnlyAudio= new RtmpOnlyAudio(this);
`
Why is there no callback interface (ConnectCheckerRtmp) for voice calls after upgrading to version 2.1.9?
![123456](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/20768182/60672e14-3d67-424b-8d09-a18f865edf83)

**Comment by pedroSG94** [comment]
Closing as inactive.
