### ISSUE TITLE
How to solve the problem of high CPU usage when the camera is running in the background

### ISSUE THREAD

**Issue by fennudexiaoji** [pedroSG94/RootEncoder#1269]
I hope camera opengl works in the background, but high CPU usage will affect the performance of other apps in the system. Is there any solution to this problem
![cpu](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/12570936/956b9099-af09-48dc-9614-f9f45d858c50)

**Comment by pedroSG94** [comment]
Hello,

If you don't need change to OpenGlView to use a preview on fly or filters. You can use constructor with the boolean in false. This way, the library will use MediaCodec surface to render directly and OpenGl is not used. Of course, you will lose all extra features related with OpenGl:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java#L83
Also, set a low fps value on prepareVideo method could help you. By default the value is 30fps, you can try with 20fps if it is acceptable for you.

**Comment by fennudexiaoji** [comment]
I have to use Opengl to set some watermark effects on the camera image, but lowering the fps value to 20 has no effect, and the CPU usage is still high. Is there any other way to improve it
![hahahahha](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/12570936/a0b0d9a4-14af-40a2-96f0-5c8fdbf5b25f)

**Comment by pedroSG94** [comment]
Reduce resolution and bitrate could help a bit because you are generating buffer with less size but I'm not sure if the difference could be high

Anyway a total usage of 18-21% CPU as posted in the first and second images (166 of 800 in the second image is 20.75%) are aceptable for an encoder app. 
Keep in mind that you are using around 6 threads continually (microphone, camera, audio encoder, video encoder and protocol sender/receiver) with microphone and camera opened.

I have an usage of 14-16% CPU with a google pixel 6a using OpenGl example (with preview) so I think that the performance posted is expected.

**Comment by fennudexiaoji** [comment]
hello
I found that the reason for the high CPU usage was due to the startup thread executing while true. After trying to execute sleep for 3 milliseconds, the CPU usage became very low. May I ask if there are any risks associated with such modifications
![test](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/12570936/1194c0ee-9be3-4053-af15-4df8226865ff)

**Comment by pedroSG94** [comment]
Hello,

Thank you for the report. I will check it
This should have no problems maybe a bit of Stuttering but maybe I can find a better solution

I will report you back today or tomorrow with a solution but I think that sleep depend of fps value is a good idea

**Comment by pedroSG94** [comment]
Hello,

This is already fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d82705f98da7676af5f66f9d5c2631249ed85ad3

This way you are waiting all time possible until next frame. You will wait more or less depend if you receive a frame from camera or not. This way you avoid Stuttering and increase wait time if possible doing a better performance.
You can add this commit using this gradle:
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:d82705f98d'
```
I will do a release in few days for now use gradle above
