### ISSUE TITLE
Send watermark using RtmpClient

### ISSUE THREAD

**Issue by sheng930920** [pedroSG94/RootEncoder#1271]
Hello,

Is it possible to include a watermark when streaming with RtmpClient? I want to add a watermark to the void onReceive(byte[] videoBuffer, int length) method of the H264 data returned by the DJI drone for streaming

Thank you!

**Comment by pedroSG94** [comment]
Hello,

RtmpClient don't support it. RtmpClient is only rtmp protocol.
If you want add a filter like watermark you will need use OpenGlView.
The idea is use VideoDecoder to render surface provided by OpenGlView replacing Camera API but this require create a class. You can check this example that i did for dji:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/817#issuecomment-1125451169
Maybe you need to update the code to the current library version or downgrade the library to  a version of that date
