### ISSUE TITLE
Error connecting to rtmp on real device

### ISSUE THREAD

**Issue by Moyout** [pedroSG94/RootEncoder#1274]
The rtmp server push stream was connected properly on the Android emulator, but the connection was wrong on my real device(Xiaomi Redmi K30 pro)。
`
Error configure stream, failed to connect to /192.168.31.86 (port 1935) from /192.168.31.32 (port 39202) after 5000ms: isConnected failed: EHOSTUNREACH (No route to host)
`

What are the possible reasons for this outcome

**Comment by pedroSG94** [comment]
Hello,

I think the error is that your real device have no access to your server.

Try to disable any proxy or similar program that can block connections. Also try to do a ping to your server with your real device to make sure that you have access to it (you can download an app from the store to do it).

**Comment by Moyout** [comment]
> 你好
> 
> 我认为错误是您的真实设备无法访问您的服务器。
> 
> 尝试禁用任何可以阻止连接的代理或类似程序。还可以尝试使用真实设备对服务器进行ping操作，以确保您可以访问它（您可以从商店下载应用程序来执行此操作）。

How do you test it? Do you test rtmp connections or http connections

**Comment by Moyout** [comment]
> Hello,
> 
> I think the error is that your real device have no access to your server.
> 
> Try to disable any proxy or similar program that can block connections. Also try to do a ping to your server with your real device to make sure that you have access to it (you can download an app from the store to do it).
You have no Android play rtmp software😄

**Comment by pedroSG94** [comment]
Download this app for example or a similar app:
https://play.google.com/store/apps/details?id=com.lipinic.ping&hl=es_419&gl=US

Try to do a ping to your rtmp server. If it fail then you need check your network because you can't access to your rtmp server.

**Comment by Moyout** [comment]
> 例如，下载此应用程序或类似的应用程序：https://play.google.com/store/apps/details?id=com.lipinic.ping&hl=es_419&gl=US
> 
> 尝试对 rtmp 服务器执行 ping 操作。如果失败，则需要检查网络，因为无法访问 rtmp 服务器。

Let me try

**Comment by Moyout** [comment]
I have solved the problem. It's true that my IP address is unreachable. 😅
