### ISSUE TITLE
Android 14 (API 34) Media Projection Support

### ISSUE THREAD

**Issue by isles1217** [pedroSG94/RootEncoder#1275]
**Is your feature request related to a problem? Please describe.**
Our app has begun our process to upgrade our `targetSdk` to API 34 (Android 14), however, when attempting to start an RTMP stream (using an `RtmpDisplay` via Media Projection), we get the following `IllegalStateException` crash:
```
java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.
 at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:206)
 at com.pedro.rtplibrary.base.DisplayBase.startEncoders(DisplayBase.java:404)
 at com.pedro.rtplibrary.base.DisplayBase.startStream(DisplayBase.java:376)
``` 

**Describe the solution you'd like**
We'd like to make sure the library adds the requisite callback needed to satisfy the new requirements in Android 14.

**Describe alternatives you've considered**
If the API for `RtmpDisplay` allowed the caller to provide their own Media Projection instance, the responsibility to satisfy the Android 14 requirements would fall to the caller instead of the library. Our application already instantiates our own Media Projection instances for our  other recording use cases, so for us, we'd already satisfy the Android 14 requirements. 

**Additional context**
Further, these changes would need to satisfy the new requirements of [MediaProjectionManager](https://developer.android.com/reference/kotlin/android/media/projection/MediaProjectionManager) to prevent `SecurityException` and `IllegalStateException`s from being thrown.

**Comment by pedroSG94** [comment]
Hello,

Currently Android 14 is not released yet. I guess I need to subscribe to google pixels beta to test it.
I will check it and report you back

**Comment by pedroSG94** [comment]
Hello,

I did a commit for this:
https://github.com/pedroSG94/RootEncoder/commit/0ec6591ed96552f1cbb03b566a05ce114a134df9
You can try using this gradle:
```gradle
implementation 'com.github.pedroSG94:RootEncoder:library:0ec6591ed9'
```
