### ISSUE TITLE
Send Metadata to server

### ISSUE THREAD

**Issue by invalidtask** [pedroSG94/RootEncoder#1276]
Is there a way to send metadata to the server? If so, how and where would I modify this? I looked through the RTMP code and could not find anything that stuck out.

**Comment by pedroSG94** [comment]
Hello,

Do you mean in metadata packet on connection or on each frame?
On connection you can do it here:
https://github.com/pedroSG94/RootEncoder/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManagerAmf0.kt#L84

**Comment by invalidtask** [comment]
Oh I completely missed that! I am sorry! Thank you kindly for the info!
