### ISSUE TITLE
Creating a new AndroidStudio project can run successfully, but an error will be reported if the project dependencies are referenced

### ISSUE THREAD

**Issue by ILoveLin** [pedroSG94/RootEncoder#1277]
Creating a new AndroidStudio project can run successfully, but an error will be reported if the project dependencies are referenced

When I refer to dependencies

dependencies {
  implementation 'com.github.pedroSG94.RootEncoder:library:2.2.7'
}

Project failed to run

Editor version:
    Android Studio 4.1
    Build #AI-201.8743.12.41.6858069, built on September 23, 2020
    Runtime version: 1.8.0_242-release-1644-b01 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Windows 10 10.0
    GC: ParNew, ConcurrentMarkSweep
    Memory: 4046M
    Cores: 6
    Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true

Below is the error log:
[errorLog.txt](https://github.com/pedroSG94/RootEncoder/files/12595700/errorLog.txt)

`
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidx.annotation:annotation:1.7.0.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/public/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/gradle-plugin/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://jitpack.io/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://developer.huawei.com/repo/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
     Required by:
         project :app > androidx.appcompat:appcompat:1.4.1
   > Could not find androidx.annotation:annotation:1.7.0.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/public/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/gradle-plugin/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://jitpack.io/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://developer.huawei.com/repo/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
     Required by:
         project :app > com.google.android.material:material:1.6.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.core:core:1.7.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.appcompat:appcompat-resources:1.4.1
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.emoji2:emoji2:1.0.0
   > Could not find androidx.annotation:annotation:1.7.0.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/public/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/gradle-plugin/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://jitpack.io/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://developer.huawei.com/repo/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
     Required by:
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.cursoradapter:cursoradapter:1.0.0
         project :app > com.google.android.material:material:1.6.0 > androidx.cardview:cardview:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.activity:activity:1.2.4 > androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.fragment:fragment:1.3.6 > androidx.viewpager:viewpager:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.fragment:fragment:1.3.6 > androidx.loader:loader:1.0.0
         project :app > com.google.android.material:material:1.6.0 > androidx.dynamicanimation:dynamicanimation:1.0.0 > androidx.legacy:legacy-support-core-utils:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.appcompat:appcompat-resources:1.4.1 > androidx.vectordrawable:vectordrawable-animated:1.1.0 > androidx.interpolator:interpolator:1.0.0
         project :app > com.google.android.material:material:1.6.0 > androidx.dynamicanimation:dynamicanimation:1.0.0 > androidx.legacy:legacy-support-core-utils:1.0.0 > androidx.documentfile:documentfile:1.0.0
         project :app > com.google.android.material:material:1.6.0 > androidx.dynamicanimation:dynamicanimation:1.0.0 > androidx.legacy:legacy-support-core-utils:1.0.0 > androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
         project :app > com.google.android.material:material:1.6.0 > androidx.dynamicanimation:dynamicanimation:1.0.0 > androidx.legacy:legacy-support-core-utils:1.0.0 > androidx.print:print:1.0.0
   > Could not find androidx.annotation:annotation:1.7.0.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/public/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/gradle-plugin/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://jitpack.io/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://developer.huawei.com/repo/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
     Required by:
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.activity:activity:1.2.4
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.fragment:fragment:1.3.6
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.savedstate:savedstate:1.1.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.lifecycle:lifecycle-viewmodel:2.3.1
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.resourceinspection:resourceinspection-annotation:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.drawerlayout:drawerlayout:1.1.1
         project :app > com.google.android.material:material:1.6.0 > androidx.coordinatorlayout:coordinatorlayout:1.1.0
         project :app > com.google.android.material:material:1.6.0 > androidx.transition:transition:1.2.0
         project :app > com.google.android.material:material:1.6.0 > androidx.vectordrawable:vectordrawable:1.1.0
         project :app > com.google.android.material:material:1.6.0 > androidx.viewpager2:viewpager2:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.core:core:1.7.0 > androidx.versionedparcelable:versionedparcelable:1.1.1
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.core:core:1.7.0 > androidx.concurrent:concurrent-futures:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.activity:activity:1.2.4 > androidx.tracing:tracing:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.collection:collection:1.1.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.emoji2:emoji2:1.0.0 > androidx.startup:startup-runtime:1.0.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.savedstate:savedstate:1.1.0 > androidx.arch.core:core-common:2.1.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.lifecycle:lifecycle-runtime:2.4.0 > androidx.arch.core:core-runtime:2.1.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.drawerlayout:drawerlayout:1.1.1 > androidx.customview:customview:1.1.0
         project :app > com.google.android.material:material:1.6.0 > androidx.recyclerview:recyclerview:1.1.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.lifecycle:lifecycle-runtime:2.4.0
         project :app > androidx.appcompat:appcompat:1.4.1 > androidx.savedstate:savedstate:1.1.0 > androidx.lifecycle:lifecycle-common:2.4.0
   > Could not find androidx.annotation:annotation:1.7.0.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/public/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://maven.aliyun.com/repository/gradle-plugin/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://jitpack.io/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
       - https://developer.huawei.com/repo/androidx/annotation/annotation/1.7.0/annotation-1.7.0.pom
     Required by:
         project :app > com.github.pedroSG94.RootEncoder:library:2.2.7 > com.github.pedroSG94.RootEncoder:encoder:2.2.7

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

**Comment by pedroSG94** [comment]
Hello,

I tested the gradle build and it is working as expected.
I can see that you have problems downloading annotation library not the my library itself. Do you have google maven declared?
Like this:
```gradle
allprojects {
  repositories {
    google()
    //alternative for old Android studio versions
    maven { url  "https://maven.google.com" }
  }
}
```

**Comment by pedroSG94** [comment]
After check a bit here:
https://developer.aliyun.com/mvn/search
You can filter by androidx.annotation and check that 1.7.0 is not uploaded yet to that repository.
You will have to compile version 2.2.6 until it is updated:
```gradle
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.2.6'
```

**Comment by ILoveLin** [comment]
Hello, I am a developer in mainland Chinese and cannot access this address   
maven { url  "https://maven.google.com" }
So, I keep showing access failed

**Comment by ILoveLin** [comment]
Thank you blogger for your patient answer, my problem is solved


When using Android Studio 4.1 version, when I change the JDK version to 17, I always report an error. When I upgrade the editor (Android Studio Flamingo | 2022.2.1 Patch 2), I can replace the JDK version normally, and the project runs through

**Comment by pedroSG94** [comment]
Hello,

The difference is the way AudioEncoder and Microphone works to generate frames:
- SYNC: Microphone and AudioEncoder use the same thread and get data without queue
- ASYNC: Microphone and AudioEncoder use differents thread and get data with a queue
- BUFFER: This is ASYNC mode but the timestamp change depend of buffer size

**Comment by ILoveLin** [comment]
Hello, thank you for your reply and explanation.
I tested, when I push voice audio, using VLC to play is fine, no problem
But when I use an SDK player provided by another company to play, this problem exists, so I feel that it should be the player problem of this SDK, not the problem of the voice push library
