### ISSUE TITLE
Live preview freezes after stream starts

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/RootEncoder#1278]
**Describe the bug**
Video starts fine **then freezes** after about 15 seconds
`rtmpCamera1 = new RtmpCamera1(lightOpenGlView, MainActivity.this);`

**To Reproduce**
1. Use **2.2.7**

**Expected behavior**
Normal video streaming

**Additional context**
If I use **2.2.6** it works fine

**Comment by pedroSG94** [comment]
Hello,
I fixed it here:
https://github.com/pedroSG94/RootEncoder/commit/96c69c05e4be90678703c90841b0abd8e2270544
You can use this gradle to test:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:96c69c05e4'
```
Let me know if it is working for you

**Comment by AlexUrrutia** [comment]
Tested again on 2.2.8 and it works perfect, thanks @pedroSG94
