### ISSUE TITLE
SRT Connection shows "Retry"

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RootEncoder#1294]
**Describe the bug**
Tried the demo app and when I connect to the srt server the app shows "connection success" and then immediately shows "Retry"

**To Reproduce**
1. Down and install SRTMiniServer and start it
2. Run the sample app
3. Select Default SRT button
4. Enter the url
5. Select Start Stream button

**Expected behavior**
Connect and start streaming

**Screenshots**

**Smartphone (please complete the following information):**
 - Library version 2.2.8
 - Device: Samsung S10
 - OS13
 - Media server SRTMiniServer 2.3 Windows
 - Class used: SRT Streaming

**Additional context**
Use on local wifi network

**Comment by pedroSG94** [comment]
Hello,

I tested it and I can reproduce the problem. I will fix it and report back

**Comment by pedroSG94** [comment]
I did a fast test with ffmpeg and I have the same problem. I think that the problem is related with server configuration.
I will check the reason.

For now I only opened the server app and press button to start server

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/RootEncoder/pull/1296
I will merge this soon. For now, you can compile the project in that branch and test

Remember use the streamid in the url correctly. The url should be like this:
srt://ip:port/streamid
For example I used: srt://192.168.0.191:9001/streamkey1ABC

**Comment by ToysoftInc** [comment]
It is working but on the server the preview colors are not correct.
Is this server problem or client?

See picture.

![srt_preview](https://github.com/pedroSG94/RootEncoder/assets/18074554/4a00bafb-db66-4f73-ab49-06a516938382)

**Comment by pedroSG94** [comment]
I had the same problem but it is an error in the server side preview. Use a different decoder fixed the problem for me:
![imagen](https://github.com/pedroSG94/RootEncoder/assets/17556876/01b49de9-4dd5-4d3c-9776-7d6a31d633d6)
It is in the rigth-bottom corner of the windows. I tried the second one

**Comment by ToysoftInc** [comment]
k. thx
