### ISSUE TITLE
Is it possible to specify video chunk size when recording ?

### ISSUE THREAD

**Issue by S-Ashjaa** [pedroSG94/RootEncoder#1295]
The use case for this would start recording a stream and instead of saving a large video save small chunks of the video, specified by time e.g. 3s,5s, etc

**Comment by pedroSG94** [comment]
Hello,

No, currently record video only support one single file.
I think that one way to solve this for your case is use a library to do it after finish record the video. Maybe you can do it with a wrapper of ffmpeg

**Comment by ToysoftInc** [comment]
You can create timer and just stop and record again.

**Comment by pedroSG94** [comment]
> You can create timer and just stop and record again.

It is an option if lose frames while you start again is not important

**Comment by SyedAshja** [comment]
I explored the option but the chunk size i am looking for (3 to 6s ) is very frequent which would cause multiple frame loss

**Comment by Ernovation** [comment]
If we could save the video files in small chunks, without losing frames or audio, we could upload them to a server to use directly for HLS. Then I would no longer need to have an RTSP server or RTMP server to make the video available through a browser. I think that would be really nice.

**Comment by S-Ashjaa** [comment]
I solved the problem by modifying the library to use 2 media muxer instances, This allowed me to stop and release 1 muxer while the other records and achieve 2-second chunks,but there were still some issues with MPEG writer so in the end had to move to a different solution.
