### ISSUE TITLE
How to use CameraX, IS it support CameraX? 

### ISSUE THREAD

**Issue by xuehongle** [pedroSG94/RootEncoder#1298]
How to use CameraX, IS it support CameraX? Because I want to adjust the focal length

**Comment by pedroSG94** [comment]
Hello,

CameraX is not supported currently but I can add this feature to camera2 if you want

**Comment by xuehongle** [comment]
Thanks，I want I want I want！！！



发自我的iPhone


------------------ Original ------------------
From: Pedro Sánchez ***@***.***&gt;
Date: Mon,Oct 9,2023 10:00 PM
To: pedroSG94/RootEncoder ***@***.***&gt;
Cc: xuehongle ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [pedroSG94/RootEncoder] How to use CameraX, IS it supportCameraX?  (Issue #1298)





 
Hello,
 
CameraX is not supported currently but I can add this feature to camera2 if you want

**Comment by pedroSG94** [comment]
Hello,

I edited the comment so maybe you can't see it on email but I shared you links with methods to use. It is currently added to the library using camera2

**Comment by xuehongle** [comment]
Now I can see the links, Thanks again

**Comment by pedroSG94** [comment]
Closing issue as resolved
