### ISSUE TITLE
srt authentication

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RootEncoder#1300]
When will you implement authentication for srt client?

**Comment by pedroSG94** [comment]
Hello,

It is not implemented yet because SRT has no a standard way to do authentication.
In the official documentation you can't find a way to do it so each server implement it in multiple ways. I'm not sure if I should implement each auth so it was stopped for now.
I can Implement an auth for a server but I need know the server and how to do it. Do you have a way to test it with ffmpeg?

Also, I can't find a way to test encryptation with ffmpeg or other pusher. For this reason it is also freezed for now.

**Comment by ToysoftInc** [comment]
Sorry I don't use ffmpeg. 

I was going to as you which server do you use.
I'm testing SRT MiniServer but having some issues.  Their support isn't much helpful.
Here are the problems with SRT MiniServer and using your lib

1.  Preview is not working.  I get the color problem that I have reported to you before.  Their support said I must stream atleast 720p
2. I can not playback stream from the server using vlc and other player.  They said it works but I can not get it work.

I need a server that I can preview and monitor the incoming feed.  If I just want to save the feed to a file then SRT MiniServer is really good.

thx

**Comment by pedroSG94** [comment]
> 1. Preview is not working.  I get the color problem that I have reported to you before.  Their support said I must stream atleast 720p

Did you test using a different decoder as suggested before? About resolution you can change the resolution in prepareVideo method and use 1280x720 (720p)



> I can not playback stream from the server using vlc and other player. They said it works but I can not get it work.

I don't know about it but if you can stream to the server and get preview. This should be a problem in server/player side.
I'm not sure about the url used in VLC but try something like this (obviously change ip, port and streamkey for your case):
srt://ip:port?streamid=streamkey
This is the equivalent to this url in my library:
srt://ip:port/streamkey

**Comment by ToysoftInc** [comment]
try these

1. Goto here https://srtminiserver.com/download
2. Download the SRTMiniServer
3. Install and run it
4. Click on the Settings icon (gear)
5. In the SRT encryption field enter your password
6. Download the SRTStreamer
7. Install and run it
8. Start the server
9. in the SRTStreamer enter the streamer server url
10. enter the password and click on the Start button

**Comment by pedroSG94** [comment]
Ok, thank you. I will try it.

As you commented maybe the auth also use encryption so I will need develop both features.
It will take time so don't expect it in 1 or 2 days it could take weeks because I'm also developing iOS library.

I will notify when it is ready.

**Comment by ToysoftInc** [comment]
Ok. I don't need it but would be nice to have auth working.

**Comment by pedroSG94** [comment]
This was related with encryption support not an auth and encryption is already supported.
Closing as inactive.
