### ISSUE TITLE
insert black screen for streaming as video

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/RootEncoder#1305]
hi pedro,

I am using display service and displayBase to capture the screen and send it out to rtsp server. However, I found that the phone get very hot. So i would like to replace with black screen whenever necessary to save battery and lower the temperature. 

I learnt that there is a function muteVideo, but it use the same amount of battery and increase temperature.

May I know is there a way to insert black screen without using too much battery and generating too much heat?

Thanks in advance.

**Comment by pedroSG94** [comment]
Maybe we can try with this:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/DisplayBase.java#L581
This way you can reduce fps when necessary and set normal fps back when you need it.
I think you can use a low value like 2 or 3 fps because you send black screen so you can't see the difference.

Other way could be remove set force render to false to avoid render screen if it is not updated (keep in mind that few servers need receive video and audio so this way maybe produce disconnection if the screen is not updated)

**Comment by lchy12345** [comment]
Thanks so much, but this is not suitable for me.

I can now insert the black screen by streaming a prepared black screen mp4.

However, is it possible to loop the mp4 when the mp4 is finished? I am now using RtspFromFile and FromFileBase to do the streaming.

Thanks in advance

**Comment by pedroSG94** [comment]
Yes, you can use this method to loop:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/FromFileBase.java#L448

**Comment by lchy12345** [comment]
hi pedro,

I have tried the setloopmode but the video seems did not loop.

I called rtspfromfile.prepareVideo and then call rtspfromfile.setLoopMode and then call rtspfromfile.startStream.

May I know if I have done anything wrong?

Thanks so much.

**Comment by pedroSG94** [comment]
Hello,

This should be solved now. Try with app sample adding loop mode and let me know if it is working

**Comment by lchy12345** [comment]
Hi pedro,

Thank you so much. I have tried setting loop mode. 

I found that the seekbar was able to loop if i preparevideo and prepareaudio, but only the audio loop but not the video.

But if I preparevideo only (as my file only contain video), both the seekbar and the video did not loop.

May I know what can I do so work with only video file for looping? Thanks

**Comment by pedroSG94** [comment]
Hello,

Do you have a file to test your cases?
It is working for me with a file that contain video and audio. I will try remove audio and test again

**Comment by lchy12345** [comment]
Dear Pedro,

I am using this black.mp4. I got the problem. Thanks

https://github.com/pedroSG94/RootEncoder/assets/89956234/0caf250d-9782-4ecc-9f00-7c05db2ac74b

**Comment by pedroSG94** [comment]
Hello,

Fixed here:
https://github.com/pedroSG94/RootEncoder/pull/1314

I tested with your video using rtmpfromfile example after add this fix and it is working fine. Remember add loop mode and setOnlyVideo:
```java
    rtmpFromFile.setLoopMode(true);
    rtmpFromFile.getStreamClient().setOnlyVideo(true);
```
here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/filestreamexample/RtmpFromFileActivity.java#L89

Also, I did a full black video but of 20s to test loop:

https://github.com/pedroSG94/RootEncoder/assets/17556876/e8ded5d1-f6d3-4b4b-bee6-4082a7032d6a

And other video of 20s with a count that help you to know if loop work fine

https://github.com/pedroSG94/RootEncoder/assets/17556876/c31bd9c7-2eb4-41be-b3cf-6bdccd37cdb3

**Comment by lchy12345** [comment]
Hi pedro, 

I found it works. thanks so much. 

Now i put the code this way

if (prepare()) {
              button.setText(R.string.stop_button);
              rtspFromFile.setLoopMode(true);
              rtspFromFile.getStreamClient().setOnlyVideo(true);
              rtspFromFile.startStream(etUrl.getText().toString());
              seekBar.setMax(Math.max((int) rtspFromFile.getVideoDuration(),
                      (int) rtspFromFile.getAudioDuration()));
              updateProgress();
            } 

just wanna confirm the setLoopMode and setOnlyVideo should be put before or after prepare()?

But I want to ask is that a must to have prepareaudio even if the mp4 has no sound? coz if I preparevideo only the loop does not work.

Thanks

**Comment by pedroSG94** [comment]
> just wanna confirm the setLoopMode and setOnlyVideo should be put before or after prepare()?

This should works in both cases.

> But I want to ask is that a must to have prepareaudio even if the mp4 has no sound? coz if I preparevideo only the loop does not work.

This shouldn't be necessary so I will check it

**Comment by pedroSG94** [comment]
> But I want to ask is that a must to have prepareaudio even if the mp4 has no sound? coz if I preparevideo only the loop does not work.

I was testing this with your video and my videos and it is working fine. Do you have this error always? Can you reproduce the problem using my videos?

I only removed this line:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/filestreamexample/RtmpFromFileActivity.java#L243

And added this to the class:
```
rtmpFromFile.setLoopMode(true);
rtmpFromFile.getStreamClient().setOnlyVideo(true);
```

**Comment by lchy12345** [comment]
i can work with my video and your video now. Thank you very much.
