### ISSUE TITLE
RtmpFromFile streaming Video/Audio sync issue

### ISSUE THREAD

**Issue by duyminhnguyen97** [pedroSG94/RootEncoder#1315]
Hi @pedroSG94,

I'm currently working on streaming video file from mobile device to streaming platforms such as Facebook, YouTube, or TikTok,... However, I noticed a problem with syncing video and audio, since audio always goes faster than video, and the video constantly stutter. I tried different bitrates and some modifications but it still happens. What settings and parameters do I have to change to reduce the desync between them? Do you have any idea what caused the desync?
I'm currently using RtmpFromFile v2.3.0, tested with Android studio emulator Pixel 4 API 31 device. Please let me know if you need anything.

Thanks in advance!

**Comment by duyminhnguyen97** [comment]
Hi,

Thank you for your response. Your branch fixed the sync problem for me perfectly! However, the stutter problem is still there. Do you have any idea what caused this? Will it be an internet problem or a config problem?
Here is a video of the stream I tested. Sometimes (rarely) it can go smooth like [this](https://www.dropbox.com/scl/fi/wz78drs2w4il6u7zmzhmc/2023-10-31-12-45-21.mkv?rlkey=zbdqi5bmqoigvq723ai0dd6jk&dl=0) but most of the time it will be flashing and stuttering like [this](https://www.dropbox.com/scl/fi/l4352k79wfecjv2449xtw/2023-10-31-16-34-03.mkv?rlkey=vossixbpg6vcbaj5o1nucsaab&dl=0)
I tested with Android studio emulator Pixel 4 API 31 Android 12. I set the video bitrate 3500 * 1024 and the audio bitrate 128 * 1024

Thanks in advance!

**Comment by pedroSG94** [comment]
The audio error sometimes happens for use google audio encoder (the only one on fews emulators):
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java#L437
If you are streaming to YouTube try with normal delay instead of low/ultralow delay. This can help you solve the issue.

If you can reproduce the problem in other platform. Let me know which platform and stream configuration in the platform.

**Comment by duyminhnguyen97** [comment]
I'm encountering a very odd case with your [fix/fromfile-video-no-audio](https://github.com/pedroSG94/RootEncoder/tree/fix/fromfile-video-no-audio) branch. This time I tested my app with a physical mobile device (Samsung A50 Android 11). I tried with a random video I recorded previously (mp4, 1080p). The stream worked fine (still a little bit stutter) until a few hours ago. At first, the loop mode seemed to break when it cut out the last few seconds of my video (a 2mins video was cut for 10s, and a 10mins video was cut for over a minute). I tried again now without the loop mode. Then it didn't stream any more. I opened the logcat and I saw sometimes the AudioDecoder said "end of file", sometimes it's the VideoDecoder, even if I was just started streaming (sometimes after a few second). Here is an example [logcat](https://www.dropbox.com/scl/fi/lul4vp3o9p58viehl7397/2023-11-01-17-17-52.txt?rlkey=0etxmp41zuw2zjoln749z1x9q&dl=0). This video is 2mins long and the stream ended after 30s, then the VideoDecoder log "end of file". Can you help me with this problem? :(

**Comment by pedroSG94** [comment]
Hello,

Can you share me a video example with this problem to test it?

**Comment by duyminhnguyen97** [comment]
Hi,

While recording examples for you I found out that this bug only happened with 1080p videos! I tried with 720p video and it works perfectly fine. At first, I tested with [this](https://www.youtube.com/watch?v=F0lowv3DyfI&t=56s) video but other 1080p videos also faced the same problem. When I downgraded this video to 720p it streamed normally. Can you fix this problem since most recorded videos nowadays are in 1080p

Thanks in advance!!!

**Comment by pedroSG94** [comment]
Hello,

I detected an error related with your case and I fixed it in the last commit:
https://github.com/pedroSG94/RootEncoder/commit/ed8c6d9debe19a8ae4eea04ca29cba4b5c0bf763
Please, get last commit and use from file rtmp example to test if the problem is solved. If not, let me know how to reproduce the case using my app example and share me a video if you can't reproduce it using that video.

I was using the video that you suggested but I downloaded it in 1080p using this web:
https://www.freemake.com/es/free_video_downloader_perfect/

**Comment by pedroSG94** [comment]
About the audio problem. I did a branch for it:
https://github.com/pedroSG94/RootEncoder/pull/1321
Test it and let me know if this help with the error

**Comment by duyminhnguyen97** [comment]
Hi,

The problem with 1080p is now fixed! However, the "end of file" problem is still there. You can test with both 1080p and 720p of the video above while streaming on YouTube. Sometimes "end of file" problem happens with audio ([logcat](https://www.dropbox.com/scl/fi/chsmchr7iydqgke3qh3ms/2023-11-02-11-21-05-1080p.txt?rlkey=qygqmmfb8fng8bul7z96r65fs&dl=0)), sometimes with video ([logcat]()https://www.dropbox.com/scl/fi/cb89vvyujhsxt2irbi6a6/2023-11-02-11-21-05-1080p-video.txt?rlkey=i6rsk25nf9udhhcddq3aylo61&dl=0). The loop also break because of the "end of file" problem since it triggers the loop right away (it continues restarting the video after a few seconds).

**Comment by pedroSG94** [comment]
Hello,

I can't reproduce the error in the app example. Can you tell me how to reproduce it using app example?
Share me a video and tell me steps to reproduce it.

Also, test the branch about the audio problem to know if this solve the error

**Comment by pedroSG94** [comment]
Closing as inactive.
