### ISSUE TITLE
Create dynamic Camera classes

### ISSUE THREAD

**Issue by Ernovation** [pedroSG94/RootEncoder#1324]
Hi Pedro,

As discussed in #1319 it would be useful to have a DynamicCamera(2) class where the protocol can be set after the object has been initialized. The appropriate StreamBaseClient can be instantiated based on the URL.
Some methods may have to be called before connecting (e. g. prepareAudio() and prepareVideo()). So it may be better to first set the URL, and then connect later. 

You wrote in #1319 :

> Maybe we can solve it creating a common module and add it as dependency in all protocols.

I think that is a good idea. I would like to have RtmpClient, RtspClient and SrtClient implement some interface so that we can refer to it, and this interface should then be in this common module. I first thought that we could put this interface in the library module, but since the library module refers to each protocol, that would make each protocol dependent on each other protocol, and create a circular dependency between modules, which we indeed should prevent.

I also think that this change would make the implementation incompatible with older versions, so this would require a bump in the version.

I would not mind working on this, but I think it would be better if you would at least make an initial setup of the new module, so that it will be as you like it. Perhaps in a new git branch.

**Comment by pedroSG94** [comment]
Hello,

This is the branch with a common module:
https://github.com/pedroSG94/RootEncoder/pull/1323
I'm moving all common classes to reduce duplicated code

You can work on this branch and create a PR to merge with the branch and after that merge with master.

**Comment by pedroSG94** [comment]
I was doing tests with jitpack compilation and finally it is working so we don't need to worry about it anymore
