### ISSUE TITLE
Replacing Android Camera Output with OBS Input

### ISSUE THREAD

**Issue by Kittyxox** [pedroSG94/RootEncoder#1327]
Hello,

I am interested in using your library for a specific use case. I want to replace the output of my Android camera application with the input from OBS. For instance, if I play a video in OBS, I want the same video to be streamed in my Android camera application.

Is it possible to achieve this functionality using your library?
If yes, could you tell me the steps!?

**Comment by pedroSG94** [comment]
Hello,

If you mean stream to an Android device using OBS, get that stream and re stream it using this library. No, it is not possible.

To do this you need to implement a media server in the device, get video/audio frames from that media server and stream it again but I have no plan to develop a media server in this library because this library is only oriented to be a encoder (basically only **send** video/audio)

**Comment by Kittyxox** [comment]
Using rtmp protocol, is it not possible to do that? I think your library does that right? Like through RTMP , pushing obs stream output to android camera input

**Comment by pedroSG94** [comment]
My library send Video/Audio using rtmp but no receive video/audio
I assume that you want stream using OBS with rtmp to your device but if you want receive rtmp from OBS you need to implement how to receive it. Basically it is a media server.

**Comment by pedroSG94** [comment]
If you can implement the way to receive video/audio from OBS you can use rtmp module to send it using my library but the way to implement how to receive video/audio should be developed by yourself

**Comment by Kittyxox** [comment]
Oh i see, Alright. I can pay you to do that part. Are you on telegram? We can talk about it.

**Comment by Kittyxox** [comment]
It doesn't have to be OBS to android camera.
But It can be my device gallery video files stream in android camera.

**Comment by pedroSG94** [comment]
If you want stream a video/audio file you can use FromFileRtmp. You can test it in the app example using From file RTMP activity

**Comment by Kittyxox** [comment]
Yeah but it still sends the stream output from android device to other apps. But im expecting to receive video and audio input from obs.
I can pay you to implement this. Can we talk in telegram?
