### ISSUE TITLE
Could not find encoder-2.1.8.aar (com.github.pedroSG94.rtmp-rtsp-stream-client-java:encoder:2.1.8).

### ISSUE THREAD

**Issue by kasterlod** [pedroSG94/RootEncoder#1328]
Hello, I can't see any tags, and I got an error while trying to build the app

ould not resolve all files for configuration ':app:stagingReleaseRuntimeClasspath'.
   > Failed to transform encoder-2.1.8.aar (com.github.pedroSG94.rtmp-rtsp-stream-client-java:encoder:2.1.8) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find encoder-2.1.8.aar (com.github.pedroSG94.rtmp-rtsp-stream-client-java:encoder:2.1.8).
        Searched in the following locations:
            https://www.jitpack.io/com/github/pedroSG94/rtmp-rtsp-stream-client-java/encoder/2.1.8/encoder-2.1.8.aar

https://www.jitpack.io/com/github/pedroSG94/rtmp-rtsp-stream-client-java/encoder/2.1.8/encoder-2.1.8.aar -> not found

cc @pedroSG94 🙏

**Comment by pedroSG94** [comment]
Hello,

I assume that you are compiling this gradle:
```gradle
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.8'
```
Try this:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.1.8'
```
If you only want encoder module you can replace rtplibrary to encoder or other module name required

**Comment by kasterlod** [comment]
thank you so much, perfect!
