### ISSUE TITLE
Why AmfLongString bodySize is same as AmfString? 

### ISSUE THREAD

**Issue by KittenBall** [pedroSG94/RootEncoder#1332]
https://github.com/pedroSG94/RootEncoder/blob/8f034fce93b5a176448ca0a6c2e83f44d1ec9701/rtmp/src/main/java/com/pedro/rtmp/amf/v0/AmfLongString.kt#L31

The length of long string should be + 4 ? 

Let me know if i wrong, thank you.

**Comment by pedroSG94** [comment]
Yes, you are right.
Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/2cdd1c1948b34dec4088cc091d70667629094f28

**Comment by KittenBall** [comment]
Thanks
