### ISSUE TITLE
Failed to resolve: com.github.pedroSG94.rtmp-rtsp-stream-client-java:encoder:2.2.6

### ISSUE THREAD

**Issue by UmairAhmed85** [pedroSG94/RootEncoder#1333]
Added this 
implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6' in app level gradle file.
No matter which version i use, whether it be 2.1.9 or 2.2.6, i am always getting this below error.  What could be the cause and how can I fix it.
----------------------------------------
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.pedroSG94.rtmp-rtsp-stream-client-java:encoder:2.2.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/pedroSG94/rtmp-rtsp-stream-client-java/encoder/2.2.6/encoder-2.2.6.pom
       - https://jcenter.bintray.com/com/github/pedroSG94/rtmp-rtsp-stream-client-java/encoder/2.2.6/encoder-2.2.6.pom
       - https://repo.maven.apache.org/maven2/com/github/pedroSG94/rtmp-rtsp-stream-client-java/encoder/2.2.6/encoder-2.2.6.pom
       - https://jitpack.io/com/github/pedroSG94/rtmp-rtsp-stream-client-java/encoder/2.2.6/encoder-2.2.6.pom
     Required by:
         project :app
         project :app > com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.2.6

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ----------------------------------------
 
 Included this block as well inside app level build.gradle file
 
 allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}

**Comment by cryinrain69** [comment]
> Hello,
> 
> Try again with this gradle:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6'
> ```
> 
> I think that jitpack failed to compile olders versions after change repository name and I need request jitpack to compile it again. I tested that version and it is working for me now.

I had the same problem as @UmairAhmed85 .
I tried both
`implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6'`
and
`implementation 'com.github.pedroSG94.RootEncoder:library:2.3.2'`
it gives me an error not found.

**Log sync gradle:**

![rtmp-build-error](https://github.com/pedroSG94/RootEncoder/assets/55587145/ae8e396f-9974-4058-b694-b02fe3da1c88)

**Comment by pedroSG94** [comment]
Hello,

Your error seems different.

Check that you added jitpack repository correctly.
Also, try to compile common module using version 2.3.2 instead of library module to discard problems with dependencies

**Comment by Caaaaaarl** [comment]
I have same question.Try to modify your gradle version in your project.My gradle version is 8.0.0;gradle plug version is 8.1.1 and JDK version 17.

**Comment by pedroSG94** [comment]
Hello,

Which library version are you using? 
Did you try to compile the library in a new project using the last library version and last Android Studio?

**Comment by Caaaaaarl** [comment]
Hello,thanks for your response,

I using library version is "2.4.4",and Android Studio version is "Android Studio Giraffe | 2022.3.1 Patch 1".
Also compile the library in a new project and it is worked.

**Comment by Caaaaaarl** [comment]
Hello,

You're right, the issue seems to stem from conflicts with other dependencies in my project. 

However, when I tried to replicate all dependencies into a new project, it failed to compile due to the complexity and multitude of dependencies. I didn't proceed to identify which dependency caused the issue. 

Anyway, I can successfully use your library after modifying the Gradle version. 

Thank you very much for your prompt response and assistance; your library works perfectly!
