### ISSUE TITLE
Is MediaCodec.BufferInfo‘s size is length, not endIndex ?

### ISSUE THREAD

**Issue by KittenBall** [pedroSG94/RootEncoder#1341]
[https://github.com/pedroSG94/RootEncoder/blob/master/rtmp/src/main/java/com/pedro/rtmp/flv/audio/AacPacket.kt#L79](url)
```kotlin
header[1] = Type.RAW.mark
buffer = ByteArray(info.size - info.offset + header.size)

byteBuffer.get(buffer, header.size, info.size - info.offset)
```

I think the correct code is

```kotlin
header[1] = Type.RAW.mark
buffer = ByteArray(info.size + header.size)
buffer.position(info.offset)
byteBuffer.get(buffer, header.size, info.size)
```

I have not test, let me know if I wrong, thank you !

**Comment by pedroSG94** [comment]
Hello,

You are right, but it is already done by MediaCodec but maybe I should do it anyway for sanity.
I will need to apply this to all protocols and packets

**Comment by KittenBall** [comment]
Yes, most of time, MediaInfo's offset is 0, so this problem does not appear.

**Comment by pedroSG94** [comment]
This should be solved here:
https://github.com/pedroSG94/RootEncoder/pull/1344

**Comment by KittenBall** [comment]
Thank you very much.
