### ISSUE TITLE
setLogs()  removed?

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/RootEncoder#1348]
I want to disable logs with version 2.3.2
`rtmpCamera1.setLogs(false);`
no longer works...

**Comment by pedroSG94** [comment]
Hello,

It was moved to streamclient in version 2.3.1. Try with:
```java
rtmpCamera1.getStreamClient().setLogs(false);
```

**Comment by AlexUrrutia** [comment]
Thanks a lot!
