### ISSUE TITLE
Camera screen black when turn on device after switch off.

### ISSUE THREAD

**Issue by RedwanSharafatKabir** [pedroSG94/RootEncoder#1369]
During live streaming when I switch off the mobile and reopen, the camera doesn't show any preview or record nothing and stream closed automatically.

 How to solve this issue?

**Comment by pedroSG94** [comment]
Hello,

I don't know about your code implementation but if you don't use a service that is expected because the Android view lifecycle works like that.
If you want avoid that you need use a service. You have examples here:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/backgroundexample
This example stream in background until you press stop button. You can modify the moment to stop yourself

**Comment by RedwanSharafatKabir** [comment]
> Hello,
> 
> I don't know about your code implementation but if you don't use a service that is expected because the Android view lifecycle works like that. If you want avoid that you need use a service because if you lock the device, the activity go to background destroying the view used for preview and the stream class (It is related with Android lifecycle). You have examples here: https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/backgroundexample This example stream in background until you press stop button (no matter if you close activity, app, lock device, etc). You can modify the moment to stop yourself

Thanks for your reply. This background service supports RTP, Can I stream in RTMP in background service?

**Comment by pedroSG94** [comment]
That is only the name. That service support RTMP and RTSP

**Comment by RedwanSharafatKabir** [comment]
One more thing. I am trying to stream text and images over screen. To do so, I created a function in RTPService and called it from BackgroundActivity.

fun addOverlayFilter(baseFilterRender: BaseFilterRender){
    camera2Base?.glInterface?.addFilter(baseFilterRender)
    Log.i("opengl_overlay", "Accepted")
  }

Calling this function from BackgroundActivity and passing a textview as androidViewFilterRender. But it doesn't show anything on the stream screen.

What would be the issue?

**Comment by RedwanSharafatKabir** [comment]
> One more thing. I am trying to stream text and images over screen. To do so, I created a function in RTPService and called it from BackgroundActivity.
> 
> fun addOverlayFilter(baseFilterRender: BaseFilterRender){ camera2Base?.glInterface?.addFilter(baseFilterRender) Log.i("opengl_overlay", "Accepted") }
> 
> Calling this function from BackgroundActivity and passing a textview as androidViewFilterRender. But it doesn't show anything on the stream screen.
> 
> What would be the issue?

One more thing. I am trying to stream text and images over screen. To do so, I created a function in RTPService and called it from BackgroundActivity.

fun addOverlayFilter(baseFilterRender: BaseFilterRender){
camera2Base?.glInterface?.addFilter(baseFilterRender)
Log.i("opengl_overlay", "Accepted")
}

Calling this function from BackgroundActivity and passing a textview as androidViewFilterRender. But it doesn't show anything on the stream screen.

What would be the issue?

**Comment by RedwanSharafatKabir** [comment]
> That is only the name. That service support RTMP and RTSP

One more thing. I am trying to stream text and images over screen. To do so, I created a function in RTPService and called it from BackgroundActivity.

fun addOverlayFilter(baseFilterRender: BaseFilterRender){
camera2Base?.glInterface?.addFilter(baseFilterRender)
Log.i("opengl_overlay", "Accepted")
}

Calling this function from BackgroundActivity and passing a textview as androidViewFilterRender. But it doesn't show anything on the stream screen.

What would be the issue?

**Comment by pedroSG94** [comment]
When are you calling that method?
Did you try to call it after start stream? After this line
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L51

**Comment by RedwanSharafatKabir** [comment]
> When are you calling that method? Did you try to call it after start stream? After this line https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L51

It works when I call it in a click event by button. But now working in onCreate method without any button click.

**Comment by pedroSG94** [comment]
When are you calling that method?
Did you try to call it after start stream? After this line
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L53

**Comment by RedwanSharafatKabir** [comment]
> When are you calling that method? Did you try to call it after start stream? After this line https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L53

Yes I am calling this function after start stream. But when I turn off mobile and turn on again the "androidViewFilterRender" is no more visible.

**Comment by pedroSG94** [comment]
That is because the reference to the view in the filter is already death. You need to update the view in the filter after turn on the mobile.
```java
androidViewFilterRender.setView(view);
```

This is related to the lifecycle of the views in Android. When an activity is destroyed, the layout used in the activity is released and you lose all references to that views so you need wait until the layout is inflated again and set the view with the new reference.

**Comment by RedwanSharafatKabir** [comment]
> That is because the reference to the view in the filter is already death. You need to update the view in the filter after turn on the mobile.
> 
> ```java
> androidViewFilterRender.setView(view);
> ```
> 
> This is related to the lifecycle of the views in Android. When an activity is destroyed, the layout used in the activity is released and you lose all references to that views so you need wait until the layout is inflated again and set the view with the new reference. Of course, this apply to anything that can contain a layout. Activity, Fragment, Widget, etc You need set the view to the filter when the view is ready to work according with the Android lifecycle

I am doing the below code in onResume() method. But it still not working when the device is reopened.

Code:
val androidViewFilterRender = AndroidViewFilterRender()
androidViewFilterRender.view = findViewById(R.id.productInfoOverlay)  
androidViewFilterRender.setScale(70F, 12F)
androidViewFilterRender.setPosition(TranslateTo.CENTER)
service?.addOverlayFilter(androidViewFilterRender)

**Comment by pedroSG94** [comment]
Do you have a black rectangle instead of the view or you can't see anything?
Can you share me a screen shoot?

**Comment by pedroSG94** [comment]
Are you using replaceView like here after set the filter?:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L115
If that is the case. This method replace a GlInterface for other GlInterface and each GlInterface contain filters that can't be shared because it is binded to the context of that GlInterface so you need set the filter again after change it. For example:
```java
val filter = getOldFilter() //create a method to get filters currently used
//each time this method is called the library is forced to release all filters related to old GlInterface 
// so it is similar to call rtmpCamera2.glInterface.clearFilters()
rtmpCamera2.replaceView(openGlView)
rtmpCamera2.glInterface.setFilter(filter)
```

To fix the problem you can call set filter after replaceView. I will add a method to do it automatically in next version

**Comment by RedwanSharafatKabir** [comment]
> Are you using replaceView like here after set the filter?: https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L115 If that is the case. This method replace a GlInterface for other GlInterface and each GlInterface contain filters that can't be shared because it is binded to the context of that GlInterface so you need set the filter again after change it. For example:
> 
> ```java
> val filter = getOldFilter() //create a method to get filters currently used
> //each time this method is called the library is forced to release all filters related to old GlInterface 
> // so it is similar to call rtmpCamera2.glInterface.clearFilters()
> rtmpCamera2.replaceView(openGlView)
> rtmpCamera2.glInterface.setFilter(filter)
> ```
> 
> To fix the problem you can call set filter after replaceView. I will add a method to do it automatically in next version

I tried this: 

service?.setView(binding.surfaceView)
|
|
val androidViewFilterRender = AndroidViewFilterRender()
androidViewFilterRender.view = findViewById(R.id.productInfoOverlay)
androidViewFilterRender.setScale(70F, 12F)
androidViewFilterRender.setPosition(TranslateTo.CENTER)

service?.addOverlayFilter(androidViewFilterRender) >>>> this line refers to this line in "RtpService" class - camera2Base?.glInterface?.addFilter(androidViewFilterRender)

**Comment by pedroSG94** [comment]
I did my implementation working with RTP service example of my app. 
- Get last master commit of the project.
- Add this method to RtpService:
```kotlin
  fun setFilter(filter: BaseFilterRender) {
    genericCamera2.glInterface.setFilter(filter)
  }
```
- Add filter to the stream in the startPreview method of BackgroundActivity (just replace the method for the next code)
```kotlin
  private fun startPreview() {
    if (binding.surfaceView.holder.surface.isValid) {
      binding.surfaceView.setAspectRatioMode(AspectRatioMode.Adjust)
      service?.setView(binding.surfaceView)
      val view = findViewById<View>(R.id.b_start_stop)
      val androidViewFilterRender = AndroidViewFilterRender()
      androidViewFilterRender.view = view
      androidViewFilterRender.setScale(70F, 12F)
      androidViewFilterRender.setPosition(TranslateTo.CENTER)
      service?.setFilter(androidViewFilterRender)
    }
    //check if onPreview and if surface is valid
    if (service?.isOnPreview() != true && binding.surfaceView.holder.surface.isValid) {
      service?.startPreview()
    }
  }
```

Compile the app and you will see that the filter add the button to stream. It is working blocking the device. You can check it in this video example recorded from ffplay result as player:

[Grabación de pantalla desde 2023-12-31 12-13-19.webm](https://github.com/pedroSG94/RootEncoder/assets/17556876/ce7f0fd4-0a73-4500-b37b-ccb2333c154c)

**Comment by RedwanSharafatKabir** [comment]
> I did my implementation working with RTP service example of my app.
> 
> * Get last master commit of the project.
> * Add this method to RtpService:
> 
> ```kotlin
>   fun setFilter(filter: BaseFilterRender) {
>     genericCamera2.glInterface.setFilter(filter)
>   }
> ```
> 
> * Add filter to the stream in the startPreview method of BackgroundActivity (just replace the method for the next code)
> 
> ```kotlin
>   private fun startPreview() {
>     if (binding.surfaceView.holder.surface.isValid) {
>       binding.surfaceView.setAspectRatioMode(AspectRatioMode.Adjust)
>       service?.setView(binding.surfaceView)
>       val view = findViewById<View>(R.id.b_start_stop)
>       val androidViewFilterRender = AndroidViewFilterRender()
>       androidViewFilterRender.view = view
>       androidViewFilterRender.setScale(70F, 12F)
>       androidViewFilterRender.setPosition(TranslateTo.CENTER)
>       service?.setFilter(androidViewFilterRender)
>     }
>     //check if onPreview and if surface is valid
>     if (service?.isOnPreview() != true && binding.surfaceView.holder.surface.isValid) {
>       service?.startPreview()
>     }
>   }
> ```
> 
> Compile the app and you will see that the filter add the button to stream. It is working blocking the device. You can check it in this video example recorded from ffplay result as player:
> 
>  Grabacion.de.pantalla.desde.2023-12-31.12-13-19.webm

It works fine now. Previously I used addFilter() instead of setFilter() function.

Thanks, man. You've consistently been very helpful.

**Comment by pedroSG94** [comment]
Closing issue then. You can open other issue if you have any problem
