### ISSUE TITLE
RTS stream url pattern failed

### ISSUE THREAD

**Issue by tangmingxing1988** [pedroSG94/RootEncoder#1372]
I have the following rts push url
`srt://push.domain.com:1105?streamid=#!::h=push.domain.com,r=/live/stream,m=publish`

and it failed with the error
`Endpoint malformed, should be: srt://ip:port/streamid`

I think the url is legal, why it failed?

**Comment by pedroSG94** [comment]
Hello,

The url in the library should be like this:
 srt://push.domain.com:1105/#!::h=push.domain.com,r=/live/stream,m=publish
