### ISSUE TITLE
IPv4 and IPv6

### ISSUE THREAD

**Issue by freespirit83xyz** [pedroSG94/RootEncoder#1380]
Hello,

is possible to force to use IPv4?
I tested your project (Really great!) on a RealMe RMX3771 with Android 13. All went great but at a point rtsp server start to use IPv6. In This way the videowall that has to play the stream can't connect.
The strange thing is that 1 hour before it used always IPv4.
So my question is: is possible to force to init the server with IPv4? I tried to pass rtsp address to startStream() but nothing happened.

**Comment by pedroSG94** [comment]
Hello,

Yes, you can do it but you will need modify the project a bit. You can import the module to your project or just copy classes and add the dependencies of the module.

You only need modify this method:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L296
To:
```kotlin
  private fun List<NetworkInterface>.findAddress(): List<String?> = this.asSequence()
    .map { addresses -> addresses.inetAddresses.asSequence() }
    .flatten()
    .filter { address -> !address.isLoopbackAddress }
    .map { it.hostAddress }
    .filter { address -> address?.contains(":") == false }
    .toList()
```
Or you can compile an old library version which doesn't support Ipv6:
```gradle
  implementation 'com.github.pedroSG94:RTSP-Server:1.1.9'
  implementation 'com.github.pedroSG94.RootEncoder:library:2.3.0'
```

I will mark this issue as feature to the a method to force it without modify the project but for now you will need use this way.

**Comment by freespirit83xyz** [comment]
Thanks, now is perfect

**Comment by pedroSG94** [comment]
Closing as solved here:
https://github.com/pedroSG94/RTSP-Server/commits/master/
