### ISSUE TITLE
External UVC Camera support

### ISSUE THREAD

**Issue by himini80** [pedroSG94/RootEncoder#1392]
Hello.
I want to connect USB Camera and stream.
How can I do it?

**Comment by pedroSG94** [comment]
Hello,

You can try this project (unmaintained so I can't help you if you have problems):
https://github.com/pedroSG94/Stream-USB-test
Or follow this post but instead of use CameraX, use a library that allow USB Camera connection:
https://github.com/pedroSG94/RootEncoder/issues/1389

**Comment by pedroSG94** [comment]
Already solved here: https://github.com/pedroSG94/RTSP-Server/issues/110
