### ISSUE TITLE
RTSPS and self-signed certificates

### ISSUE THREAD

**Issue by brian7704** [pedroSG94/RootEncoder#1395]
I'm using RootEncoder in my app and can stream to MediaMTX using rtsp and rtsps using Let's Encrypt certificates. However if I try to stream using rtsps to a MediaMTX server with self signed certificates I get this error in logcat

```javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found```

I understand the error and why it happens. My question is, is there a way to prompt the user about the security risk and have them choose to continue anyway, kind of like web browsers do?

I also noticed some unexpected behavior when using Let's Encrypt certificates. Everything worked as expected when I connected to rtsps://my_domain.com:8322/my_stream. Then I connected using rtsps://my_local_ip:8322/my_stream and that also worked. Maybe I'm misunderstanding something but I would have expected an error that the url's hostname doesn't match the certificate's hostname. But it seems like it's just checking the certificate issuer and possibly the expiration date.

**Comment by brian7704** [comment]
Thanks for your help, I'll try to modify the library like you suggested.

**Comment by pedroSG94** [comment]
I'm currently adding a method for it. If you can wait like 30min I can give you a gradle to compile the project with the new method to support it

**Comment by brian7704** [comment]
Thank you, I'd be happy to test it when you're ready.

**Comment by pedroSG94** [comment]
This is the gradle
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:f7c1abf917'
```

You can add your certificate like this:
```kotlin
rtmpCamera2.getStreamClient().addCertificates(arrayOf(AcceptAllCertificates()))
```

AcceptAllCertificates is a class created for me to auto accept all certificates. Load your own certificate as explained in the previous stackoverflow post is recommended:
https://stackoverflow.com/a/24520834

**Comment by brian7704** [comment]
Thanks! I will test it as soon as possible and let you know how it goes.

**Comment by brian7704** [comment]
I was able to get it to work using the gradle you gave me and the following code. I was able to connect to my MediaMTX server with a self signed cert and I got no errors. Thanks for the quick response!

```
try {
    Log.d(LOGTAG, getFilesDir().getAbsolutePath());
    KeyStore keyStore = KeyStore.getInstance("PKCS12");
    FileInputStream caFile = new FileInputStream(getFilesDir().getAbsolutePath() + "/my_cert.p12");
    keyStore.load(caFile, "my_password".toCharArray());

    TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
    trustManagerFactory.init(keyStore);

    SSLContext sslctx = SSLContext.getInstance("TLS");
    sslctx.init(null, trustManagerFactory.getTrustManagers(), new SecureRandom());

    rtspCamera2.getStreamClient().addCertificates(trustManagerFactory.getTrustManagers());
    
} catch (Exception e) {
    Log.e(LOGTAG, e.getMessage());
}
```
