### ISSUE TITLE
No video when streaming in a background service and app is minimized

### ISSUE THREAD

**Issue by brian7704** [pedroSG94/RootEncoder#1400]
My app can stream from a service when it is in the foreground. However if I turn off the screen or switch to another app the video will be blank but audio still streams.  Any ideas on how to troubleshoot that?

**Comment by pedroSG94** [comment]
Hello,

Did you test using background example of my app sample?

**Comment by brian7704** [comment]
Yes I was previously able to compile the sample app and it does send video when the app is not in the foreground. However I'm confused about [ActivityBackgroundBinding in BackgroundActivity.kt](https://github.com/pedroSG94/RootEncoder/blob/45b332af0a080cc827b6f848bd90e579269ea603/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L29). I can't find where that comes from.

**Comment by pedroSG94** [comment]
Hello,

I'm glad you solved this.

> Yes I was previously able to compile the sample app and it does send video when the app is not in the foreground. However I'm confused about [ActivityBackgroundBinding in BackgroundActivity.kt](https://github.com/pedroSG94/RootEncoder/blob/45b332af0a080cc827b6f848bd90e579269ea603/app/src/main/java/com/pedro/streamer/backgroundexample/BackgroundActivity.kt#L29). I can't find where that comes from.

ActivityBackgroundBinding is a link to the layout generated using viewbinding. Maybe I should remove viewbinding from the app and use a more recent way to do it or the classic one.
