### ISSUE TITLE
Camera preview image not upright if app started in landscape

### ISSUE THREAD

**Issue by kenle** [pedroSG94/RootEncoder#1419]
**Describe the bug**
Hi @pedroSG94 ,

The preview camera image is rotated 90 degrees if the app starts while the phone is in landscape orientation.  In the rotation example this is rectified if the phone is rotated at least once, however in my app I lock my user to landscape mode so this cannot be rectified.

**To Reproduce**
1. Start RootEncoder example app while phone is in landscape
2. Choose Rotation example
3. The image is 90 degrees (not upright)

**Expected behavior**
Image should be properly rotated upright regardless of which orientation the phone starts the app in.

**Screenshots**
![Screenshot_20240305_064418](https://github.com/pedroSG94/RootEncoder/assets/47367/e8ded94c-3267-4dcd-9e4f-e4e98d69f1e5)

**Smartphone (please complete the following information):**
 - Library version 2.3.8
 - Device: Galaxy A15
 - OS: Android 13
 - Class used GenericStream, Camera2Source

**Additional context**

**Comment by pedroSG94** [comment]
Hello,

Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/19b7feb79318da86d457292fdfd42130f3f4a75a
https://github.com/pedroSG94/RootEncoder/commit/aa2ed32f5bbdfd240d93582ac2be12fb9e0a6074

I will upload a version with the fix soon.

**Comment by kenle** [comment]
Again, thank you @pedroSG94 .

Based on looking at your changes in Rotation Example's CameraFragment class, I was able to edit my code to properly rotate the image.  

Since I only have access to a context object I tried 
```
genericStream.setConfig(context.getResources().getConfiguration(), context) 
```
but my compiler was giving errors.  So I used the code below slightly similar to setConfig.

My question is, would it be appropriate to build this into the GenericStream constructor so the user does not have to set this up?  The context is passed into the GenericStream constructor so the code below is possible.  Or perhaps your intent of GenericStream is for the user to be able to manually set the orientation with setOrientation?

RtmpCamera1, RtmpCamera2 was nice because the orientations worked right out of the box without the extra setup.

Lastly, the onOrientationChanged callback is called quite often, for any small phone movement it is triggered, I'm not sure if calling getCameraOrientation and setOrientation many times is inefficient?  If it is efficient then the code should be ok.

Thank you so much,
- Ken

```java
        if(orientationEventListener == null) {
                 orientationEventListener = new OrientationEventListener(myApplicationContext) {
                @Override
                public void onOrientationChanged(int orientation) {
                    int cameraOrientation = CameraHelper.getCameraOrientation(myApplicationContext);
                    boolean isReversed = cameraOrientation == 180 || cameraOrientation == 270;
                    boolean isPortrait = CameraHelper.isPortrait(myApplicationContext);
                    if(!isPortrait) {
                        if(isReversed) {
                            genericStream.setOrientation(90);
                        } else {
                            genericStream.setOrientation(270);
                        }
                    } else {
                        if(isReversed) {
                            genericStream.setOrientation(180);
                        } else {
                            genericStream.setOrientation(0);
                        }
                    }
                }
            };

            orientationEventListener.enable();
```

**Comment by pedroSG94** [comment]
Hello,

> My question is, would it be appropriate to build this into the GenericStream constructor so the user does not have to set this up? The context is passed into the GenericStream constructor so the code below is possible. Or perhaps your intent of GenericStream is for the user to be able to manually set the orientation with setOrientation?

Yes, this is possible
Maybe I should remove setConfig method and use add a method to indicate if you want auto handle orientation and do it internally.



> Lastly, the onOrientationChanged callback is called quite often, for any small phone movement it is triggered, I'm not sure if calling getCameraOrientation and setOrientation many times is inefficient? If it is efficient then the code should be ok.

This should be a problem because you are not doing a high requirement work but I should optimize it a bit. This can be avoided like this:
```java
        if(orientationEventListener == null) {
                 int currentOrientation = -1;
                 orientationEventListener = new OrientationEventListener(myApplicationContext) {
                @Override
                public void onOrientationChanged(int orientation) {
                    //avoid call it if the orientation is not changed
                    if (currentOrientation == orientation) return;
                    else currentOrientation = orientation;
                    int cameraOrientation = CameraHelper.getCameraOrientation(myApplicationContext);
                    boolean isReversed = cameraOrientation == 180 || cameraOrientation == 270;
                    boolean isPortrait = CameraHelper.isPortrait(myApplicationContext);
                    if(!isPortrait) {
                        if(isReversed) {
                            genericStream.setOrientation(90);
                        } else {
                            genericStream.setOrientation(270);
                        }
                    } else {
                        if(isReversed) {
                            genericStream.setOrientation(180);
                        } else {
                            genericStream.setOrientation(0);
                        }
                    }
                }
            };

            orientationEventListener.enable();
```

**Comment by kenle** [comment]
> Yes, this is possible Maybe I should remove setConfig method and use add a method to indicate if you want auto handle orientation and do it internally.

That sounds like a good idea.

> This shouldn't be a problem because you are not doing a high requirement work but I should optimize it a bit. This can be avoided like this:
>
> ```java
>                    if (currentOrientation == orientation) return;
>                    else currentOrientation = orientation;
> ```

That looks good as well.

Thanks again @pedroSG94

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/0c042f53514e3f4a475c41eded20accc0e216235

Gradle to test:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:0c042f5351'
```

**Comment by kenle** [comment]
Hi @pedroSG94 , that branch worked perfectly.  Thank you.

**Comment by pedroSG94** [comment]
Closing issue as completed. You can open other issue or reopen this one if needed
