### ISSUE TITLE
Is it possible to change the resolution without disconnecting during use?

### ISSUE THREAD

**Issue by James-lyb** [pedroSG94/RootEncoder#1428]
HI ! 
First ,thank you for your project!
Is there a way to switch between landscape and portrait mode, change the resolution of the RTMP stream without disconnecting the socket while using screen pushing（Display RTMP）?
using version : 2.2.6 & 2.3.1

**Comment by pedroSG94** [comment]
Hello,

No, it is not possible.

RTMP protocol need notify resolution and other info in the connection to allow server and player handle with the video/audio data correctly so it is not allowed by the protocol.
You need close and create other stream to change the resolution but you have a way to solve it in server side.

Few servers, allow multi resolution streams (YouTube or Twitch for example). Basically the pusher (this library for example) only send the stream in a high resolution (1080p for example) and the server modify this data it in multiple resolutions (1080p, 720, 480p, etc) that is only the original stream but scaled to the desired configuration allowing the player to connect anyone depend of the requirement on fly. You can try this way

**Comment by James-lyb** [comment]
Hello,
Thank you,I will try it!
