### ISSUE TITLE
Wrong aspect ratio when in portrait mode and app is in background

### ISSUE THREAD

**Issue by brian7704** [pedroSG94/RootEncoder#1435]
**Describe the bug**
While streaming from a service with the device in portrait mode, minimizing the app causes the stream's aspect ratio to be incorrect. Bringing the app back to the foreground fixes the aspect ratio. The problem does not occur when streaming from a service in landscape mode. See the attached screenshots.

**To Reproduce**
1. Stream from a service while holding the device in portrait mode
2. Start viewing the stream
3. Minimize the app
4. See the incorrect aspect ratio in the stream

**Expected behavior**
Aspect ratio should not change

**Screenshots**
Correct aspect ratio when app is in foreground
![vlcsnap-2024-03-13-10h32m45s958](https://github.com/pedroSG94/RootEncoder/assets/19883638/0e3d96ed-1d28-4264-8f0e-e1833774452b)

Incorrect aspect ratio when app is minimized
![vlcsnap-2024-03-13-10h32m47s612](https://github.com/pedroSG94/RootEncoder/assets/19883638/e4a301e1-13bb-461d-a2f7-3495119e57f2)

**Smartphone (please complete the following information):**
 - Library version: 2.4.0
 - Device: Pixel 4a 5G, Galaxy S21, Pixel 6 Pro
 - OS: Tested on Android 11, 13, and 14
 - Media server: MediaMTX 1.6.0
 - Class used: RtspCamera2, RtmpCamera2, and UdpCamera2

**Additional context**
I'm having this problem in my app OpenTAK ICU. You can download the APK from [my repo](https://github.com/brian7704/OpenTAK_ICU/releases/tag/1.4.1) if you'd like to test it.

**Comment by pedroSG94** [comment]
Hello,

Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/9f2178dea0d4fc830f4a73e437b4918f3bfb18d4

You can compile this using this gradle:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:9f2178dea0'
```

I will upload this fix in the next version soon

**Comment by brian7704** [comment]
Thank you for your quick response! Unfortunately when I use that gradle the preview works for about 1 second and then freezes. Then I cannot start streaming as usual. I'm looking at logcat and I see these messages but I'm not sure if they're related to the problem.

```
2024-03-13 15:25:22.515  7477-7565  pentakicu.debu          io.opentakserver.opentakicu.debug    W  Core platform API violation: Ljava/nio/Buffer;->position:I from Landroid/opengl/GLES20; using JNI
2024-03-13 15:25:22.515  7477-7565  pentakicu.debu          io.opentakserver.opentakicu.debug    W  Core platform API violation: Ljava/nio/Buffer;->limit:I from Landroid/opengl/GLES20; using JNI
2024-03-13 15:25:22.515  7477-7565  pentakicu.debu          io.opentakserver.opentakicu.debug    W  Core platform API violation: Ljava/nio/Buffer;->_elementSizeShift:I from Landroid/opengl/GLES20; using JNI
```

**Comment by pedroSG94** [comment]
Hello,

That logcat is not related with your case.
Can you explain me more? What do you mean with the preview freeze?
The stream result freeze or the preview in the android app?

**Comment by pedroSG94** [comment]
I downloaded the app but I don't understand it. How can I test to reproduce it?

**Comment by brian7704** [comment]
When I use this gradle `implementation 'com.github.pedroSG94.RootEncoder:library:9f2178dea0'` the preview in my app freezes about 1 second after I open it. Then I cannot start streaming. When I use version 2.4.0 there is no freezing. [Here ](https://docs.opentakserver.io/OpenTAK_ICU-debug.apk) is a debug build of my app using the `9f2178dea0` gradle so you can see the problem.

**Comment by pedroSG94** [comment]
Fixed here:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:82cf9217b9'
```

**Comment by brian7704** [comment]
Thank you, that fixed the freezing and the aspect ratio problems.
