### ISSUE TITLE
GenericStream only gets FPS 15-20 when set to 30FPS

### ISSUE THREAD

**Issue by kenle** [pedroSG94/RootEncoder#1437]
**Describe the bug**
Hi @pedroSG94 ,

I'm only getting 15 to 20 FPS when using GenericStream, while setting FPS to 30 within prepareVideo.  I tested changing back to RtmpCamera2 and I get 30FPS.  Can you please check if this issue occurs on your side as well?

**To Reproduce**
```
GenericStream genericStream = new GenericStream(context, RtmpConnectionHandler.instance);

genericStream.setFpsListener(new FpsListener.Callback() {
                @Override
                public void onFps(int fps) {
                    System.out.println("FPS: " + fps);
                }
            });

genericStream.getStreamClient().setReTries(10);

genericStream.setVideoCodec(VideoCodec.H265);

boolean prepared = genericStream.prepareAudio(
                                    128 * 1000,
                                    true,
                                    44100,
                                    true,
                                    false
                                )
                && 
               genericStream.prepareVideo(
                                    1920,
                                    1080,
                                    30,
                                    8000000,
                                    maxKeyFrame,
                                    0, 
                                    CodecProfileLevel.HEVCProfileMain,
                                    CodecProfileLevel.HEVCMainTierLevel4);

if(prepared) {
genericStream.startPreview(mySurfaceTexture, 1920, 1080);

genericStream.startRecord(captureFilePath, new RecordController.Listener() {
                    @Override
                    public void onStatusChange(Status status) {
                        if (status == RecordController.Status.RECORDING) {
                        }
                    }
                });
}



```

**Expected behavior**
30FPS

**Smartphone (please complete the following information):**
 - Library version 2.4.3
 - Galaxy A15
 - OS: [e.g. Android13]
 - Class used: GenericStream

**Comment by pedroSG94** [comment]
Hello,

The problem is related with your prepareVideo method. You have the parameters in the wrong order. This is the correct order:
```kotlin
prepareVideo(width: Int, height: Int, bitrate: Int, fps: Int, iFrameInterval: Int,
    rotation: Int, profile: Int, level: Int)
```
But you are doing this:
```kotlin
prepareVideo(width: Int, height: Int, fps: Int, bitrate: Int, iFrameInterval: Int,
    rotation: Int, profile: Int, level: Int)
```
Bitrate and fps are inverted producing this error.
I have this values in a different order than Camera2Base because bitrate is a necessary parameter for StreamBase and fps is optional so this order is necessary to use @JvmOverloads and allow differents prepareVideo parameters in Java code.
I can add a fix in Camera2Base for it, but this will break retro compatibility, so I will not do it for now.

Since you are using kotlin you can also solve it using the method like this:
```kotlin
    genericStream.prepareVideo(
      width = 1920,
      height = 1080,
      fps = 30,
      bitrate = 8000000,
      iFrameInterval = maxKeyFrame,
      rotation = 0,
      profile = CodecProfileLevel.HEVCProfileMain,
      level = CodecProfileLevel.HEVCMainTierLevel4)
```
This last way allow you work with both classes without worry about parameters order

**Comment by kenle** [comment]
Oh ok noted @pedroSG94 !

I fixed the ordering and now I get 30 FPS.

Thank you so much, and I will close this issue.
