### ISSUE TITLE
In Landscape mode, pointing camera downward rotates view 90 degrees

### ISSUE THREAD

**Issue by kenle** [pedroSG94/RootEncoder#1444]
**Describe the bug**
Hi @pedroSG94 , using the new auto rotate feature, when i point the camera downward it rotates the view 90 degrees.  This could be seen in the rotation example as well.

**To Reproduce**
1. Open rotation example in landscape mode, with auto rotate on
2. Point camera downward

**Expected behavior**
Orientation of camera should remain in landscape.

**Smartphone (please complete the following information):**
 - 2.4.3
 - Galaxy A15

**Comment by pedroSG94** [comment]
Hello,

This is fixed here:
https://github.com/pedroSG94/RootEncoder/commit/784c86220e076e49944ae5a53136eca245b42317
Now, the rotation should follow UI device orientation of the app. You can compile the fix using this gradle until next release is uploaded:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:784c86220e'
```

**Comment by kenle** [comment]
Thank you @pedroSG94 !  That fixes the issue.

**Comment by pedroSG94** [comment]
Closing as complete
