### ISSUE TITLE
Not use preview, the aspect ratio of stream will be broken.

### ISSUE THREAD

**Issue by maehata-fairy** [pedroSG94/RootEncoder#1445]
## Describe the bug

Thanks for your excellent work.
I have some case where rtmp streaming breaks the aspect ratio and size using the sample RotationActivity.

![image](https://github.com/pedroSG94/RootEncoder/assets/72180045/3cec9316-a704-45c2-a9bc-40770b656d75)

### Case 1: As in the pure sample code (see Screenshots case1)
- The entire image is displayed with a black border and is displayed small. 

### Case2: surfaceView does not display Preview. (see Screenshots case2)
- The aspect ratio seems to be broken.

### Case3: Show Preview in surfaceView + use CameraHelper.getCameraOrientation for rotate in prepareVideo
- Correct size and aspect ratio

### Verified environment
- Commit: 784c86220e076e49944ae5a53136eca245b42317
- Device: Pixel 7 (Android13)
- Server: mediamtx (running windows 11)
- Viewer: ffplay

```
Case1: (broken size..?)
1. checkout 784c86220e076e49944ae5a53136eca245b42317
2. build (e.g. ./gradlew assembleDebug)
3. click Rotation(include filters)
4. input stream url (e.g. rtmp://xxx.yyy.zzz.aaa:port/test)
5. see case1 (e.g. ffplay rtmp://localhost:port/test)
```

```
Case2: (broken aspect ratio)
1. checkout 784c86220e076e49944ae5a53136eca245b42317
2. comment out  

* CameraFragment.kt

    // surfaceView.holder.addCallback(object: SurfaceHolder.Callback {
    //   override fun surfaceCreated(holder: SurfaceHolder) {
    //     if (!genericStream.isOnPreview) genericStream.startPreview(surfaceView)
    //   }
    //   override fun surfaceChanged(holder: SurfaceHolder, format: Int, width: Int, height: Int) {
    //     genericStream.getGlInterface().setPreviewResolution(width, height)
    //   }
    //   override fun surfaceDestroyed(holder: SurfaceHolder) {
    //     if (genericStream.isOnPreview) genericStream.stopPreview()
    //   }
    // })

3. build (e.g. ./gradlew assembleDebug)
4. click Rotation(include filters)
5. input stream url (e.g. rtmp://xxx.yyy.zzz.aaa:port/test)
6. see case2 (e.g. ffplay rtmp://localhost:port/test)
```

```
Case3: (No problem)
1. checkout 784c86220e076e49944ae5a53136eca245b42317
2. replace rotate.

* CameraFragment.kt

   private fun prepare() {
     val prepared = try {
-      genericStream.prepareVideo(width, height, vBitrate, rotation = rotation) &&
+      genericStream.prepareVideo(width, height, vBitrate, rotation = CameraHelper.getCameraOrientation(activity)) &&

3. build (e.g. ./gradlew assembleDebug)
4. click Rotation(include filters)
5. input stream url (e.g. rtmp://xxx.yyy.zzz.aaa:port/test)
6. see case3 (e.g. ffplay rtmp://localhost:port/test)
```

## Expected behavior
- Reproduce with RtmpCamera2 instead of GenericStream.
- Does not reproduce with RtmpCamera2 of v2.2.7.
- I think it occurred somewhere between v2.2.7 and v2.4.3.

## Screenshots
- Case 1: As in the pure sample code
![image](https://github.com/pedroSG94/RootEncoder/assets/72180045/37d99044-304f-4bb8-a608-9ae8adadd361)

- Case2: surfaceView does not display Preview.
![image](https://github.com/pedroSG94/RootEncoder/assets/72180045/3cec9316-a704-45c2-a9bc-40770b656d75)

- Case3: Show Preview in surfaceView + use CameraHelper.getCameraOrientation for rotate in prepareVideo
![image](https://github.com/pedroSG94/RootEncoder/assets/72180045/5936bef8-625f-4854-9d8e-5eb7dc02164a)

## Smartphone (please complete the following information):
 - Library version [v2.4.3 or commit: 784c86220e076e49944ae5a53136eca245b42317]
 - Device: [Pixel 7]
 - OS: [Android13]
 - Media server [MediaMTX v1.2.0]
 - Class used [GenericStream or RtmpCamera2]

**Comment by pedroSG94** [comment]
Hello,

This should be fixed here:
https://github.com/pedroSG94/RootEncoder/commit/e716ae1a9be2cbe800a0e7911223a68e87678cab

I think tested all cases but let me know if I missed something. I will upload the next version with the fixes soon

**Comment by maehata-fairy** [comment]
Hello,

I immediately checked the operation and confirmed that there were no problems in case 1 and case 2.

In case 1, CameraFragment's `private var rotation` is 0 by default, 
so, I think sample codes assume landscape orientation.
I think it would be easier to use the sample by determining whether it is portrait or landscape when initializing the Fragment and setting it as the initial value.

and In case2, 
after rewriting private var rotation = 90,
I commented out surfaceView.holder.addCallback and confirmed that it was streamed by Fit.

Thank you for your quick response.

**Comment by pedroSG94** [comment]
Hello,


> I think it would be easier to use the sample by determining whether it is portrait or landscape when initializing the Fragment and setting it as the initial value.

Yes, this is an option but I think it is more confuse because the user can open in landscape, rotate to portrait and then start stream. The orientation will be horizontal in this case but If I open in Portrait and start stream the orientation is vertical and this could be confuse to understand.

I did it always horizontal and you can change it in the menu to vertical, this way it is easy to understand that you will stream horizontal until you change it in the menu.
I will keep the current way for this reason.

The error seem fixed. I will close the issue as completed but you can reopen it if you need or open other issue.
Thank you for the report
