### ISSUE TITLE
How to get frame data while pushing stream

### ISSUE THREAD

**Issue by Miles087** [pedroSG94/RootEncoder#1452]
Hello, I want to get yuv data when streaming, I try to create a queue<Frame> to save frames, but when I use this queue in othere place, streaming is broken, just facedetect worked, can't see streaming. 
How can I fix this, Thank you verymuch.
![q1](https://github.com/pedroSG94/RootEncoder/assets/4329440/f1aaad85-35d1-4302-bbb7-4f784f8d1d13)

**Comment by Miles087** [comment]
![Uploading q1.png…]()
gap++

**Comment by Miles087** [comment]
In that code, i have gap++
VLC's error log
![q2](https://github.com/pedroSG94/RootEncoder/assets/4329440/3a8bf081-e266-46f2-bab3-2d34aa3183ed)

**Comment by pedroSG94** [comment]
Hello,

I recommend you use OpenGlView if you are using RtspCamera1 and capture images using takePhoto method:
```kotlin
rtspCamera1.glInterface.takePhoto { bitmap -> 
      
}
```
This way you can get images in bitmap format and convert bitmap to YUV if you really need YUV format

**Comment by Miles087** [comment]
Thanks, I tried to use OpenGLView and use takePhoto function, but an error came.
I use that bitmap to do some Time-consuming operation, last picture is my takePicture code.
![q3](https://github.com/pedroSG94/RootEncoder/assets/4329440/0a446b3a-4a11-4eef-916a-b97329f2f59a)
![q4](https://github.com/pedroSG94/RootEncoder/assets/4329440/c8ce6bab-7ebd-4960-b329-98f327b7d00e)

**Comment by Miles087** [comment]
Thanks, I modified my code to OpenGlView, it works well. Thank you very much!

**Comment by Miles087** [comment]
> Hello,
> 
> I recommend you use OpenGlView if you are using RtspCamera1 and capture images using takePhoto method:
> 
> ```kotlin
>     rtspCamera1.glInterface.takePhoto { bitmap ->
>       //do it in a thread to avoid block the view
>       val data = IntArray(bitmap.width * bitmap.height)
>       bitmap.getPixels(data, 0, bitmap.width, 0, 0, bitmap.width, bitmap.height)
>       val yuv = YUVUtil.ARGBtoYUV420SemiPlanar(data, bitmap.width, bitmap.height)
>       
>     }
> ```
> 
> This way you can get images in bitmap format and convert bitmap to YUV if you really need YUV format

Hello again， when I use takePhoto often, it cames an error like this. I don't know What can I do now.
Is my function cost much time?
![q5](https://github.com/pedroSG94/RootEncoder/assets/4329440/00518fbf-6f62-42fc-81a6-9678a7b159a3)
Here's my code below:
![code](https://github.com/pedroSG94/RootEncoder/assets/4329440/a57adb13-ce25-4540-b96b-fde669776cec)

**Comment by Miles087** [comment]
I try to use version 2.4.4, the same err came.
(update err log
![q6](https://github.com/pedroSG94/RootEncoder/assets/4329440/e82fc41b-d95b-4f43-8734-e25f117e92e5)

**Comment by pedroSG94** [comment]
Hello,

I'm no able to reproduce the error in my app example.
Can you share me a project example to reproduce it?

**Comment by Miles087** [comment]
> Hello,
> 
> I'm no able to reproduce the error in my app example. Can you reproduce it consistently? Do you have filters? Can you share me a project example to reproduce it?

Yes, it can be crush every time. I don't use any filter,  sorry I can't share project now, every time I use that bitmap to do facedetect, it will be crush quickly. 
I'll try to create a new project send to you. I just do operates with bitmap.

**Comment by Miles087** [comment]
I'm createing new project to send you. 
How can I send my poj to you?
I'll send you after about 2 hours later.

**Comment by pedroSG94** [comment]
> I'm createing new project to send you. How can I send my poj to you? I'll send you after about 2 hours later.

email could be a good option using a zip

I had other idea that maybe help you. But this way you need use api 21+. With camera1 only require api 18+ (using takephoto with camera1).
If it is fine you can use RtspCamera2 and this method:
```kotlin
      rtspCamera2.addImageListener(ImageFormat.YUV_420_888, 1) { image ->
        //this must be without a thread because image class is released after this callback
        val buffer = image.planes[0].buffer
        val yuv = ByteArray(buffer.capacity())
        buffer.get(yuv)
        //execute usage of the yuv in background thread now. You can convert yuv in bitmap like this:
        val bitmapImage = BitmapFactory.decodeByteArray(yuv, 0, yuv.length, null)
      }
```
This code should be better than takePhoto all time if you use higher resolutions
Even if you solve the error with the above code. Get a project where I can reproduce the previous error is important for me because that code should work without errors and this way I can try to solve it.

**Comment by Miles087** [comment]
> > I'm createing new project to send you. How can I send my poj to you? I'll send you after about 2 hours later.
> 
> email could be a good option using a zip
> 
> I had other idea that maybe help you. But this way you need use api 21+. With camera1 only require api 18+ (using takephoto with camera1). If it is fine you can use RtspCamera2 and this method:
> 
> ```kotlin
>       rtspCamera2.addImageListener(ImageFormat.YUV_420_888, 1) { image ->
>         //this must be without a thread because image class is released after this callback
>         val buffer = image.planes[0].buffer
>         val yuv = ByteArray(buffer.capacity())
>         buffer.get(yuv)
>         //execute usage of the yuv in background thread now. You can convert yuv in bitmap like this:
>         val bitmapImage = BitmapFactory.decodeByteArray(yuv, 0, yuv.length, null)
>       }
> ```
> 
> This code should be better than takePhoto all time if you use higher resolutions Even if you solve the error with the above code. Get a project where I can reproduce the previous error is important for me because that code should work without errors and this way I can try to solve it.

Thanks very much!   I'll try this in tomorrow morning. And I will give you fallback at once.

**Comment by Miles087** [comment]
> > I'm createing new project to send you. How can I send my poj to you? I'll send you after about 2 hours later.
> 
> email could be a good option using a zip
> 
> I had other idea that maybe help you. But this way you need use api 21+. With camera1 only require api 18+ (using takephoto with camera1). If it is fine you can use RtspCamera2 and this method:
> 
> ```kotlin
>       rtspCamera2.addImageListener(ImageFormat.YUV_420_888, 1) { image ->
>         //this must be without a thread because image class is released after this callback
>         val buffer = image.planes[0].buffer
>         val yuv = ByteArray(buffer.capacity())
>         buffer.get(yuv)
>         //execute usage of the yuv in background thread now. You can convert yuv in bitmap like this:
>         val bitmapImage = BitmapFactory.decodeByteArray(yuv, 0, yuv.length, null)
>       }
> ```
> 
> This code should be better than takePhoto all time if you use higher resolutions Even if you solve the error with the above code. Get a project where I can reproduce the previous error is important for me because that code should work without errors and this way I can try to solve it.

Morning, It's doesn't work when I use facedetect with this bitmap. I think maybe it's collision with  our facedetect module and this module. I tried to draw something on this bitmap, even though tried to delay a few seconds when drawing, it doesn't crash.  When I do our face detect, it does crashed. For project safty, I can't send you our face detect module. Sorry about that.

**Comment by pedroSG94** [comment]
> Morning, It's doesn't work when I use facedetect with this bitmap. I think maybe it's collision with our facedetect module and this module. I tried to draw something on this bitmap, even though tried to delay a few seconds when drawing, it doesn't crash. When I do our face detect, it does crashed. For project safty, I can't send you our face detect module. Sorry about that.

So, we can't reproduce the error without use your face detection library.
I was checking the previous way to get bitmap and maybe the problem is in the conversion. You have a valid buffer in that callback so we only need find the way to convert it in a valid bitmap for your library.

Another way to get the image and convert to bitmap:
```kotlin
      val converter = YuvToRgbConverter(this) //create it only one time
      rtspCamera2.addImageListener(ImageFormat.YUV_420_888, 1) { image ->
        //this must be without a thread because image class is released after this callback
        val bitmapImage = Bitmap.createBitmap(image.width, image.height, Bitmap.Config.ARGB_8888)
        converter.yuvToRgb(image, bitmapImage)
        //execute usage of the bitmap in background thread now.
      }
```
To use YuvToRgbConverter you will need copy this external classes:
https://github.com/android/camera-samples/blob/master/Camera2Basic/utils/src/main/java/com/example/android/camera/utils/YuvToRgbConverter.kt
https://github.com/android/camera-samples/blob/master/Camera2Basic/utils/src/main/java/com/example/android/camera/utils/Yuv.kt

**Comment by Miles087** [comment]
> > Morning, It's doesn't work when I use facedetect with this bitmap. I think maybe it's collision with our facedetect module and this module. I tried to draw something on this bitmap, even though tried to delay a few seconds when drawing, it doesn't crash. When I do our face detect, it does crashed. For project safty, I can't send you our face detect module. Sorry about that.
> 
> So, we can't reproduce the error without use your face detection library. It is good because other users can't reproduce it but, if you find a way to reproduce the error and share a code for it, let me know it.
> 
> I was checking the previous way to get bitmap and maybe the problem is in the conversion. You have a valid buffer in that callback so we only need find the way to convert it in a valid bitmap for your library.
> 
> Another way to get the image and convert to bitmap:
> 
> ```kotlin
>       val converter = YuvToRgbConverter(this) //create it only one time
>       rtspCamera2.addImageListener(ImageFormat.YUV_420_888, 1) { image ->
>         //this must be without a thread because image class is released after this callback
>         val bitmapImage = Bitmap.createBitmap(image.width, image.height, Bitmap.Config.ARGB_8888)
>         converter.yuvToRgb(image, bitmapImage)
>         //execute usage of the bitmap in background thread now.
>       }
> ```
> 
> To use YuvToRgbConverter you will need copy this external classes: https://github.com/android/camera-samples/blob/master/Camera2Basic/utils/src/main/java/com/example/android/camera/utils/YuvToRgbConverter.kt https://github.com/android/camera-samples/blob/master/Camera2Basic/utils/src/main/java/com/example/android/camera/utils/Yuv.kt

Hi, Now I found what's wrong with that. I'm a new compose user, that bug is my code problem. It's working well now. I'm appreciate for helping me to figure out what's happend. Thank you very much.
