### ISSUE TITLE
standalone local android (rtsp server)

### ISSUE THREAD

**Issue by dianyulius** [pedroSG94/RootEncoder#1461]
Hey there,

i want to ask can i use this library to create a local android rtsp server to accept stream data (for example from local client ip OBS)?

i tried to call:

```
rtspServer = RtspServer(this, 1935)
rtspServer.startServer()
```

and remarking these code:
```
//        if (!serverCommandManager.videoDisabled) {
//          if (!serverCommandManager.videoInfoReady()) {
//            semaphore.drainPermits()
//            Log.i(TAG, "waiting for video info")
//            semaphore.tryAcquire(5000, TimeUnit.MILLISECONDS)
//          }
//          if (!serverCommandManager.videoInfoReady()) {
//            onMainThreadHandler {
//              connectChecker.onConnectionFailed("video info is null")
//            }
//            return@Thread
//          }
//        }
```

then i start the obs server through _**rtsp://IPADDRESS:1935**_

![image](https://github.com/pedroSG94/RootEncoder/assets/13867659/840ec0f7-c0b8-446b-874b-a0208b985ca7)

Thank you!

**Comment by pedroSG94** [comment]
Hello,

This server is not designed to accept external data. This server is only to connect with a player and send data from the device sources.
I mean. a stream server has 2 types of clients:
- Pusher/encoders -> send video/audio data to the server
- Players -> get video/audio data from the server (the server get this video/audio data from the pusher) and reproduce it.

So this server only accept players and get the video/audio data from the device. External video/audio data from a pusher is not accepted.

**Comment by dianyulius** [comment]
Hello, 

Okay thanks for the reply.
