### ISSUE TITLE
RTMP Authentication not working

### ISSUE THREAD

**Issue by brian7704** [pedroSG94/RootEncoder#1484]
**Describe the bug**
When streaming using RTMP I call RtspCamera2.getStreamClient().setAuthorization("my_username", "my_password") but when I start to stream, no username or password is sent. I am streaming to MediaMTX

**To Reproduce**
1. Install [OpenTAK ICU](https://github.com/brian7704/OpenTAK_ICU/releases/tag/1.4.3)
2. In the stream settings select RTMP or RTMPS, and set your server's address, port, username, and password
3. Start streaming and see that no username or password is sent

**Expected behavior**
A username and password should be sent

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Library version: 2.3.5
 - Device: Pixel 4a and Pixel 6 Pro
 - OS: Android 144
 - Media server: MediaMTX 1.6.0
 - Class used RtmpCamer2

**Additional context**
You can also see the code [here](https://github.com/brian7704/OpenTAK_ICU/blob/33b68c4e8832f0bfd02b0c28e4fd2c5cd6fadb10/app/src/main/java/io/opentakserver/opentakicu/CameraService.java#L697)

**Comment by pedroSG94** [comment]
Hello,

I think this is not an error in the library. I'm not sure the way mediamtx is using RTMP auth (normally should use adobe auth) but it is not working even with ffmpeg. Only RTSP auth is working with mediamtx.
I tested RTMP using a wowza trial (wowza use adobe auth) and it is working fine. We should ask to mediamtx about it.

**Comment by brian7704** [comment]
I just found in MediaMTX's README that for RTMP the username should be appended to the end of the stream URL like this `?user=my_username&pass=my_pass`. When I did that, authentication worked as expected.

**Comment by pedroSG94** [comment]
> I just found in MediaMTX's README that for RTMP the username should be appended to the end of the stream URL like this `?user=my_username&pass=my_pass`. When I did that, authentication worked as expected.

Thank you for the info. This is a custom way to do it so remember that you only should do it using mediamtx.
This library support adobe auth and llnw auth for RTMP that are all RTMP auth supported in ffmpeg
