### ISSUE TITLE
Where can I download previous versions?

### ISSUE THREAD

**Issue by alexz006** [pedroSG94/RootEncoder#1494]
Hi, I worked on my project a while ago and used the following versions:

```
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.2.6'
implementation 'com.github.pedroSG94:RTSP-Server:1.1.8'
```

```
import com.pedro.encoder.input.video.CameraOpenException;
import com.pedro.rtplibrary.util.BitrateAdapter;
import com.pedro.rtplibrary.view.OpenGlView;
import com.pedro.rtsp.utils.ConnectCheckerRtsp;
import com.pedro.rtspserver.RtspServerCamera1;
import com.pedro.rtspserver.RtspServerCamera2;
```

After some time, I needed to make a few changes to my project's code, but I found out that the old versions are no longer supported. When I specify the new versions, I encounter a lot of errors. I only need to change a couple of lines in my code, but I can't do it because of the old library versions.

Please send me these old versions, as I really don't want to rewrite my code. The old versions suited me perfectly. Thank you!

**Comment by pedroSG94** [comment]
Hello,

You only need change to this:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6'
implementation 'com.github.pedroSG94:RTSP-Server:1.1.8'
```
Or you can get the source code from here:
https://github.com/pedroSG94/RootEncoder/tags
https://github.com/pedroSG94/RTSP-Server/tags

**Comment by alexz006** [comment]
build.gradle:
```
implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6'
implementation 'com.github.pedroSG94:RTSP-Server:1.1.8'
```
Clean -> Rebuild:
```
Duplicate class com.pedro.rtsp.utils.TLSSocketFactory found in modules rtsp-2.1.8-runtime (com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtsp:2.1.8) and rtsp-2.2.6-runtime (com.github.pedroSG94.RootEncoder:rtsp:2.2.6)
```
Then I wrote:
```
implementation('com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6')
implementation('com.github.pedroSG94:RTSP-Server:1.1.8') {
    exclude group: 'com.github.pedroSG94.rtmp-rtsp-stream-client-java', module: 'rtplibrary'
}
```
Clean -> Rebuild - BUILD SUCCESSFUL, but:

import com.pedro.rtspserver.RtspServerCamera2; - Cannot resolve symbol 'rtspserver'

**Comment by pedroSG94** [comment]
Hello,

Apparently that version of RTSP-Server had an error in jitpack. I recompiled it and now should be working.
Try to compile the project again.

**Comment by alexz006** [comment]
Unfortunately, the error remains..

**Comment by pedroSG94** [comment]
Hello,

Are you sure about it? I just tested it and it is working fine.

```gradle
    implementation 'com.github.pedroSG94.RootEncoder:rtplibrary:2.2.6'
    implementation ('com.github.pedroSG94:RTSP-Server:1.1.8') {
        exclude group: 'com.github.pedroSG94.rtmp-rtsp-stream-client-java', module: 'rtplibrary'
    }
```
Remember add jitpack maven:
```gradle
allprojects {
  repositories {
    maven { url 'https://jitpack.io' }
  }
}
```

Try with a clean project to make sure and clear the project properly deleting build folders

**Comment by pedroSG94** [comment]
Also, remove the import just in case that your import is not correct and use the IDE to import it

**Comment by alexz006** [comment]
Hello! I apologize a thousand times) It turns out that for several days I was trying to restore the wrong project... I had already downloaded and imported your libraries into my working project a long time ago, and everything works fine. Phew...
