### ISSUE TITLE
Local Screen Recording and Device Audio Recording

### ISSUE THREAD

**Issue by ramt57** [pedroSG94/RootEncoder#1495]
I am currently using the ROOTENCODER library for an Android application to record the screen while simultaneously streaming it live to an RTMP server. I have a couple of feature requests and questions regarding the library:

1. Local Screen Recording when RTMP Connection Fails:
       -  Scenario: Suppose the connection to my RTMP server fails or is not established.
       - Question: Is there a way for the ROOTENCODER library to continue recording the screen and save the recording locally on the device storage?
      
2. Microphone and Device Audio Recording:
        - Question: Is there an option within the ROOTENCODER library to toggle between recording audio from the microphone and recording the device's internal audio? If not, could this feature be considered for future updates?

**Comment by pedroSG94** [comment]
Hello,

Both cases are currently possible.

1 - You have a callback to detect connection fail. You can use that callback to start recording.

2 - Using StreamBase (RtmpStream, RtspStream, SrtStream, UdpStream or GenericStream class). You can change the audio and video source on fly.
You have an example changing video source on fly here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/RotationActivity.kt#L70
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/rotation

For internal audio you can use InternalSource and for microphone MicrophoneSource.
InternalSource need use a service to create the MediaProjection class like ScreenSource. You have an example using ScreenSource here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt

**Comment by ramt57** [comment]
Hi,

So Thanks for the Reply, Internal Audio is working fine now and yes we can use the same MediaProjection instance for ScreenSource and InternalSource.

**Comment by ramt57** [comment]
Also, Can u tell me how can I record to a local file.  I mean is this possible with your library or should I just implement my own recorder

**Comment by pedroSG94** [comment]
You can do it this way:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt#L128
