### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by eitanomer888** [pedroSG94/RootEncoder#1498]
I'm trying to use the "ConnectCheckerRtsp" from this domain by importing it like this:
import com.pedro.rtplibrary.rtsp.ConnectCheckerRtsp;

but the problem is that my project cannot recognize it (I added all the needed dependencies and I can import other things from the root encoder.

**Comment by pedroSG94** [comment]
Hello,

ConnectCheckerRtsp was replaced to ConnectChecker

**Comment by pedroSG94** [comment]
Closing as complete, you can reopen if needed
