### ISSUE TITLE
Pause Record to File for GenericStream/StreamBase

### ISSUE THREAD

**Issue by kenle** [pedroSG94/RootEncoder#1502]
**Is your feature request related to a problem? Please describe.**
Hi @pedroSG94 , i noticed pauseRecord() is available for the old API (Camera1Base, Camera2Base) but it doesn't seem to be available for GenericStream if I'm not mistakened.

**Describe the solution you'd like**
May you please add pauseRecord(), resumeRecord() for StreamBase parent of GenericStream?

Thank you!
- Ken

**Comment by pedroSG94** [comment]
Hello,

Fixed here:

You can use this gradle meanwhile:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:5942d1b149'
```

**Comment by kenle** [comment]
@pedroSG94 thank you for your quick response and update!

**Comment by kenle** [comment]
Hi @pedroSG94 , I tested it and it works perfectly.  Thanks again.

**Comment by pedroSG94** [comment]
> Hi @pedroSG94 , I tested it and it works perfectly. Thanks again.

Perfect :)
Closing the issue, if you need more help you can open other issue
