### ISSUE TITLE
Corrupt duration in file metadata when recording and livestreaming

### ISSUE THREAD

**Issue by NerdySouth** [pedroSG94/RootEncoder#1509]
**Describe the bug**
If we are recording a video, and activate livestreaming then the recording gets corrupted with a bad duration. We have two stream objects running simultaneously, but if there is a better way to stream audio always, record audio + video selectively, and selectively stream video, please let us know. 

**To Reproduce**
1. instantiate two generic streams, one with no video source and a mic, the other with both video and mic
2. start the audio only stream object with RTMP
3. start the audio + video object to record with startRecording()
4. activate video livestream by calling stopStreaming() on the audio only object, and then startStreaming() on the audio + video object, while it is still recording locally.
5. end the recording and livestream
6. recorded mp4 file has bad duration

**Expected behavior**
Normally, we expect that the mp4 had the correct duration, so the recording and livestreaming can happen simultaneously. This is on a Motorola Razr+ 2023

**Screenshots**

**Smartphone (please complete the following information):**
 - Library version [e.g. 2.2.7]
 - Device: Motorola Razr+ 2023
 - OS: Android1 3
 - Media server Nginx RTMP 
 - Class used: GenericStream

**Additional context**
We are building an app which needs to always be streaming audio via RTMP, while being able to selectively record video + audio locally (ex. when the user taps a button). We would also like to be able to selectively stream video along with the audio via RTMP. Currently, we do this by having two GenericStream objects, one with NoVideoSource() and MicrophoneSource()
and the other with a Camera2Source and Microphone source. The one with audio only streams to our endpoint, and when the user taps a button the other stream object will start/stop recording locally to the device. 

The bug happens when we try to then activate the video on the audio only stream. First we tried to change the video source on-the-fly, but we would never see the video in the player. So we then tried to just stop the audio stream object, release it, then instantiate a new GenericStream with Camera2Source and Mic. This worked, but if the device was recording locally when the video livestream is activated, we would end up with a recorded mp4 file that had a duration of 275 hours long. This was not correct, and there was also no video track in the mp4. If we never activate the video livestream during a recording, this would not happen.

After that, we decided we would just call stopStream() on the audio only object when we start a video livestream, and then just call startStream() on the stream object that is already recording locally. This fixed the issue of having no video track in the recording, but the duration was still the same (around 275 hours for a 20 second recording). This time, the video would freeze on the last frame for the remaining (incorrect) duration.

We did some digging and found this relevant [article](https://medium.com/@sandeepraghuraman/pitfalls-when-using-mediamuxer-with-mediacodec-and-camera-4b6b08b5a109) which may be the problem?

**Comment by pedroSG94** [comment]
Hello,

Thank you for the report. As you said maybe the error is that record no start with ts 0:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/recording/BaseRecordController.java#L107

I created a branch with a fix for it. Test it and let me know if the problem persist:
https://github.com/pedroSG94/RootEncoder/tree/fix/record-ts

**Comment by pedroSG94** [comment]
Let me know if you need a gradle compilation to test it and I can compile the branch for you

**Comment by NerdySouth** [comment]
So i just tried with the changes. Still having the same issue, but now the timestamps seem to be slightly bigger (starting at 283 hours rather than 275 hours).

**Comment by pedroSG94** [comment]
Can you share a code example to test?

**Comment by NerdySouth** [comment]
Yes, let me put together a quick example. In the meantime, i did some logging to try and spot a problem. I added a log statement in updateFormat in BaseRecordController.java to print out the old presentation time, startTs, and new presentation times. I noticed that whenever we activate the video livestream, the next value for oldinfo.presentationTimeUs comes back wildly larger than the previous. I am attaching a screenshot, but we can see the normal values prior to starting the stream are in the 3,117,404 range, then immediately after starting the video stream (while recording) the next value is huge.

![Screenshot 2024-06-28 at 2 52 48 PM](https://github.com/pedroSG94/RootEncoder/assets/46800978/9f7826fb-f438-4679-a5c2-ded0a11a99ab)

**Comment by NerdySouth** [comment]
``` 
// instantiate objects
liveStream = GenericStream(this@MainActivity, this, NoVideoSource(), MicrophoneSource()).apply {
    getGlInterface.autoHandleOrentation = true
}

recordStream = GenericStream(this@MainActivity, this, Camera2Source(this@MainActivity), MicrophoneSource())apply {
    getGlInterface.autoHandleOrentation = true
}

// prepare streams
fun prepareStreams() {
        try {
            liveStream.prepareAudio(sampleRate, isStereo, aBitrate) &&
                    liveStream.prepareVideo(width, height, vBitrate, 0, 2, 0, -1, -1) &&
                    recordStream.prepareVideo(width, height, vBitrate, 15, 2, 0, -1, -1) &&
                    recordStream.prepareAudio(sampleRate, isStereo, aBitrate)
        } catch (e: IllegalArgumentException) {
            Log.e(TAG, "onStart: Failed to prepare streams.")
        }

        // turn off preview
        liveStream.stopPreview()
        recordStream.stopPreview()
}
   
// start audio only 
liveStream.startStream("URL://STREAM-

// use some 
val path = "/some/path/here"
recordStream.startRecord(path) { status ->
      // get record 

// let recording progress a few seconds

// now activate video on livestream
liveStream.stopStream()
recordStream.startStream("URL FROM EARLIER")

// Now stop all streams, video file will have wrong duration
recordStream.stopStream()
recordStream.stopRecording()


```

**Comment by pedroSG94** [comment]
It is 02:00 here. I will test tomorrow

**Comment by pedroSG94** [comment]
Hello,

I fixed the ts problem. Gradle to test:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:3459b925df'
```
Let me know if all is working for you now.

**Comment by pedroSG94** [comment]
Hello,

I think I detected the problem. I did a commit to that branch.
Gradle:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:3459b925df'
```

**Comment by NerdySouth** [comment]
Yep, seems to be working now. Thanks so much!

**Comment by faromero** [comment]
Gracias Pedro!

**Comment by pedroSG94** [comment]
Closing as resolved.
I will merge this fix in master and create a release soon
