### ISSUE TITLE
What is a legal srt push stream url?

### ISSUE THREAD

**Issue by bamboo188** [pedroSG94/RootEncoder#1511]
Hi, pedro,thanks for your great work! 
I used screen rtsp push stream in your project, the effect is very stable, but the delay is a little high, about 3s. So I want to use srt push in your project to see if it can reduce the delay. **But I can't find a valid srt push url**. 

According to [this issue](https://github.com/pedroSG94/RootEncoder/issues/1372#issuecomment-1869056350), I tried `srt://192.168.123.218:8890/#!:: h = 192.168.123.218,r =/live/stream, m = publish`, app successfully connected to server, but then server got error `closed: invalid path name: can't begin with a slash (/live/stream)`, 
then I removed the first/, changed to `srt://192.168.123.218:8890/#!:: h = 192.168.123.218, r = live/stream, m = publish`, 
**Server got error again: `closed: unable to decode ADTS: invalid syncword`**.

I installed your app on an Android 10 API 29 phone, server is set up on an ubuntu PC, and I have verified that this server is available via ffmpeg push and pull streams.
The command line code for ffmpeg validation is as follows:
`ffmpeg-re-i 2.mp4-f mpeg 'srt://localhost: 8890? streamid=publish:mystream'# push `
`ffplay -i 'srt://192.168.123.218:8890? streamid=#!:: r = mystream '#pull stream`

So, can you give us some practical advice on what's the srt urls of successfully pushing and pulling stream?

**Comment by pedroSG94** [comment]
Hello,

Using this command in ffpmeg:
```
ffmpeg-re-i 2.mp4-f mpeg 'srt://localhost:8890?streamid=publish:mystream'
```
This url:
```
srt://localhost:8890?streamid=publish:mystream
```
In the library should be like this:
```
srt://localhost:8890/publish:mystream
```

This library can't reproduce a stream, only push video/audio (ffmpeg command) so you can't do the ffplay part.

**Comment by pedroSG94** [comment]
Also, remember reduce the delay in player side with ffplay using "-fflags nobuffer" like this:
```
ffplay -fflags nobuffer -i 'srt://192.168.123.218:8890?streamid=#!::r=mystream'
```

**Comment by bamboo188** [comment]
Thank you for your prompt reply, your answer perfectly solved my problem！With the addition of-fflags nobuffer, the delay is reduced from about 3s for rtsp to about 1s for srt. 
My Android device is Huawei nova5pro, push server and version: `mediamtx_v1.8.3_linux_amd64` environment is ubuntu22, 6.5.0-15-generic #15~22.04.1-Ubuntu.
Very impressive, but I will continue to try to optimize latency. Thank you again for your great work!

**Comment by pedroSG94** [comment]
This issue seems solved.
You can open other issue if you need it
