### ISSUE TITLE
Android run error when add library

### ISSUE THREAD

**Issue by MinhMinh8722** [pedroSG94/RootEncoder#1513]
![Capture1](https://github.com/pedroSG94/RootEncoder/assets/33676764/bfc816ca-420e-4363-b2cf-cca639b864f0)

When adding this library, this error happened. Please help me, THANKS!!! 🙏

**Comment by pedroSG94** [comment]
Hello,

I think that the problem is in "duplicate class found". Click in that line for more info.
If possible, share me the gradle dependencies related with this library.
Also, if possible use the last library version instead of version 2.2.6

**Comment by MinhMinh8722** [comment]
![Capture2](https://github.com/pedroSG94/RootEncoder/assets/33676764/8e0a8efd-668c-4f2f-bf10-05a238895c60)

I have this error when use the last version (2.4.5)

**Comment by MinhMinh8722** [comment]
Hi, I'm using Kotlin with version '1.6.21'. Do you think that is the problem for making this error?

**Comment by MinhMinh8722** [comment]
![Capture3](https://github.com/pedroSG94/RootEncoder/assets/33676764/3b794dac-532d-4fac-92c5-0e52c44033a6)

This is the error of 'duplicate class found'. Please help me, thanks! ^^

**Comment by pedroSG94** [comment]
Hello,

> ![Capture3](https://private-user-images.githubusercontent.com/33676764/344963835-3b794dac-532d-4fac-92c5-0e52c44033a6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTU2OTQsIm5iZiI6MTcxOTkxNTM5NCwicGF0aCI6Ii8zMzY3Njc2NC8zNDQ5NjM4MzUtM2I3OTRkYWMtNTMyZC00ZmFjLTkyYzUtMGU1MmM0NDAzM2E2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEwMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjEwM2RlY2Q3ZWEyY2MxNzg0YzQ3ZGRiNGMxZWM0NmQxN2IyYjU0YTJhNDNiMzVkYzJjNGRiYzJiN2IzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ecSgk6seCjdWlCktm9yoe79SsThCkgrvqqizIL5cyr4)
> 
> This is the error of 'duplicate class found'. Please help me, thanks! ^^

lifecycleview-model is not inside rootencoder dependencies.
Can you share me the line in dependecies related to rootencoder that you are using?



> Hi, @pedroSG94 I'm using Kotlin with version '1.6.21'. Do you think that is the problem for making this error?

I don't think that it is a problem



> ![Capture2](https://private-user-images.githubusercontent.com/33676764/344920927-8e0a8efd-668c-4f2f-bf10-05a238895c60.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTU2OTQsIm5iZiI6MTcxOTkxNTM5NCwicGF0aCI6Ii8zMzY3Njc2NC8zNDQ5MjA5MjctOGUwYThlZmQtNjY4Yy00ZjJmLWJmMTAtMDVhMjM4ODk1YzYwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEwMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOGY3MTU5N2MzYTM0YTcyMzQyZGE5MDRhZGUyMmZiN2QyZTI0N2M0NDAwNGFiMGJiZjljYTY5YThkYjQxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iLqVQYu_Q9CjA4kimL77mRfZ1vEEUQFh4_7p1X-3Xik)
> 
> I have this error when use the last version (2.4.5)

I can't get enough info with this. Can you click and show me the error in:
- app:kaptgeneratestubdebugkotlin
- app:compiledebugkotlin
- org.gradle.api.GradleException....

**Comment by MinhMinh8722** [comment]
Thanks @pedroSG94 
We upgraded version of gradle. This is my error. Thanks!
