### ISSUE TITLE
Sharpening filter no visible effect

### ISSUE THREAD

**Issue by perotom** [pedroSG94/RootEncoder#1514]
Thank you very much for this great library!
I tried to use the `SharpnessFilterRender` but I can't see any effect. Other filters are working just fine. I set the sharpness to 1.

Sadly I am not sure how to integrate some custom sharpening filter. Maybe something like that would be good: https://www.shadertoy.com/view/wsK3Wt

Would love to get some guidance, thank you!

**Comment by pedroSG94** [comment]
Hello,

Thank you for the report. Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/b625dd7730b69cca5a2a50cc9066b3e864281bc5

Compile the app example and test it in rotation example (use the menu in top-rigth to test any filter).

**Comment by perotom** [comment]
Awesome, this fix works!
