### ISSUE TITLE
encoder-2.4.6.aar not found

### ISSUE THREAD

**Issue by Comanx** [pedroSG94/RootEncoder#1531]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileSdchV5FmDebugAidl'.
> Could not resolve all files for configuration ':app:sdchV5FmDebugCompileClasspath'.
   > Failed to transform encoder-2.4.6.aar (com.github.pedroSG94.RootEncoder:encoder:2.4.6) to match attributes {artifactType=android-aidl, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find encoder-2.4.6.aar (com.github.pedroSG94.RootEncoder:encoder:2.4.6).
        Searched in the following locations:
            https://jitpack.io/com/github/pedroSG94/RootEncoder/encoder/2.4.6/encoder-2.4.6.aar
```

When opening https://jitpack.io/com/github/pedroSG94/RootEncoder/encoder/2.4.6/encoder-2.4.6.aar in the browser, it shows 'Not found,' but 2.4.7 works fine. I encountered a similar issue with a previous version in the 2.4.x series, which forced me to update to 2.4.6. However, the problem has recurred.

**Comment by pedroSG94** [comment]
Hello,

I don't know why but jitpack remove the compilations after few time or when I upload others versions.
I have an issue 1 moth ago totally ignored in github repository of jitpack.io
I will try compile it again.

**Comment by pedroSG94** [comment]
version 2.4.6 recompiled.
I checked the others versions (2.4.0 to 2.4.5 and 2.4.7) and all should be working fine.
Let me know if you have problems with other version

**Comment by Comanx** [comment]
Wow, that was fixed so quickly, thank you. I checked the previous version was 2.4.0, and magically now 2.4.0 is working fine. It seems like it was an issue with [jitpack.io](http://jitpack.io/).

**Comment by Comanx** [comment]
Could not find com.github.pedroSG94.RootEncoder:library:2.4.7
![image](https://github.com/user-attachments/assets/e1240a34-e8df-40ec-97dc-8e0987599357)
![image](https://github.com/user-attachments/assets/02b116a7-8515-4345-8c2b-44dbcb6fb3e0)

**Comment by pedroSG94** [comment]
Hello,

I don't know the reason but jitpack remove old releases sometimes.
I recompiled version 2.4.0

**Comment by Comanx** [comment]
> I'm not able to recompile 2.4.7

Oh, that's bad news. I'll downgrade to version 2.4.6,
Thanks
