### ISSUE TITLE
Unimplemented message type: null

### ISSUE THREAD

**Issue by MinhMinh8722** [pedroSG94/RootEncoder#1533]
Hi @pedroSG94 
I have got an error when I try to startStream()

<img width="1239" alt="Screenshot 2024-08-02 at 08 54 44" src="https://github.com/user-attachments/assets/9ffacd96-2161-497c-b252-bc1a248c0408">

I think my issue is the same as [#1168](https://github.com/pedroSG94/RootEncoder/issues/1168)

My URL server is youtube server: rtmp://a.rtmp.youtube.com/live2
Please help me with this. Thanks so much!

**Comment by MinhMinh8722** [comment]
@pedroSG94 
Sorry, I knew my issue. Thanks!

**Comment by bhavinatharva** [comment]
@pedroSG94 facing same

**Comment by pedroSG94** [comment]
This is caused because the server close connection with you. If you are using YouTube remember add stream key after the url. Instead of:
```
rtmp://a.rtmp.youtube.com/live2
```
Use:
```
rtmp://a.rtmp.youtube.com/live2/xxxx-xxxx-xxxx-xxxx-xxxx
```
Where xxxx-xxxx-xxxx-xxxx-xxxx is the key of your stream that should be provided from the youtube studio where you create the new stream

**Comment by duguangyan** [comment]
facing same, I use RSR service， the url looks like   rtmp://192.168.7.11/live/livestream

**Comment by pedroSG94** [comment]
Hello,

Please, open an issue if necessary and reference to this issue but avoid write in a closed issue.
About your case:
Don't use amf3-support because it is not finished. It is freezed until I'm able to find a server that support amf3 because I need it to test it.
