### ISSUE TITLE
Updated to the latest version 2.4.7, Android studio cannot find the code implementation of RtmpClient

### ISSUE THREAD

**Issue by sheng930920** [pedroSG94/RootEncoder#1542]
**Describe the bug**
After upgrading to the latest version 2.4.7 or 2.4.6, Android studio cannot find the code implementation of RtmpClient. Downgrading the version to 2.4.5 works fine.

<img width="1395" alt="image" src="https://github.com/user-attachments/assets/dcc14615-eb58-46ae-80a5-ec375a54e09f">
<img width="997" alt="image" src="https://github.com/user-attachments/assets/f2cb2157-3430-49f4-b098-8cebd896cc5a">

**Comment by pedroSG94** [comment]
Hello,

I just tested the compilation in a clear project and it is working fine for me. This is like the library is not found
Can you show me your build error?

**Comment by sheng930920** [comment]
Android studio has been upgraded to the latest version and the problem has been solved
