### ISSUE TITLE
Add some parameters to the URL

### ISSUE THREAD

**Issue by Moyout** [pedroSG94/RootEncoder#1556]
How can I add some parameters to the URL, similar to how OBS software can set some parameters before starting live.

![2024-08-24 053149](https://github.com/user-attachments/assets/453a5eca-5095-4c32-b0dc-becbf9710b5a)

**Comment by pedroSG94** [comment]
Hello,

I'm not sure what do you want to do with test=qwer. But that seems to be an app name so you can try this way:
```
rtmp://192.168.238.182:1935/live?test=qwer/123456
```
In this library the equivalent to OBS is write both textbox contactenated by an "/"

**Comment by Moyout** [comment]
> Hello,
> 
> I'm not sure what do you want to do with test=qwer. But that seems to be part of an app name so you can try this way:
> 
> ```
> rtmp://192.168.238.182:1935/live?test=qwer/123456
> ```
> 
> In this library the equivalent to OBS is write both textbox concatenated by an "/"
okay！
What I mean is to add some parameters to the URL so that they can be captured on your own server for verification

**Comment by Moyout** [comment]
> Hello,
> 
> I'm not sure what do you want to do with test=qwer. But that seems to be part of an app name so you can try this way:
> 
> ```
> rtmp://192.168.238.182:1935/live?test=qwer/123456
> ```
> 
> In this library the equivalent to OBS is write both textbox concatenated by an "/"

Hello! 
If I use this method for live streaming, which URL should I use for playback in VLC media player? I have tried many URLs but cannot find the live streaming URL

**Comment by pedroSG94** [comment]
The same URL:
rtmp://192.168.238.182:1935/live?test=qwer/123456

Anyway, If you don't need test=qwer. I recommend you remove it from both, stream and vlc:
rtmp://192.168.238.182:1935/live/123456

If you need it, commonly I see this type of custom parameters to the end of the URL:
rtmp://192.168.238.182:1935/live/123456?test=qwer

**Comment by Moyout** [comment]
If the same URL is used, wouldn't it expose these parameters?

> The same URL: rtmp://192.168.238.182:1935/live?test=qwer/123456
> 
> Anyway, If you don't need test=qwer. I recommend you remove it from both, stream and vlc: rtmp://192.168.238.182:1935/live/123456
> 
> If you need it, commonly I see this type of custom parameters to the end of the URL: rtmp://192.168.238.182:1935/live/123456?test=qwer

**Comment by Moyout** [comment]
> The same URL: rtmp://192.168.238.182:1935/live?test=qwer/123456
> 
> Anyway, If you don't need test=qwer. I recommend you remove it from both, stream and vlc: rtmp://192.168.238.182:1935/live/123456
> 
> If you need it, commonly I see this type of custom parameters to the end of the URL: rtmp://192.168.238.182:1935/live/123456?test=qwer

Do you know how to authenticate nginx+RTMP

**Comment by pedroSG94** [comment]
Yes, instead of the typical ffmpeg url:
```
rtmp://user:pass@192.168.238.182:1935/live/123456
```
Set the url without user pass:
```
rtmp://192.168.238.182:1935/live/123456
```
And use setAuthorization any time before startStream:
```kotlin
yourStreamObject.getStreamClient().setAuthorization("user", "password")
```

**Comment by pedroSG94** [comment]
> If the same URL is used, wouldn't it expose these parameters?
> 
> > The same URL: rtmp://192.168.238.182:1935/live?test=qwer/123456
> > Anyway, If you don't need test=qwer. I recommend you remove it from both, stream and vlc: rtmp://192.168.238.182:1935/live/123456
> > If you need it, commonly I see this type of custom parameters to the end of the URL: rtmp://192.168.238.182:1935/live/123456?test=qwer

Yes, if you set custom parameters in the url. That parameters are exposed if you don't have a custom server implementation that receive parameters and create other output url without parameters.
Anyway, the stream with rtmp (without ssl) is totally clear for a MITM (man in the middle) attack.

If you want set parameters supported by the protocol by default (like auth) let me know the parameter and I can tell you if it is supported in this library

**Comment by Moyout** [comment]
> > > The same URL: rtmp://192.168.238.182:1935/live?test=qwer/123456
> > > Anyway, If you don't need test=qwer. I recommend you remove it from both, stream and vlc: rtmp://192.168.238.182:1935/live/123456
> > > If you need it, commonly I see this type of custom parameters to the end of the URL: rtmp://192.168.238.182:1935/live/123456?test=qwer
> > 
> > 
> > Do you know how to authenticate nginx+RTMP
> 
> Yes, instead of the typical ffmpeg url:
> 
> ```
> rtmp://user:pass@192.168.238.182:1935/live/123456
> ```
> 
> Set the url without user pass:
> 
> ```
> rtmp://192.168.238.182:1935/live/123456
> ```
> 
> And use setAuthorization any time before startStream:
> 
> ```kotlin
> yourStreamObject.getStreamClient().setAuthorization("user", "password")
> ```

Does RTMP have authentication services? How to set up RTMP server

**Comment by pedroSG94** [comment]
I don't understand you. RTMP protocol support auth but this also depend of your server (maybe it is not implemented). 
How to configure the server to allow auth should be ask to the server developers. I can't help you with server configurations

**Comment by Moyout** [comment]
All right

> 我不明白你的意思。RTMP 协议支持身份验证，但这也取决于你的服务器（可能没有实现）。 如何配置服务器以允许身份验证应该询问服务器开发人员。我无法帮助你进行服务器配置
