### ISSUE TITLE
Unsafe implementation of the X509TrustManager interface

### ISSUE THREAD

**Issue by AnthonyWu-kkstream** [pedroSG94/RootEncoder#1563]
The AcceptAllCertificates class defines empty checkServerTrusted() and checkClientTrusted() methods, thereby disabling SSL validation and accepting any SSL certificate as valid if the class is used when connecting to a server over SSL/TLS.

Regardless of whether the affected classes are actually used at runtime, Google Play is blocking any app that defines such an insecure X509TrustManager, as detailed on Google's support page:

"Beginning May 17, 2016, Google Play will block the publishing of any new apps or updates containing an unsafe implementation of the X509TrustManager interface."

[reference](https://developer.android.com/privacy-and-security/risks/unsafe-trustmanager)

**Comment by pedroSG94** [comment]
Duplicated issue:
https://github.com/pedroSG94/RootEncoder/issues/1562

Closing issue as dupicated
