### ISSUE TITLE
Passing the '/' symbol in the URL will result in an exception

### ISSUE THREAD

**Issue by Moyout** [pedroSG94/RootEncoder#1566]
When my RTMP link is like this：
```
rtmp://192.168.238.182:1935/live/100044?userId=100044&roomTitle=123123&roomCover=http://192.168.238.182/xxxx.png
```
 when connecting, the console output is as follows:

```shell
send Command(name='connect', transactionId=1, timeStamp=0, streamId=0, data=[AmfString value: connect, AmfNumber value: 1.0, AmfObject properties: {AmfString value: app=AmfString value: live/100044?userId=100044&roomTitle=123123&roomCover=http:, AmfString value: flashVer=AmfString value: FMLE/3.0 (compatible; Lavf57.56.101), AmfString value: tcUrl=AmfString value: rtmp://192.168.238.182:1935/live/100044?userId=100044&roomTitle=123123&roomCover=http:, AmfString value: objectEncoding=AmfNumber value: 0.0}], bodySize=259)
```
My roomCover parameter has been truncated. How can I pass parameters with a '/' symbol ?

**Comment by pedroSG94** [comment]
Hello,

This seems a parse error in the library. 
I'm already working to fix it. Thank you for the report

**Comment by Moyout** [comment]
> 你好，
> 
> 这似乎是库中的解析错误。 我已经在努力修复它。感谢您的报告



> Hello,
> 
> This seems a parse error in the library. I'm already working to fix it. Thank you for the report

Okay, if it's fixed, you can reply to me

**Comment by pedroSG94** [comment]
Hello,

I did a fix for this case:
https://github.com/pedroSG94/RootEncoder/pull/1567

I'm doing more testing because this change is important since I removed the previous parser.

**Comment by pedroSG94** [comment]
The fix is available in master now. I did a gradle compilation for it meanwhile release 2.5.1 is available:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:591f882147'
```

**Comment by Moyout** [comment]
That's great

> The fix is available in master now. I did a gradle compilation for it meanwhile release 2.5.1 is available:
> 
> ```groovy-gradle
>   implementation 'com.github.pedroSG94.RootEncoder:library:591f882147'
> ```
