### ISSUE TITLE
Title of youtube streaming

### ISSUE THREAD

**Issue by t4k3n3r** [pedroSG94/RootEncoder#1586]
There is any way in wich i can set the streming titile for youtube live? I'm streaming but allways with the same title, i want to manage the title directly from the app.

Not related, i want to stream in portrait mode and add some logos, but in portrait mode the images appear to be a little deformed (more width than usual)
im doing it with ImageObjectFilterRender, BitmapFactory and use .setScale(scaleWidth, scaleHeight) to modify the witdth an height mantaining the aspect ratio. There is any way to do it correctly

Sorry, im new to android development and sorry for my english is not my main language

**Comment by pedroSG94** [comment]
Hello,

The first question:
No, this library only provide a way to use stream protocols, if you want change the stream title on YouTube you will need use YouTube libraries.

Second question:
You need use setScale depend of your stream size and the image size. Set scale works like this:
setScale(percentX, percentY)
Where percentX is the percent of the stream size. For example: 
streaming with resolution 480x640 (portrait) -> percentX = 50f -> 240px in width
streaming with resolution 480x640 (portrait) -> percentY = 50f -> 320px in height

**Comment by t4k3n3r** [comment]
i've created a method in BaseObjectFilterRender.java to avoid errors rescaling images when you have a max height and width. I put it here just in case.
`public void setReScale(float streamHeight, float streaWidth, float maxWidth, float maxHeight, float initialX, float initialY) {

    // Initialize scales
    var scaleWidth = maxWidth;
    var scaleHeight = maxHeight;
    var streamRatio = streamHeight / streaWidth;
    float height = (float) streamObject.getHeight();
    float width = (float) streamObject.getWidth();
    float localAspectRatio = height / width;

    // Adjust scale to mantain aspect ratio without passing the max limits
    if (localAspectRatio > 1) {
      // If the image is more width than height, we adjust the width to the max
      scaleHeight = maxHeight / localAspectRatio / streamRatio;
      if (scaleHeight > maxHeight) {
        scaleHeight = maxHeight;
        scaleWidth = maxWidth * localAspectRatio * streamRatio;
      }
      else{
        scaleWidth = maxWidth;
        scaleHeight = maxHeight;
      }
    }
    else if (localAspectRatio < 1){
      scaleWidth = maxWidth * localAspectRatio * streamRatio;
      if (scaleWidth > maxWidth) {
        scaleWidth = maxWidth;
        scaleHeight = maxHeight / localAspectRatio / streamRatio;
      }
      else{
        scaleWidth = maxWidth;
        scaleHeight = maxHeight;
      }
    }
    float localPosX = initialX + ((maxWidth - scaleWidth) / 2);
    float localPosY = initialY + ((maxHeight - scaleHeight) / 2);
    this.setScale(scaleWidth, scaleHeight);
    this.setPosition(localPosX, localPosY);
  }`
