### ISSUE TITLE
RtspStream video fps

### ISSUE THREAD

**Issue by legosaro** [pedroSG94/RootEncoder#1598]
Hey there, 
 I tried to set the FPS value lower than 30, but I'm having issues recording the video when I use forceFpsLimit. If I don't use forceFpsLimit, it seems that the FPS value passed in the prepareVideo function isn't considered. 
How can I set a smaller FPS value, like 15 FPS?

Thanks!

**Comment by pedroSG94** [comment]
Hello,

Actually, forceFpsLimit is the only way to force the library use a fps value. In prepareVideo the fps is used to indicate to the camera fps desired, but it is only used if the camera support that fps for that resolution. If not, the camera select the closest value to your request.
forceFpsLimit basically ignore a frame if the frames come so fast skipping it.

Did you tried to use 30 fps in prepareVideo and 15 fps in forceFpsLimit or 15fps in both cases?
Can you describe the issues?

**Comment by legosaro** [comment]
Hello Pedro,
  thank you for your response. 
Here is the piece of code that I am using: 
   ```
    rtspStream.prepareAudio(48 * 1000, false,  48 * 1000, true, true);
    rtspStream.prepareVideo(640, 480, 1200 * 1024, 15, 2, 0);
    rtspStream.forceFpsLimit(true);
```

The issue I am experiencing is that, after a few seconds of recording, the video stream unexpectedly freezes, and no new frames are processed.

**Comment by pedroSG94** [comment]
Also, try this way:
```java
    rtspStream.prepareAudio(48 * 1000, false,  48 * 1000, true, true);
    rtspStream.prepareVideo(640, 480, 1200 * 1024, 30, 2, 0);
    rtspStream.getGlInterface().forceFpsLimit(15);
```

**Comment by legosaro** [comment]
> Which class are you using as VideoSource?

default RtspStream videoSource: Camera2Source

**Comment by legosaro** [comment]
> ```java
> rtspStream.getGlInterface().forceFpsLimit(15);
> ```

the video blocked after 1 second

**Comment by pedroSG94** [comment]
Can you tell me if the preview is blocked too in all cases?

**Comment by legosaro** [comment]
I also tried making some changes directly in the sample application provided by the library, modifying the code like this: 
```
private fun prepare() {
    val prepared = try {
      genericStream.prepareVideo(width, height, vBitrate, rotation = rotation, fps=30) &&
          genericStream.prepareAudio(sampleRate, isStereo, aBitrate)
    } catch (e: IllegalArgumentException) {
      false
    }
    if (!prepared) {
      toast("Audio or Video configuration failed")
      activity?.finish()
    }

    genericStream.getGlInterface().forceFpsLimit(15)
  }
```
Unfortunately, even with these changes, the application crashes during the preview.

**Comment by pedroSG94** [comment]
Can you share the crash logcat?

**Comment by legosaro** [comment]
sorry, I meant that the preview freezes

**Comment by pedroSG94** [comment]
Ok, I will check it

**Comment by pedroSG94** [comment]
Hello,

I did a fix for it and all seem solved.
Get last commit in master branch and test again.

**Comment by legosaro** [comment]
I tried the latest commit, and the example seems to work fine. When is a new version of the library expected to be released with this fix?

**Comment by pedroSG94** [comment]
I have plan to do it this week. Currently, I'm working in other fix that I want include in the next release and then I will do the release.

**Comment by pedroSG94** [comment]
Closing as solved

**Comment by legosaro** [comment]
Hello Pedro,
  I tested the forceFpsLimit feature using the latest version of the library (2.5.2). The video records without any issues, but I noticed that the file size remains the same whether I set the FPS to 30 or 15. Why does this happen?

`
  rtspStream.prepareVideo(640, 480, 1200 * 1000, 30, 2, 270);  rtspStream.getGlInterface().forceFpsLimit(15);
`

Thx

**Comment by pedroSG94** [comment]
Hello,

This is because the size depend of the bitrate, the fps is not related with the size. The only different in your case if you set 30fps to prepareVideo in both cases is the keyframe.
The encoder calculate when should generate a keyframe using iFrameInterval and fps values:

- 30fps, 2 interval, force 30 -> 1 keyframe each 2 seconds (generate 1 keyframe each 60 frames)
- 30fps, 2 interval, force 15 -> 1 keyframe each 4 seconds (generate 1 keyframe each 60 frames but in this case you produce 15 frames per second)
