### ISSUE TITLE
audio tick noise

### ISSUE THREAD

**Issue by Lyman92** [pedroSG94/RootEncoder#1605]
I user RtspStream
If I set audio samplerate  8000  there is no tick noise 
but the quality is bad
If I set samplerate to  44100 there is tick noise.
Is it the problem with MicrophoneMode 
how to set MicrophoneMode with RtspStream

**Comment by pedroSG94** [comment]
Hello,

Using this gradle:
```gradle
  implementation 'com.github.pedroSG94.RootEncoder:library:f0b9aa3fcb'
```
Try add this line after create RtspStream class:
```kotlin
rtspStream.setTimestampMode(TimestampMode.BUFFER, TimestampMode.BUFFER)
```

**Comment by Lyman92** [comment]
Thanks，it's hardware issues maybe。
