### ISSUE TITLE
Choose encoder with CBR priority

### ISSUE THREAD

**Issue by isaacchiang-kkstream** [pedroSG94/RootEncoder#1632]
**Is your feature request related to a problem? Please describe.**
We need to ensure the setting of CBR during the streaming. But i only notice that there have 3 settings in RootEncoder
1. HARDWARE
2. SOFTWARE
3. FIRST_COMPATIBLE_FOUND

**Describe the solution you'd like**
Can you provide the 4th setting which in below priority?
`hardware CBR > software CBR > hardware > software`

**Describe alternatives you've considered**
If solution available, please release it in a official version will very helpful to me. Thank you.

**Additional context**
N/A

**Comment by pedroSG94** [comment]
Hello,

Currently the library follow this rule (using FIRST_COMPATIBLE_FOUND that is used by default):
hardware CBR > hardware > software CBR > software

This is because in the streaming CBR is always recommended. You can find the logic here:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L359
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java#L293

**Comment by pedroSG94** [comment]
I could add it for the next release

**Comment by pedroSG94** [comment]
No date for now.
I want finish a new feature related to support custom Extractors to use in FromFile streaming and maybe others fixs.

I can provide you a compilation of the commit with this change meanwhile (I think I could have a compilation this week).

**Comment by isaacchiang-kkstream** [comment]
> No date for now.
I want finish a new feature related to support custom Extractors to use in FromFile streaming and maybe others fixs.

Sure, It's ok.

> I can provide you a compilation of the commit with this change meanwhile (I think I could have a compilation this week).

You mean might provide as below import way this week?
```
implementation 'com.github.pedroSG94.RootEncoder:library:{COMMIT_NUM}'
```
That will be great! Thank you.

**Comment by pedroSG94** [comment]
I did a PR for this:
https://github.com/pedroSG94/RootEncoder/pull/1633
I want test it a bit and then merge into master

**Comment by isaacchiang-kkstream** [comment]
Thanks for the PR, it looks perfect! But instead of directly using the source code to enter my project, I use Gradle import your released version to enter my project. Since the release(official) version still under developing, could you please provide the snapshot version that i can import to my project? Such as below:
```kotlin=
implementation 'com.github.pedroSG94.RootEncoder:library:35c550b3bb'
```

**Comment by pedroSG94** [comment]
Hello,

Try with this gradle:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:35c550b3bb'
```

**Comment by isaacchiang-kkstream** [comment]
Thanks a lot, very helpful.

**Comment by isaacchiang-kkstream** [comment]
Hi, 
I notice that might be some typo in this line? https://github.com/pedroSG94/RootEncoder/pull/1633/files
Can you please help to check it if you available?

**Comment by pedroSG94** [comment]
Which line?

**Comment by isaacchiang-kkstream** [comment]
```kotlin=
List<MediaCodecInfo> softwareEncoders = getAllHardwareEncoders(mime
```

**Comment by pedroSG94** [comment]
True, fixed:
https://github.com/pedroSG94/RootEncoder/commit/204efe020e484abbb7f0d998a3ac5f86146ed641
I'm compiling a new gradle

**Comment by pedroSG94** [comment]
Gradle:
```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:8b428e5d4e'
```

**Comment by isaacchiang-kkstream** [comment]
This `8b428e5d4e` version worked fine, thank you very much. 👍

**Comment by pedroSG94** [comment]
Ok,
Closing as solved. You can use the gradle until the new release is uploaded
