### ISSUE TITLE
Invalid NAL unit size  with ZLMediaKit

### ISSUE THREAD

**Issue by Lyman92** [pedroSG94/RootEncoder#1648]
Hello,

I use RtspStream to push android screen and microphone to rtsp server (we use  [ZLMediaKit](https://github.com/ZLMediaKit/ZLMediaKit) as server site)
my android code:
```
rtspStream = new RtspStream(getBaseContext(), this, new NoVideoSource(), new MicrophoneSource());
rtspStream.getStreamClient().setReTries(10);
rtspStream.getStreamClient().setLogs(true);
rtspStream.getGlInterface().setForceRender(true, FPS);
rtspStream.setAudioCodec(AudioCodec.AAC);
rtspStream.setTimestampMode(TimestampMode.BUFFER, TimestampMode.BUFFER);
prepared = rtspStream.prepareVideo(capSize.getWidth(), capSize.getHeight(), vBitrate, FPS, IFRAME_INTERVAL, rotation) &&
                    rtspStream.prepareAudio(sampleRate, isStereo, aBitrate, true, true);
rtspStream.getGlInterface().setCameraOrientation(0);
rtspStream.changeVideoSource(screenSource);
rtspStream.changeAudioSource(new MicrophoneSource());
rtspStream.startStream(endpoint);
```
our admin site will play and record the video and audio  via  ZLMediaKit ,  video and audio will be transformed to ws protocol as below
ws://192.168.110.220:6060/rtp/41280175262397976495_41280175262397976495.live.flv
we cannot see the video but can hear the sound from the stream.

The browser console loged as below
Jessibuca: [worker]: [h264 @ 0x6bda30] Invalid NAL unit size (0 > 117492).
Jessibuca: [worker]: [h264 @ 0x6bda30] Error splitting the input into NAL units.

the stream can be played well with vlc player by the rtsp protocol.

We cannot find other solussions.  Any idea or suggestions for us? Thank you so much.

**Comment by pedroSG94** [comment]
If VLC can reproduce it using RTSP the problem should be in the transformation to ws or the player.
Can you see the video using VLC and ws? Did you try using H265?

**Comment by Lyman92** [comment]
If I use H265,  The app throws an exception  
```
FATAL EXCEPTION: VideoEncoder
Process: com.openfire.app, PID: 7738
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.nio.ByteBuffer.remaining()' on a null object reference
	at com.pedro.encoder.video.VideoEncoder.extractVpsSpsPpsFromH265(VideoEncoder.java:427)
	at com.pedro.encoder.video.VideoEncoder.sendSPSandPPS(VideoEncoder.java:332)
	at com.pedro.encoder.video.VideoEncoder.formatChanged(VideoEncoder.java:512)
	at com.pedro.encoder.BaseEncoder$1.onOutputFormatChanged(BaseEncoder.java:315)
	at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1810)
	at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1705)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by pedroSG94** [comment]
Hello,

I fixed that error here:
https://github.com/pedroSG94/RootEncoder/commit/e7d23da2aaf8ff8b9bcda96c303b25a1a51acbdf

Did you try to reproduce the stream using ws with VLC to discard that the problem is in the player?

**Comment by Lyman92** [comment]
VLC can't play the stream using ws.
I tried H265 and  works on my phone and some Android TV.  But some of  my Android TV  do not support H265 encoding ( prepareVideo return false )

**Comment by Lyman92** [comment]
the [ZLMediaKit](https://github.com/ZLMediaKit/ZLMediaKit)  will auto generate rtmp link ，and can be played by VLC.
We don't know which version of RFC used by ZLMediaKit
Can you add support for RFC 6184 ?

**Comment by pedroSG94** [comment]
Hello,

> Can you add support for RFC 6184 ?

If you can reproduce the stream in rtmp then the RFC should not be related because the server need unpacketize the RTP frame to create flv packets necessary to rtmp. This seems a problem in the rtsp to ws translation. Did you tried using ffmpeg to reproduce the case and confirm that all is working fine?

> Is there a method to test if a device support H265?

Yes, you can use this method to know if you device have h265 encoders:
```kotlin
CodecUtil.getAllEncoders(CodecUtil.H265_MIME, true, true).size >= 1
```
Also, you can use that method to know the codec selected by the library:
```kotlin
//The library select the first codec in the list, you can get info about the codec selected
CodecUtil.getAllEncoders(CodecUtil.H265_MIME, true, true)[0]
```

**Comment by Lyman92** [comment]
Thanks
