### ISSUE TITLE
RtmpClient: stream to a RTMPS server secured by a key

### ISSUE THREAD

**Issue by frozar** [pedroSG94/RootEncoder#1650]
I successfully launched the demo project in this repository on my smartphone.

I'm trying to stream my camera to a private RTMPS server. My RTMPS server is secured by a key. What I mean by that is that if I used OBS, for example, to stream my screen to my RTMPS server, I have to provide this key in the `Stream Key` in the settings of the connexion to the server.

![image](https://github.com/user-attachments/assets/441996a2-6b87-490e-8bbc-8df44b5379d1)

I'm not proficient in Kotlin development, and despite my efforts to understand the settings for the connexion to a RTMPS server, I don't find the place to put my private key.

Is there a way in the demo application to setup the connexion with a secure key please?
If not, do you have any advice to do so please? What part of the code should I checkout please?

**Comment by pedroSG94** [comment]
Hello,

In this library this is the equivalent:
```
servertext/streamkeytext
```

**Comment by frozar** [comment]
@pedroSG94 Thank you, it works :tada: 

But just to be explicit, and to let you know, in my RTMPS server URL, I have some `/` too so the setting of the `protocol://yourendpoint` field in the stream view was a bit confusing.
For example, let say my URL for the RTMPS server is `rtmps://58ce357411d46.domain-name.net:443/apps/` and my server key is `Fo97t7£QDd*_`, then I type the following in the `protocol://yourendpoint` field:
```
rtmps://58ce357411d46.domain-name.net:443/apps/Fo97t7£QDd*_
```
and it works :D 

Thank you again for your quick answer. I let you close this issue :)
