### ISSUE TITLE
RtmpClient endpoint parser

### ISSUE THREAD

**Issue by alexsafe** [pedroSG94/RootEncoder#1652]
Hi,

My stream endpoint looks like this "rtmp://rtmp-auto.millicast.com:[port]/v2/pub/[stream_name]?[token]" . The main issue is with the refactored RtmpClient. Before 2.5.1 it was using a regex and it was parsing correctly. After 2.5.2 , it parses appName as "v2" , where it should be "v2/pub" and the connection is not established. I made my own RtmpClient to solve this, but maybe there is a better way?

**Comment by pedroSG94** [comment]
Hello,

Are you using the library version 2.5.4?
I tested the endpoint like this:
```
rtmp://rtmp-auto.millicast.com:1935/v2/pub/streamName?token
```
And it is working as expected

**Comment by alexsafe** [comment]
Thanks! I see what's happening ... i was dumb and didn't notice I basically wrote the answer in my question :)

Yes it's for 2.5.4. I was calling it in my code as /[stream_name]?token=[token] (which does fail and worked before) instead of /[stream_name]?[token] (which works)
