### ISSUE TITLE
message type null , connection failed

### ISSUE THREAD

**Issue by duguangyan** [pedroSG94/RootEncoder#1656]
branch is amf3-support ， I use SRS service，use OBS tools to test is good , the RTMP url looks like : rtmp://192.168.7.11/live/livestream,

connection failed.

**Comment by pedroSG94** [comment]
Hello,

As I said in the other issue.

Don't use amf3-support because it is not finished. It is freezed until I'm able to find a server that support amf3 because I need it to test it. You can test using master branch which use amf0 but should work fine with SRS server

**Comment by duguangyan** [comment]
There is no problem using SRS on the master branch, but there are no instances of watermarks on the master branch. If I want to implement a streaming watermark effect on the master branch, how should I handle it? Please help me.

**Comment by pedroSG94** [comment]
You have code examples to add bitmap filter in the stream using Rotation example. You can open the rotation example and use the top-right menu to add a filter

**Comment by duguangyan** [comment]
Thank you very much, you have solved my problem

**Comment by pedroSG94** [comment]
Closing as solved
