### ISSUE TITLE
GenericStreamClient and setAuthorization

### ISSUE THREAD

**Issue by brian7704** [pedroSG94/RootEncoder#1672]
**Is your feature request related to a problem? Please describe.**
I'm trying to use GenericStream and authorization, but setAuthorization throws an unimplemented error due to the lack of authorization support in SRT. I'm using GenericStream in order to make it easier to switch between Camera2, UVC Camera, and Screen sources.

**Describe the solution you'd like**
Could the call to srtClient.setAuthorization() on [this line](https://github.com/pedroSG94/RootEncoder/blob/2707c46770b51e56d89093b6847d556e23168243/library/src/main/java/com/pedro/library/util/streamclient/GenericStreamClient.kt#L97) be removed from GenericStreamClient.setAuthorization() until SRT authorization is implemented?

**Describe alternatives you've considered**
None

**Additional context**

**Comment by pedroSG94** [comment]
Hello,

You can use RtmpStream or RtspStream depend of the protocol that you need use instead of GenericStream.
The idea of GenericStream is only support common methods for all protocols.

**Comment by brian7704** [comment]
Got it, thank you again!
