### ISSUE TITLE
Camera2 openGl + FPS + resolution + sound

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/RootEncoder#262]
Tried to record on 60 fps and resulted video is on 15fps recorded.
It records up to 30fps and read somewhere that we need to ask from camera2api to do more frames.
https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics
Also i notice sound is a little out of sync.
Till you look for this i may have found how to enable 60fps.
Also i know that you use samsung s7 and i would like to know if its possible to record on max resolution.

**Comment by pedroSG94** [comment]
I don't know how to increase camera2 fps. I will try find it. 
About high resolutions, I did streams and videos to 4k (3840x2160) without problems with my S7. Anyway high resolutions on any devices have problems to render. I recommend you use only resolutions supported by your native camera app to reduce performance problems.

**Comment by mhackeras** [comment]
Maybe sound was out of sync cause of low fps when setting 60fps.(when i set 60fps i get a 15fps video result)
About resolution.. can you tell me the settings to achieve 4k?
I mean i tried to set surface and encoder to bigger resolutions than 1920x1080 but i get error camera cant open this resolution.

**Comment by pedroSG94** [comment]
Because your are using camera1. If you want use more resolution than 1920x1080 you need use camera2. With camera 2 you can achieve higher resolutions. For 4k I use:
```java
rtspCamera2.prepareAudio() && rtspCamera2.prepareVideo(3840, 2160, 30, 12000 * 1024, false, 2, CameraHelper.getCameraOrientation(this))
```

**Comment by mhackeras** [comment]
Oh god didnt even notice that :O and thanks For CameraHelper.getCameraOrientation(this)
