### ISSUE TITLE
RTMP H265 support

### ISSUE THREAD

**Issue by chengsewennuan** [pedroSG94/RootEncoder#377]
Hi
    How do  add h265 to the TRMP protocol using the following document？
   [https://github.com/ksvc/FFmpeg/wiki]()

**Comment by pedroSG94** [comment]
Do you have a server to test it?

**Comment by chengsewennuan** [comment]
> Do you have a server to test it?

Yes 
[rtmp://pushpgc.sobeycache.com/ys/632756bc2e30169a95164770fbb24611](url)

**Comment by pedroSG94** [comment]
I will try add it. I think you only need modify SrsFlvMuxer and RtmpConnection classes in rtmp module.
Is this a custom server?

**Comment by chengsewennuan** [comment]
The server is customized.I can't provide it， but you can use it.

**Comment by mhackeras** [comment]
h265 is playable to an rtmp server like youtube??
also i would die to see h265 and aac to flv packetization man :'( 
is there any chance we have it?

**Comment by pedroSG94** [comment]
No, RTMP dont support h265. That is unofficial adaptación for h265 so you cant find a server that support ir.

**Comment by GGPENG** [comment]
Even it's not possible to stream h265 encoded video via RTMP, is it possible to record in h265 with RTMPCamera1 or 2?

**Comment by pedroSG94** [comment]
No, because I'm using same encoder to record and stream. You can do it only with RtspCamera1 or RtspCamera2.
