### ISSUE TITLE
Is it possible to apply a filter, without affecting the preview?

### ISSUE THREAD

**Issue by animaonline** [pedroSG94/RootEncoder#689]
So that the filter is only applied to the output stream

**Comment by pedroSG94** [comment]
No by default. You can modify library to do it, but for now, this isn't available

**Comment by animaonline** [comment]
Thanks, I suppose this can be done in OpenGlView? Any tips on how to implement this?

**Comment by pedroSG94** [comment]
Yes. You can do it in that class.
You need modify this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L129
You need know about opengl to do it but, basically you need create a way to render two list of filters. One for preview and one for encoder.

**Comment by animaonline** [comment]
But I only want to apply the filter to the enocer, not the preview.

**Comment by pedroSG94** [comment]
Closing as inactive
