### ISSUE TITLE
Can stream with image, text, filter... but don't show it on camera screen ?

### ISSUE THREAD

**Issue by cryinrain69** [pedroSG94/RootEncoder#726]
Hi.
First, thank you for great lib.
As title, i want stream with image, text,... but i wan't show it on camera screen.
Can I do that?

In demo source code:

> ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(imageObjectFilterRender);
        imageObjectFilterRender.setImage(
                BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher));
        imageObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
//        imageObjectFilterRender.setPosition(TranslateTo.RIGHT);
        imageObjectFilterRender.setPosition(10, 40);

It seems that GlInterface is the class to draw those views on the screen.
So when i call it, it will always be displayed on the screen of the person who is currently livestream.
Can you add the option to show / hide those views, filters, ... on the screen of the person who is currently streaming it ?
Example:
`imageObjectFilterRender.displayForStreamer = true/false`

Thank you so much.

**Comment by pedroSG94** [comment]
Do you mean show filter only in stream and not in preview?
Actually, this is not easy to develop and it will produce performance reduction (reason because I didn't implement it yet). Not really hard reduction, but this could be appreciable in really low spec devices.
The reason?
Actually I'm rendering all in background (camera, filters, etc) and after process all I only need copy the result in preview and encoder (stream result) with the proper scale.

With your suggestion I need create two renders, one for preview and other for encoder.
OpenGL work with renders like layers producing a "chain" to know layer order because you need specify layer order before start render, so if you want use different usage of the one layer (in this case hide/show), you must render all the chain.

```
Example (remember that you are suing GPU so multithreading is not a solution):

  layer 1                    layer 2                                                             layer 3                                                    -- hide -- draw result
     |                              |                                                                        |                                                           |
camera render - filter 1 (show in both, preview and stream) - filter 2 (show in stream and hide in preview) --
                                                                                                                                                                         |
                                                                                                                                                                         -- show -- draw result


The above result is 2 chain each time you have different usage in a filter. The way to optimize it is:


                              --- preview filters x N ---- draw result
                              |
camera render -----
                              |
                              ---- stream filters x N ----- draw result




The actual way is:                  
                                               -- draw preview
                                               |
camera render --- filters x N --
                                               |
                                               -- draw stream
```
Can you imaginate the problem to implement it?

**Comment by cryinrain69** [comment]
> Do you mean show filter only in stream and not in preview?
I mean like that.

I don't really understand the performance or processing issues inside the library. But I think that feature might be really necessary in many cases.
For example in my case: I have more views / logo / sticker / text, ... on the screen. I can handle rotate, scale, move, edit, ... them. I will then call ObjectFilterRender to stream it. I don't need to show it again on the preview.
Also I can add some default views that will be available when streaming without having to display them in preview.

I would be very happy if I had this feature because I really very needed it :+1: 
Thank you.

**Comment by pedroSG94** [comment]
I will mark it as enhancement, but I'm not sure when I will implement it.

**Comment by pedroSG94** [comment]
No plan to implement it. This could produce performance issues
Closing as inactive.
