### ISSUE TITLE
NullPointerException  Attempt to read from field 'android.opengl.EGLContext com.pedro.encoder.input.gl.SurfaceManager.eglContext' on a null object reference

### ISSUE THREAD

**Issue by KunNiu** [pedroSG94/RootEncoder#757]
I'm using v-1.9.6.
`com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:32)
com.pedro.rtplibrary.view.OpenGlViewBase.addMediaCodecSurface(OpenGlViewBase.java:122)
com.pedro.rtplibrary.base.Camera1Base.resetVideoEncoder(Camera1Base.java:551)
com.pedro.rtplibrary.base.Camera1Base.reTry(Camera1Base.java:617)
com.pedro.rtplibrary.base.Camera1Base.reTry(Camera1Base.java:607)
com.sktlab.android.veeko.ui.PushStreamActivity.lambda$onConnectionFailedRtmp$8$PushStreamActivity(PushStreamActivity.java:307)
com.sktlab.android.veeko.ui.-$$Lambda$PushStreamActivity$00Y3cZvC5739SkT1t9sgibUEY8g.run(Unknown Source:4)`

This is not a must happen issue. Seems it will happen when leave streaming Activity, and at same time rtmpCamera1 is reconnecting.
Both rtmpCamera1 and rtmpCamera2 can cause this problem.
I have already stopStream when surfaceDestroyed

` 
@Override
    public void surfaceDestroyed(SurfaceHolder holder) {
        if (rtmpCamera1.isStreaming()) {
            rtmpCamera1.stopStream();
        }
        rtmpCamera1.stopPreview();
//        if (rtmpCamera2.isStreaming()) {
//            rtmpCamera2.stopStream();
//        }
//        rtmpCamera2.stopPreview();
    }
`

**Comment by KunNiu** [comment]
Or maybe the reconnect task is paused and waiting next repeat, and at this time, leave the streaming Activity.

**Comment by pedroSG94** [comment]
I will check it

**Comment by pedroSG94** [comment]
Closing as inactive. Unable to reproduce
