### ISSUE TITLE
Can we check if device supports stereo channel or not?

### ISSUE THREAD

**Issue by parthivmistri** [pedroSG94/RootEncoder#768]
How can we verify that the device supports stereo channel or not as there is some device which supports and some don’t? 
Basically, I would like to have priority for stereo but in case if the device doesn’t support fall back to Mono.

Thanks

**Comment by pedroSG94** [comment]
According with Android documentation. You will receive prepareAudio = false if any parameters specifies is invalid:
https://developer.android.com/reference/android/media/AudioRecord#AudioRecord(int,%20int,%20int,%20int,%20int)
My code:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L69
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L274

**Comment by parthivmistri** [comment]
Yes, @pedroSG94 I'm checking those AudioRecord states but the issue with some manufacturers company is they don’t support stereo channel but AudioRecord don't give `STATE_UNINITIALIZED` or `IllegalArgumentException` only the audio will be distorted for that devices. 

Thanks for the prompt reply.

Also, I want to ask another thing like, I'm using display service to stream device's display that works really great and I have made some improvements according to my case on the top of the library now I want to display device screen in right side and side by side want to display something from another source. How can I merge those two data source and create one frame which will be sent via RTMP?

**Comment by pedroSG94** [comment]
If you want send video you can try use SurfaceFilter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L266

**Comment by pedroSG94** [comment]
About check if stereo is supported. I'm not sure how to check it by other way. Any sugestion to check it is welcome

**Comment by parthivmistri** [comment]
I'm also finding the solution for it. I'll create a PR as soon as I find some concrete way to check availability of channels.
