### ISSUE TITLE
Audio laggy over RTMP with UVC

### ISSUE THREAD

**Issue by alejandrorosas** [pedroSG94/RootEncoder#806]
Hi, I've started a new project where I'm trying to stream UVC video over RTMP, but it looks the audio I get is too laggy. I'm using your old sample usb test as base.

I'm using this configuration for video:
https://github.com/alejandrorosas/Stream-USB-test/blob/771470125eb7d17e0654bfaba5467502f65e2d79/app/src/main/java/com/pedro/usbtest/RtpService.kt#L94

and for audio:
https://github.com/alejandrorosas/Stream-USB-test/blob/771470125eb7d17e0654bfaba5467502f65e2d79/app/src/main/java/com/pedro/usbtest/streamlib/USBBase.java#L174

I've tried with different bitrates, the one that sounds better is 48hz and 41hz, but is still supper laggy and impossible to understand anything from the audio.

**Comment by alejandrorosas** [comment]
It seems I could fix the audio issue rolling back to a previous version of the library. For now with the `1.5.3` it works perfectly. Tomorrow will try if I can bisect and find the update where it broke the audio.

**Comment by pedroSG94** [comment]
try use audio in sync mode:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L130
- Copy that method in your class
- In your init method:
https://github.com/alejandrorosas/Stream-USB-test/blob/771470125eb7d17e0654bfaba5467502f65e2d79/app/src/main/java/com/pedro/usbtest/streamlib/USBBase.java#L91
Replace:
```java
   microphoneManager = new MicrophoneManager(this);
   audioEncoder = new AudioEncoder(this);
```
To:
```java
 setMicrophoneMode(MicrophoneMode.SYNC);
```

**Comment by alejandrorosas** [comment]
No luck with this change, I still hear the audio laggy :(.

I've been trying to bisect the versions and the last version I could make it work and hear the audio perfectly was the `1.8.5`. 

While from the `1.8.6` to `1.9.5` I had a crash (BufferOverflowException at BaseEncoder.processInput(BaseEncoder.java:113)) so I could not verify if it was working or not, and in the version `1.9.6` I could start but the audio was laggy again.

**Comment by pedroSG94** [comment]
Did you try last library version (1.9.9) with my change?

**Comment by alejandrorosas** [comment]
> Did you try last library version (1.9.9) with my change?

Yes, it was still happening. The latest version I could hear correctly the audio was the `1.8.5`

**Comment by mylaimani** [comment]
I am also facing the problem with audio I had given code like this

    private boolean prepareEncoders() {
        return rtmpUSB.prepareVideo(1280,720,30, 2000 * 1024, 0, mUVCCamera)
                && rtmpUSB.prepareAudio(128 * 1024,44100,
                true, true,
                true);
    }

Audio is fast and not clear

**Comment by pedroSG94** [comment]
Can you hear all fine using rtmpCamera1 instead of rtmpUSB?
To discard mediacodec async implementation try this:
In BaseEncoder:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java#L47
replace:
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
      createAsyncCallback();
      codec.setCallback(callback, handler);
      codec.start();
    } else {
      codec.start();
      handler.post(new Runnable() {
        @Override
        public void run() {
          while (running) {
            try {
              getDataFromEncoder();
            } catch (IllegalStateException e) {
              Log.i(TAG, "Encoding error", e);
            }
          }
        }
      });
    }
```
to:
```java
codec.start();
      handler.post(new Runnable() {
        @Override
        public void run() {
          while (running) {
            try {
              getDataFromEncoder();
            } catch (IllegalStateException e) {
              Log.i(TAG, "Encoding error", e);
            }
          }
        }
```

**Comment by mylaimani** [comment]
Yes I tested now I can hear everything perfect using rtmpCamera1 with latest version 1.9.9

For rtmpUSB I used version 1.8.5 after that only Audio is worked.

**Comment by alejandrorosas** [comment]
Still having lags, did a clone (https://github.com/alejandrorosas/rtmp-rtsp-stream-client-java/pull/1) and applied your suggested changes, but it does still have audio lag

**Comment by diashima** [comment]
Hello! Sorry for offtop message, but can you share with your code of streaming UVC? 
I have spent over two weeks trying to make an rtmp strem with USB camera, but i didn't achieve anything...
I have tried every github projects available

**Comment by alejandrorosas** [comment]
> Hello! Sorry for offtop message, but can you share with your code of streaming UVC?
> I have spent over two weeks trying to make an rtmp strem with USB camera, but i didn't achieve anything...
> I have tried every github projects available

I have been working on this one, that is working for me 😃 
https://github.com/alejandrorosas/android-uvc-rtmp-stream

**Comment by diashima** [comment]
> > Hello! Sorry for offtop message, but can you share with your code of streaming UVC?
> > I have spent over two weeks trying to make an rtmp strem with USB camera, but i didn't achieve anything...
> > I have tried every github projects available
> 
> I have been working on this one, that is working for me 😃
> https://github.com/alejandrorosas/android-uvc-rtmp-stream

thank you :) now it works for me
