### ISSUE TITLE
Stream auth error with setAuthorization

### ISSUE THREAD

**Issue by 1-CharlieShin** [pedroSG94/RootEncoder#838]
I have to make an app that plays RTSP streaming from an IP Camera.

So I am testing via this app for RTSP streaming.
Because of authorization I added a line in `DisplayService.kt` file.

```
fun init(context: Context) {
      contextApp = context
      if (displayBase == null) {
        displayBase = RtmpDisplay(context, true, connectCheckerRtp)
      }
      displayBase?.setAuthorization("my_id", "my_password")
}
```
I added `displayBase?.setAuthorization("my_id", "my_password")`.
But I see only "Stream auth error" when I put address in the TextBox.

Does the `setAuthorization("id", "password")` function work in other IP Camera except Wowza server?
(IP Camera Model : Dahua DH-SF125)

Sorry for short English. Thanks.

**Comment by pedroSG94** [comment]
Hello,

This library is not a player so you can't play an IP camera (this is a pusher).
I recommend you check other project like exoplayer, VLC or ijkplayer
