### ISSUE TITLE
Default Application : Urgent Help

### ISSUE THREAD

**Issue by np8698** [pedroSG94/RootEncoder#842]
Hey, 
I am working for the first time with RTSP -RTMP streaming. Can someone help me out about how does the default app work given in this project, so I can get a better understand regarding the same. Or maybe if there is a list of steps or a video to help me out figure it, that would be really helpful.

Urgently needed.
Thank you ! Cheers !

**Comment by pedroSG94** [comment]
Default example is only a code example to stream with default parameters (640x480 resolution and stereo audio with 3200hz).
In that activity you can switch camera (back and front), record a video in a local file and stream to media server.
Edit text is used to indicate endpoint used to stream to media server after press start stream. If you need a server to stream you can use any of this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested
