### ISSUE TITLE
SPS or pps is null

### ISSUE THREAD

**Issue by yyt231** [pedroSG94/RootEncoder#864]
![image](https://user-images.githubusercontent.com/24969821/118797204-e930df00-b8ce-11eb-9bf9-5446f0d41060.png)

I can play RTSP streaming video in VLC, but I can’t use this library。

**Comment by pedroSG94** [comment]
Using my app example try check if this method is called:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L172
If not called try use software encoder by this way before prepareVideo:
```java
rtspCamera1.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
```
