### ISSUE TITLE
Recording more than one video from single camera

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/RootEncoder#892]
is it doable to record two videos at the same time from single camera?,
I want to make an interleaved video recording so I want two videos to be recorded at the same time,
if it's doable, can you please give me an intuition about how to do it.

**Comment by pedroSG94** [comment]
Hello,
I create a second instance of this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L73
And call same method that you call with the first
