### ISSUE TITLE
how to mute microhphone without muting media audio?

### ISSUE THREAD

**Issue by Arslanmajeed270** [pedroSG94/RootEncoder#898]
Hi @pedroSG94, I want to mute microphone but not the media. Right now i am calling `rtmpCamera1.disableAudio();` for the mute and `rtmpCamera1.enableAudio();` for the unmute. But it's also mute the media audio as well. Is there any way so that only microphone media get muted rather then all the audio?

Thanks,

**Comment by Arslanmajeed270** [comment]
> Hello,
> 
> This is normal because media audio is detected by microphone so if you mute microphone you also disable it.
> Actually you need choose if you want get audio from microphone or internal audio with this method:
> 
> ```java
> prepareInternalAudio()
> ```
> 
> Internal audio is only available in display mode and android API 29+:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java#L212

Thanks for the reponse. During the stream if we switch audio from `prepareAudio()` to `prepareInternalAudio()` then stream will be stop or not? Also can you tell me how can i use this function?

**Comment by pedroSG94** [comment]
No, you can change to prepareInternalAudio on fly. You need stop stream before it.
