### ISSUE TITLE
How can I copy what the textureView is displaying and encode it

### ISSUE THREAD

**Issue by mudcastles** [pedroSG94/RootEncoder#900]
**I am using the textureview display video. This video is from other places. I can't get video data, but I want to encode and stream for each frame displayed in TextureView, how can I get video frame data? Or how to share the frame buffer to the input surface provided by the encoder? Can you give me a sample program?**

**Comment by pedroSG94** [comment]
You have multiple ways to send a video frame to rtmp/rtsp module.
1 - Get raw h264 frames from any source and send it directly to rtmp/rtsp module.
2 - Get a NV21/YUV12 frame and encode it using VideoEncoder class of the library that return you a raw h264. You can send this frame to rtmp/rtsp modules
3 - Render a surface produced by VideoEncoder class that return you a raw h264 frame. You can send this frame to rtmp/rtsp modules

The question is, which one can you do with your video data?

You can read Camera1Base to check this cases:
Case 1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L880
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L185
Case 2 (read prepareVideo, startStream and stopStream to know how to use videoEncoder class):
YUV frame provided by Android Camera API:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L894
Case 3 (before send surface you need use prepareVideo):
I send surface provided by VideoEncoder class to a class that render it using OpenGl but you can render that surface by any way to want:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L620

**Comment by mudcastles** [comment]
Is there a way to get the video stream frame directly through the surfaceTexture provided by the textureView? Or share the frame buffer to the surface provided by videoEncoder?

**Comment by pedroSG94** [comment]
Depend of few thing but you can do this:
1 - You can try convert your surfacetexture to surface and get frames with canvas (this maybe not work for you but it is fast to test). This way use CPU so performance increase with better devices but a normal device maybe can handle 15-20 fps in 1080p. This is my recommend way.
You can try with native way if not working as normal way:
https://stackoverflow.com/questions/33692409/how-to-associate-the-existing-surface-to-mediacodec-encoder-surface
I recommend you create a project to do a demo doing a copy to a surface of SurfaceView. After that, you can apply this to my library:
1.1 - Go to camera1 or camera2 base and remove CameraManager class that will be replaced by this canvas render.
1.2 Replace CameraManager funcionality to your new render using OpenGlView (Using OpenGlView you can copy data to surface provided by openglview.getSurface()).

2 - TextureView can get a bitmap that contain a screenshoot of your video frame but it has really bad performance.

The hard way but with better performance:

3 - You can try copy frames to another surface using openGL but you need study this API and it is a bit complex if you never do it. You can use SurfaceManager class provided byt this library to copy frames but you need understand how to create a openGL context and how to use it to work.
