### ISSUE TITLE
Livestreaming with raw ByteArray

### ISSUE THREAD

**Issue by linhlq58** [pedroSG94/RootEncoder#909]
Hi @pedroSG94,

Is there a way to livestream with raw ByteArray (data source from camera preview) using your library?

**Comment by pedroSG94** [comment]
This library is doing it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L315
And send to VideoEncoder here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L895

**Comment by linhlq58** [comment]
@pedroSG94  I tried send byte[] through inputYUVData() but I received these logs. It seems that it can not encode video frames.

I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 258
I/VideoEncoder: frame discarded
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 248
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 245
D/RtmpConnection: wrote packet: RTMP Audio, size: 263
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 264
D/RtmpConnection: wrote packet: RTMP Audio, size: 252
I/VideoEncoder: frame discarded
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 265
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 295
D/RtmpConnection: wrote packet: RTMP Audio, size: 260
I/VideoEncoder: frame discarded
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 258
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 245
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 255
D/RtmpConnection: wrote packet: RTMP Audio, size: 264
D/RtmpConnection: wrote packet: RTMP Audio, size: 283
I/VideoEncoder: frame discarded
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 257
I/VideoEncoder: frame discarded
D/RtmpConnection: wrote packet: RTMP Audio, size: 253
I/VideoEncoder: frame discarded

**Comment by linhlq58** [comment]
I also get these logs:

W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/divx311
W/VideoCapabilities: Unsupported mime video/divx4
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W/Utils: could not parse long range '175-174'
I/OMXClient: IOmx service obtained
W/ExtendedACodec: Failed to get extension for extradata parameter
I/AudioEncoder: prepared
E/RtmpFUCameraBase: Streaming or preview stopped, ignored
I/VideoEncoder: VideoEncoder OMX.qcom.video.encoder.avc
    Color supported: 2141391876
I/VideoEncoder: Color supported: 2130708361
    Color supported: 2135033992
    Color supported: 21
I/OMXClient: IOmx service obtained
I/VideoEncoder: Prepare video info: YUV420SEMIPLANAR, 480x640
    bitrate mode CBR not supported using default mode
I/ExtendedACodec: setupVideoEncoder()
W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
    do not know color format 0x7f000789 = 2130708361
I/ACodec: setupAVCEncoderParameters with [profile: High] [level: Level3]
I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
    setupVideoEncoder succeeded
I/ExtendedACodec: [OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 4) = {
      int32_t color-format = 21
      int32_t i-frame-interval = 2
      string mime = "video/avc"
      int32_t width = 480
      int32_t bitrate = 1228800
      int32_t max-input-size = 0
      int32_t frame-rate = 30
      int32_t height = 640
      int32_t encoder = 1
    }
W/ExtendedACodec: Failed to get extension for extradata parameter
I/VideoEncoder: prepared
    started
    
    -----------------------------------------
    
    
    I/BaseEncoder: Encoding error
    java.lang.IndexOutOfBoundsException: off=0, len=512000 out of bounds (size=460800)
        at java.nio.Buffer.checkBounds(Buffer.java:587)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:285)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:156)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:196)
        at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:217)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1688)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1646)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
I/chatty: uid=10220(com.botbanhang.botlive) BaseEncoder identical 2 lines
I/BaseEncoder: Encoding error
    java.lang.IndexOutOfBoundsException: off=0, len=512000 out of bounds (size=460800)
        at java.nio.Buffer.checkBounds(Buffer.java:587)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:285)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:156)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:196)
        at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:217)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1688)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1646)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by pedroSG94** [comment]
Which resolution are you using?

**Comment by linhlq58** [comment]
I'm using default resolution (640 x 480). 

More details: I'm using a face AR library, which is using GLSurfaceView to rendering images. After rendering, that library has a callback returning NV21 frames in byte[]. I'm editing Camera1Base & RtmpCamera1. Instead of sending frames to VideoEncoder at onPreviewFrame() as default, I send them whenever that library return a frame. Then I have the error above.

What can I do to fix this error?

**Comment by pedroSG94** [comment]
VideoEncoder only support YUV images using byte[]
YUV image size is = width * height * 3 / 2. In your case 460800 but you set an image with size 512000.
Are you sure that your image is YUV format?

**Comment by linhlq58** [comment]
@pedroSG94 Thank you! I did realize my mistake. While output video resolution for streaming is 640x480, input video resolution is still 1280x720.

I will close this issue here.

**Comment by linhlq58** [comment]
Hi @pedroSG94,
I want to add watermark (text, image) to YUV frame before sending to RTMP stream. Could you help me how to do this?

**Comment by pedroSG94** [comment]
I don't know how to implement it using YUV byte array.

Maybe mix both images using canvas and convert RGB image provided by convas to YUV is a solution but the performance is really bad

**Comment by linhlq58** [comment]
I see. Which method do you recommend when I have to add water mark to livestream using GLSurfaceView?

**Comment by pedroSG94** [comment]
You can create an external texture with opengl and add it to your shader. I'm doing it with ImageObjectFilter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/object/ImageObjectFilterRender.java
Parent class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/object/BaseObjectFilterRender.java

You can check result using my app example OpenGl RTMP/RTSP, open top-right menu and select image.

**Comment by linhlq58** [comment]
I tried this method using ImageObjectFilter and it worked but I lost camera preview on GLSurfaceView. 

Before using ImageObjectFilter:
![image](https://user-images.githubusercontent.com/10673572/130311634-4800810f-cebe-4ea5-ae81-2e0ee840e166.png)

After using ImageObjectFilter:
![image](https://user-images.githubusercontent.com/10673572/130311646-6ab82894-69f7-4d82-b38c-4ccc4748f0cb.png)

Here is my code:

`@Override
    public void onSurfaceCreated(GL10 gl, EGLConfig config) {
        Log.d(TAG, "onSurfaceCreated. thread:" + Thread.currentThread().getName());
        GlUtil.logVersionInfo();
        mProgramTexture2d = new ProgramTexture2d();
        mProgramTextureOES = new ProgramTextureOES();
        mProgramLandmarks = new ProgramLandmarks();

        imageObjectFilterRender = new ImageObjectFilterRender();
        imageObjectFilterRender.initGl(720, 1280, mActivity, 720, 1280);
        imageObjectFilterRender.setImage(
                BitmapFactory.decodeResource(mActivity.getResources(), R.drawable.anhs));
        imageObjectFilterRender.setDefaultScale(720,
                1280);
        imageObjectFilterRender.setPosition(TranslateTo.RIGHT);

        mCameraTexId = GlUtil.createTextureObject(GLES11Ext.GL_TEXTURE_EXTERNAL_OES);
        mBackgroundHandler.post(new Runnable() {
            @Override
            public void run() {
                openCamera(mCameraFacing);
                startPreview();
            }
        });
        LimitFpsUtil.setTargetFps(LimitFpsUtil.DEFAULT_FPS);
        mOnRendererStatusListener.onSurfaceCreated();
    }`

`@Override
    public void onDrawFrame(GL10 gl) {
        .....................................

        imageObjectFilterRender.draw();

        ........................................
    }`

**Comment by pedroSG94** [comment]
You aren't rendering camera data in your view. You can use my OpenGlView instead of your view:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java

**Comment by pedroSG94** [comment]
Closing as inactive
