### ISSUE TITLE
Flutter plugin error with openglview

### ISSUE THREAD

**Issue by RomainPetit1** [pedroSG94/RootEncoder#923]
Hello, 
I'm working on a flutter plugin and I have an issue with the openglview.
When I start a livestream I have this error : "Make sure the SurfaceView or associated SurfaceHolder has a valid Surface"

To be easier to use I developed my [library](https://github.com/apivideo/android-live-stream) in Kotlin, so I just have to init ApiVideoLiveStream class with the context, the ConnectCheckerRtmp, and an optional openglview.
To use the preview I need the openglview. So I added an xml file and a class that init the view (LiveStreamView) by using this xml. 
I did the exact same thing for [react native](https://github.com/apivideo/react-native-livestream) and it works fine.
But there I don't know why it doesn't work. 

PS: If I don't use the preview the stream works well.

here is my code sample:

```kotlin
   class LiveStreamNativeView(private val context: Context, id: Int, creationParams: Map<String?, Any?>?, messenger: BinaryMessenger):
    PlatformView, ConnectCheckerRtmp, MethodChannel.MethodCallHandler {

    private var channel: MethodChannel = MethodChannel(messenger, "plugin")

    private lateinit var apiVideo: ApiVideoLiveStream
    private var livestreamKey: String = ""
    private var url: String? = null
    private var methodChannel: MethodChannel? = null
    private lateinit var view: LiveStreamView


    init {
        channel.setMethodCallHandler(this)
        initMethodChannel(messenger, id)
        view = LiveStreamView(context)
        apiVideo = ApiVideoLiveStream(context, this, view.findViewById(R.id.opengl_view), null)
    }
}
```

```kotlin
class LiveStreamView(context: Context): ConstraintLayout(context){
    init {
        inflate(context, R.layout.flutter_livestream, this)
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <com.pedro.rtplibrary.view.OpenGlView
        app:keepAspectRatio="true"
        app:aspectRatioMode="adjust"
        android:id="@+id/opengl_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:AAEnabled="false"
        app:isFlipHorizontal="false"
        app:isFlipVertical="false"/>
</androidx.constraintlayout.widget.ConstraintLayout>
```
You can find the project [here](https://github.com/RomainPetit1/flutter-livestream/tree/master/android/src/main/kotlin/com/example/plugin).
If someone can help me it would be awesome. 
Thanks in advance.

**Comment by pedroSG94** [comment]
Keep in mind that you need start preview after surface is completly created like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L470

I'm not sure if you are doing it because I can't find any activity in your code. You can start preview with 1 or 2 seconds of delay (without block main thread) to make sure that this is your case.
Try find in flutter the equivalent class of SurfaceHolder.Callback that I use in OpenGlRtmpActivity
