### ISSUE TITLE
TakePhoto and cropped bitmap

### ISSUE THREAD

**Issue by FunnyDevs** [pedroSG94/RootEncoder#935]
I use rtspservercamera1 with OpenGlView and when i try to take photo (with both cameras, back and front) the result is a cropped bitmap

![1578446753291](https://user-images.githubusercontent.com/10280983/132550446-226322ef-c31c-471e-825e-e35386a4e163.jpg)

**Comment by pedroSG94** [comment]
Hello, 

I tested it with my app and all is working as expected (no cropped).
I did a photo without aspect ratio enabled and with aspect ratio in both modes (adjust and fill).
Can you share me a code example used to reproduce error?

I did tests with this steps:
- Replace SurfaceView to OpenGlView in layout:
https://github.com/pedroSG94/RTSP-Server/blob/master/app/src/main/res/layout/activity_camera_demo.xml#L9
- Go to example in this line: https://github.com/pedroSG94/RTSP-Server/blob/master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt#L104
- Replace line 104 to 
```java
        rtspServerCamera1.glInterface.takePhoto {
          val f = File(getExternalFilesDir(null)?.absolutePath + "/photo.png")
          it.compress(Bitmap.CompressFormat.PNG, 100, FileOutputStream(f))
        }
```
- Compile and open app example and press switch camera to take a photo that you can check in: Android > data > com.pedro.sample > files
