### ISSUE TITLE
[Question] About fixTimeStamp() method

### ISSUE THREAD

**Issue by agent10** [pedroSG94/RootEncoder#936]
Hey. I see that you have fixTimeStamp() method in BaseEncoder.
Probably it's because we have to send packets in strictly increasing order and you should change older encoded frame timestamp to be at least as a previous one.
What's about using PriorityBlockingQueue in RTXX senders to sort frames by timestamps automatically?

Correct me if I'm wrong..

**Comment by pedroSG94** [comment]
Hello,

fixTimeStamp() was developed to fix a bug recording a file not for stream. The error is this one:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/659

In this case, I prefer implement this fix in VideoEncoder because this solve error recording files and streaming
