### ISSUE TITLE
How to get h264 data when using SurfaceTexture create camera

### ISSUE THREAD

**Issue by fantasy-mark** [pedroSG94/RootEncoder#948]
when i try to trace how to get video data，but i found
```
private void processInput(@NonNull ByteBuffer byteBuffer, @NonNull MediaCodec mediaCodec,
      int inBufferIndex) throws IllegalStateException {
    try {
      Frame frame = getInputFrame();
      while (frame == null) frame = getInputFrame();
      byteBuffer.clear();
      int size = Math.max(0, Math.min(frame.getSize(), byteBuffer.remaining()) - frame.getOffset());
      byteBuffer.put(frame.getBuffer(), frame.getOffset(), size);
      long pts = System.nanoTime() / 1000 - presentTimeUs;
      mediaCodec.queueInputBuffer(inBufferIndex, 0, size, pts, 0);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    } catch (NullPointerException | IndexOutOfBoundsException e) {
      Log.i(TAG, "Encoding error", e);
    }
  }
```
the `getInputFrame` no go in to，can you tell me in this way，the h264 data where create。。。thx a lot！

**Comment by pedroSG94** [comment]
In this callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L896
You have the same callback in all Base classes

**Comment by fantasy-mark** [comment]
Thx a lot! But i don't know the GLES how to create data to `MediaCodec` as Encoder,  it work in JNI code?

**Comment by pedroSG94** [comment]
I'm not using JNI in this project.
To work with OpenGl I'm using this:
https://developer.android.com/guide/topics/graphics/opengl#packages

Actually I'm working like this:
- Create a surface using OpenGl that will be send to Camera API:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L84
- Link MediaCodec surface to an OpenGl context (I'm doing the same for preview where I link SurfaceView surface):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlViewBase.java#L146
- Wait for a notification where I receive that opengl surface was updated and I can render that frame into both opengl context to updated both surfaces (MediaCodec and Preview).
- Render loop:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L184
- Update notification received from surface used in Camera API:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlViewBase.java#L203

**Comment by fantasy-mark** [comment]
You are very very kind, and i found `MediaCodec#createInputSurface`, in this way `MediaCodec` auto encode data from render of Surface, just take the data from `MediaCodec Output Buffer Queue`, thx a lot！！
