### ISSUE TITLE
Simultaneous preview, recording and stream for rear and front camera

### ISSUE THREAD

**Issue by ggpaeg** [pedroSG94/RootEncoder#949]
Hi!

I would like to know if it's possible to preview, record, and stream Android rear and front cameras, simultaneously. 

Both options work for me: 
- one stream/preview surface/media file split into two media sources
- two stream/preview surface/media files containing one video source on each. 

That project is working fine for me: https://github.com/ananthrajsingh/front-rear-simultaneous-camera
Would be great to see that resource in our library!

**Comment by pedroSG94** [comment]
Yes, it is possible but you need modify the library code. I explained how to do it in this post:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/243
