### ISSUE TITLE
How to detect rtsp server is disconnect phyiscally from network?

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/RootEncoder#957]
Hi pedro,

I am using RtspDisplay and DisplayService to stream rtsp to server (aler9/rtsp-simple-server - Docker Hub). How can I know if the device that run the server program is physically disconnect from my app? If I just close the server program from the device, it can be detected by on DisconnectRtp() under DisplayService. But if I remove the LAN line from the device that run the server program, it cannot be detected.
Do you have any idea how can I detect this?
Thank you very much

**Comment by pedroSG94** [comment]
Yes, it was added to rtsp and rtmp:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpClient.kt#L230
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.kt#L323
Test it and let me know if it is working in your case
