### ISSUE TITLE
publishing stream to two servers, if one server is physically disconnected, the other server disconnected too?

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/RootEncoder#962]
Hi pedro,

I am using RtspDisplay. I created two rtspclient in rtspdisplay to publish the stream to two servers. However, I found that if one server is physically disconnected from the network, the other server will be disconnected too. Is there any way to solve this problem?

Thank you so much.

**Comment by lchy12345** [comment]
Hi Pedro,

I have tried to ping the other server after one server is disconnected physically. However, it still failed. I have attached the  full logcat here. It would be grateful if you have any idea to solve the problem. Thank you very much.

[new 5.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7495206/new.5.txt)

**Comment by lchy12345** [comment]
In fact, I found out that when one server is disconnected physically, the rtsp stream to the other server is stopped too. but I have not idea why that's happen

**Comment by pedroSG94** [comment]
If you can't ping the other server. It isn't a library error or code error. 
You need check your server because it is disconnected when you disconnect the other one.

**Comment by lchy12345** [comment]
Oh.. I mean I can ping the other server. But the rtsp stream connection lost.

**Comment by pedroSG94** [comment]
I can't see any disconnect error in logcat. 
-Can you share me a log of reason String provided in onConnectionFailed callback?

-Are you sure that you are stopping only the stream that fail instead of both? Can you share me how are you doing stop stream?

**Comment by lchy12345** [comment]
The reason is no response from server for the one I physically remove the lan cable.
I didn't stop the stream when receiving onConnectionFailed. Do I need to stop the stream?

**Comment by pedroSG94** [comment]
Which reason do you have from the other one? If you don't receive onConnectionFailed callback the stream should be still working.
It is recommended to stop/retry if you receive onConnectionFailed to stop encoders and other things becuase you are not using it.

Check the following:
- Use one RtmpConnectionChecker in each stream object.
- Check that you are not stopping the other stream in your code.
- Use this method to ping your server in the stream that should work after diconnect one server in onConnectionFailed of that stream (print the result in logcat):
```java
  public boolean ping(String ip) {
    Runtime runtime = Runtime.getRuntime();
    try {
      Process ipProcess = runtime.exec("/system/bin/ping -c 1 " + ip);
      int exitValue = ipProcess.waitFor();
      return exitValue == 0;
    } catch (Exception ignored) { }
    return false;
  }
```

**Comment by pedroSG94** [comment]
Closing as inactive.
