### ISSUE TITLE
Trouble using library on Java backend

### ISSUE THREAD

**Issue by westy92** [pedroSG94/RootEncoder#981]
Hi, I'm hoping to use part of this library (`RtmpClient`) on a Java backend to verify RTMP(S) URLs and connections.

My `pom.xml` looks like this:
```xml
<project>
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    ...
    <dependencies>
        <dependency>
            <groupId>com.github.pedroSG94.rtmp-rtsp-stream-client-java</groupId>
            <artifactId>rtmp</artifactId>
            <version>2.1.4</version>
        </dependency>
    </dependencies>
</project>
```

Here's the error:
```
$ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< XYZ >--------------
[INFO] Building XYZ
[INFO] --------------------------------[ war ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.572 s
[INFO] Finished at: 2021-11-18T12:39:02-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project XYZ: Could not resolve dependencies for project XYZ: Failure to find com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtmp:jar:2.1.4 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by pedroSG94** [comment]
Your pom seems fine. I don't know the possible reason.
Anyway, rtmp contain a bit of Android dependencies in this case Log, MediaCodec.BufferInfo and Base64 classes (maybe this is the problem).
I recommend you download the folder and add it to your project manually. To replace Android clases you can use this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/rtmp/src/test/java/android

After that, you have a totally functional rtmp module on any platform and you can do the same for rtsp.

**Comment by pedroSG94** [comment]
I will mark this as feature because even though you can download it using maven. The rtmp should crash for the Android dependencies. 
I will try remove Android dependencies in both modules and test maven download but it is not priority for now.

**Comment by westy92** [comment]
I was able to get it to work with these instructions:

We use `https://github.com/pedroSG94/rtmp-rtsp-stream-client-java` and cannot use it directly from Maven due to https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/981.

Instead, do the following:
1. Copy `rtmp-rtsp-stream-client-java/rtmp/src/test/java/android/` to `src/main/java/android/`.
2. Copy `rtmp-rtsp-stream-client-java/rtmp/src/main/java/com/` to `src/main/java/com/`.
3. Add `public static final int BUFFER_FLAG_KEY_FRAME = 1;` to our `andorid/media/MediaCodec.java`. (Source https://android.googlesource.com/platform/frameworks/base.git/+/master/media/java/android/media/MediaCodec.java)
4. Add `public static final int NO_WRAP = 2;` to our `android/util/Base64.java`. (Source https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/util/Base64.java)


Note: I also had to configure my java project to compile kotlin files.
