### ISSUE TITLE
Add the date time in the RTSP video camera 1 streaming to server

### ISSUE THREAD

**Issue by Shanmugamsundarrajan** [pedroSG94/RootEncoder#998]
Add the date time in the RTSP video camera 1 streaming to server, Please let me know how to achieve it in the code

**Comment by pedroSG94** [comment]
Already answered:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/997
Please, avoid open duplicated issues

**Comment by Shanmugamsundarrajan** [comment]
We want to add it in the Surface view mode. The same setTextToStream() is not available in the Surface view mode. Please help on the same

**Comment by pedroSG94** [comment]
SurfaceView doesn't support this feature so you will need use OpenGlView or develop it yourself.

**Comment by Shanmugamsundarrajan** [comment]
ok
